import { test, expect, type Page } from "@playwright/test"
import { readFile } from "node:fs/promises"
import sharp from "sharp"

test.beforeEach(async ({ context }) => {
  await context.addCookies([{ name: "NEXT_LOCALE", value: "en", url: "http://localhost:3000" }])
})
test.setTimeout(60000)
const row = (page: Page, id: string) => page.locator(`[data-tier-row="${id}"]`)
async function assign(page: Page, item: string, label: string) {
  await page.getByRole("button", { name: `Assign ${item}`, exact: true }).click()
  await page.getByRole("radio", { name: label, exact: true }).click()
}
async function drag(page: Page, item: string, sourceRow: string, targetRow: string, targetItem?: string, fromName = false) {
  await expect(page.getByRole("status").filter({ hasText: "Saved on this device" })).toBeVisible()
  const stored = await savedBoards(page)
  const source = row(page, sourceRow).getByRole("button", { name: `Assign ${item}`, exact: true, includeHidden: true })
  const itemId = await source.getAttribute("data-tier-item-id")
  await source.scrollIntoViewIfNeeded()
  const card = await source.boundingBox()
  if (!card) throw new Error("Missing card")
  // Start in the artwork or the name, deliberately away from the grip marker.
  const startX = card.x + 20, startY = fromName ? card.y + card.height - 10 : card.y + 40
  await page.mouse.move(startX, startY)
  await page.mouse.down()
  await page.mouse.move(startX + 15, startY + 15, { steps: 3 })
  await expect(source).toHaveAttribute("data-dragging", "true")
  await expect(page.locator("[data-tier-drag-preview]")).toBeVisible()
  await row(page, targetRow).scrollIntoViewIfNeeded()
  const destination = targetItem ? row(page, targetRow).getByRole("button", { name: `Assign ${targetItem}`, exact: true }) : row(page, targetRow)
  const target = await destination.boundingBox()
  if (!target) throw new Error("Missing drop target")
  await page.mouse.move(target.x + target.width - 30, target.y + 40, { steps: 12 })
  await expect(row(page, targetRow)).toHaveAttribute("data-drop-state", "active")
  await expect(row(page, targetRow).locator(`[data-tier-insertion-preview="${itemId}"]`)).toBeVisible()
  expect(await savedBoards(page)).toEqual(stored)
  await page.mouse.up()
  await expect(page.locator("[data-tier-drag-preview]")).toHaveCount(0)
  await expect(page.getByRole("dialog")).toHaveCount(0)
}

async function savedBoards(page: Page) {
  return page.evaluate(() => Object.entries(localStorage).filter(([key]) => key.startsWith("tier-list:v1:")).sort(([a], [b]) => a.localeCompare(b)))
}

test("source filters recover ranked cards and gear contains the extra row actions", async ({ page }) => {
  await page.goto("/tier-lists/standard")
  const filter = page.getByRole("combobox", { name: "Filter items" })
  await expect(filter).toHaveValue("unassigned")
  const controls = page.getByRole("region", { name: "S", exact: true }).locator("[data-tier-row-controls]")
  await expect(controls.getByRole("button")).toHaveCount(3)
  const gear = controls.getByRole("button", { name: "Options for row S", exact: true })
  await gear.focus()
  await page.keyboard.press("ArrowDown")
  await expect(page.getByRole("menuitem", { name: "Edit row S", exact: true })).toBeFocused()
  await expect(page.getByRole("menuitem", { name: "Clear row S", exact: true })).toBeDisabled()
  await expect(page.getByRole("menuitem", { name: "Delete row S", exact: true })).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(gear).toBeFocused()
  await assign(page, "Exploration", "S")
  await expect(row(page, "source").getByRole("button", { name: "Assign Exploration", exact: true })).toHaveCount(0)
  await filter.selectOption("all")
  await expect(row(page, "source").getByRole("button", { name: /^Assign / })).toHaveCount(6)
  await filter.selectOption("assigned")
  await expect(row(page, "source").getByRole("button", { name: /^Assign / })).toHaveCount(1)
  await page.getByPlaceholder("Search items…").fill("Building")
  await expect(row(page, "source").getByRole("button", { name: /^Assign / })).toHaveCount(0)
  await page.getByPlaceholder("Search items…").fill("")
  await drag(page, "Exploration", "source", "a")
  await expect(row(page, "s").getByRole("button", { name: "Assign Exploration", exact: true })).toHaveCount(0)
  await expect(row(page, "a").getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  await drag(page, "Exploration", "a", "source")
  await expect(row(page, "source").getByRole("button", { name: /^Assign / })).toHaveCount(0)
  await filter.selectOption("unassigned")
  await expect(row(page, "source").getByRole("button", { name: /^Assign / })).toHaveCount(6)
})

test("live insertion shifts cards, stays stable, cancels and commits one undo step", async ({ page }, testInfo) => {
  await page.goto("/tier-lists/standard")
  await assign(page, "Strategy", "S")
  await assign(page, "Building", "S")
  await expect(page.getByRole("status").filter({ hasText: "Saved on this device" })).toBeVisible()
  const stored = await savedBoards(page)
  const source = row(page, "source").getByRole("button", { name: "Assign Exploration", exact: true })
  await source.scrollIntoViewIfNeeded()
  const start = await source.boundingBox()
  if (!start) throw new Error("Missing source")
  await page.mouse.move(start.x + 20, start.y + 40)
  await page.mouse.down()
  await page.mouse.move(start.x + 35, start.y + 40)
  await row(page, "s").scrollIntoViewIfNeeded()
  const strategy = row(page, "s").getByRole("button", { name: "Assign Strategy", exact: true })
  const destination = await strategy.boundingBox()
  if (!destination) throw new Error("Missing destination")
  await page.mouse.move(destination.x + 20, destination.y + 40, { steps: 12 })
  const gap = row(page, "s").locator('[data-tier-insertion-preview="exploration"]')
  await expect(gap).toBeVisible()
  const gapBox = await gap.boundingBox(), shifted = await strategy.boundingBox()
  expect(shifted!.x).toBeGreaterThan(destination.x + 60)
  expect(gapBox!.x).toBeLessThan(shifted!.x)
  for (const offset of [0, 2, -2, 0]) {
    await page.mouse.move(gapBox!.x + 20 + offset, gapBox!.y + 40)
    await expect(gap).toBeVisible()
    expect((await gap.boundingBox())!.x).toBe(gapBox!.x)
  }
  expect(await savedBoards(page)).toEqual(stored)
  await page.screenshot({ path: testInfo.outputPath("tier-list-live-insertion.png") })
  await expect(gap).toBeVisible()
  await page.keyboard.press("Escape")
  await page.mouse.up()
  await expect(gap).toHaveCount(0)
  expect(await savedBoards(page)).toEqual(stored)
  expect((await strategy.boundingBox())!.x).toBe(destination.x)
  await drag(page, "Exploration", "source", "s", "Strategy")
  await expect(row(page, "s").getByRole("button", { name: /^Assign / }).first()).toHaveAccessibleName("Assign Exploration")
  await page.getByRole("button", { name: "Undo", exact: true }).click()
  await expect(row(page, "s").getByRole("button", { name: /^Assign / })).toHaveCount(2)
  await expect(source).toBeVisible()
  await expect(page.getByRole("status").filter({ hasText: "Saved on this device" })).toBeVisible()
  expect(await savedBoards(page)).toEqual(stored)
  await source.scrollIntoViewIfNeeded()
  const outsideStart = await source.boundingBox()
  await page.mouse.move(outsideStart!.x + 20, outsideStart!.y + 40)
  await page.mouse.down()
  await page.mouse.move(outsideStart!.x + 35, outsideStart!.y + 40)
  await row(page, "a").scrollIntoViewIfNeeded()
  const a = await row(page, "a").boundingBox()
  await page.mouse.move(a!.x + 40, a!.y + 40, { steps: 10 })
  await expect(row(page, "a").locator("[data-tier-insertion-preview]")).toBeVisible()
  await page.mouse.move(1, 1, { steps: 5 })
  await expect(page.locator("[data-tier-insertion-preview]")).toHaveCount(0)
  await page.mouse.up()
  expect(await savedBoards(page)).toEqual(stored)
})

test("keyboard movement previews its destination and drops without opening actions", async ({ page }) => {
  await page.goto("/tier-lists/standard")
  const card = row(page, "source").getByRole("button", { name: "Assign Exploration", exact: true })
  await card.scrollIntoViewIfNeeded()
  await card.focus()
  await page.keyboard.press("Space")
  await expect(page.locator("[data-tier-drag-preview]")).toBeVisible()
  await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
  await page.keyboard.press("ArrowUp")
  const gap = page.locator('[data-tier-row]:not([data-tier-row="source"]) [data-tier-insertion-preview="exploration"]')
  await expect(gap).toBeVisible()
  const targetId = await gap.evaluate((element) => element.closest("[data-tier-row]")!.getAttribute("data-tier-row"))
  await page.keyboard.press("Space")
  await expect(page.locator("[data-tier-drag-preview]")).toHaveCount(0)
  await expect(row(page, targetId!).getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  await expect(row(page, targetId!).getByRole("button", { name: "Assign Exploration", exact: true })).toBeFocused()
  await expect(page.getByRole("dialog")).toHaveCount(0)
})

test("exclusive ranking, real dragging, reorder, reload and undo", async ({ page }, testInfo) => {
  await page.goto("/tier-lists/standard")
  await expect(page.getByRole("heading", { name: "Classic S / A / B / C" })).toBeVisible()
  await expect(row(page, "source").getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  await expect.poll(() => row(page, "source").locator("img").evaluateAll((images) => images.filter((image) => (image as HTMLImageElement).complete && (image as HTMLImageElement).naturalWidth > 0).length)).toBe(6)
  const controls = page.getByRole("region", { name: "S", exact: true }).locator("[data-tier-row-controls]")
  await expect(controls.getByRole("button")).toHaveCount(3)
  expect(await controls.getByRole("button").first().textContent()).toBe("")
  const controlsBox = await controls.boundingBox(), rowBox = await row(page, "s").boundingBox()
  expect(controlsBox!.x).toBeGreaterThan(rowBox!.x + rowBox!.width - 1)
  await drag(page, "Exploration", "source", "s")
  await expect(row(page, "s").getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  await assign(page, "Strategy", "S")
  await row(page, "s").getByRole("button", { name: "Assign Strategy", exact: true }).click()
  await page.getByRole("button", { name: "Move earlier", exact: true }).click()
  await page.keyboard.press("Escape")
  await expect(row(page, "s").getByRole("button", { name: /^Assign / }).first()).toHaveAccessibleName("Assign Strategy")
  await drag(page, "Strategy", "s", "s", "Exploration", true)
  await expect(row(page, "s").getByRole("button", { name: /^Assign / }).first()).toHaveAccessibleName("Assign Exploration")
  await drag(page, "Exploration", "s", "a")
  await expect(row(page, "a").getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  await expect(row(page, "s").getByRole("button", { name: "Assign Exploration", exact: true })).toHaveCount(0)
  await expect(page.getByRole("status").filter({ hasText: "Saved on this device" })).toBeVisible()
  await page.reload()
  await expect(row(page, "a").getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  await row(page, "a").getByRole("button", { name: "Assign Exploration", exact: true }).click()
  await page.getByRole("radio", { name: "B", exact: true }).click()
  await page.getByRole("button", { name: "Undo", exact: true }).click()
  await expect(row(page, "a").getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Redo", exact: true }).click()
  await expect(row(page, "b").getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath("tier-list-desktop.png"), fullPage: true })
})

async function setColor(page: Page, color: string) {
  const input = page.locator('input[type="color"]').first()
  await input.evaluate((element, value) => {
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value")!.set!.call(element, value)
    element.dispatchEvent(new Event("input", { bubbles: true }))
  }, color)
  await expect(input).toHaveValue(color)
  return input
}

test("row color swatch, template color reuse and keyboard card actions", async ({ page }, testInfo) => {
  await page.goto("/tier-lists/standard")
  await page.getByRole("button", { name: "Options for row S", exact: true }).click()
  await page.getByRole("menuitem", { name: "Edit row S", exact: true }).click()
  const picker = page.locator('input[type="color"]')
  await expect(picker).toHaveAccessibleName("Row color")
  await expect(picker.locator("..").locator("[data-color-swatch]")).toHaveCSS("background-color", "rgb(240, 128, 128)")
  await setColor(page, "#123456")
  await expect(picker.locator("..").locator("[data-color-swatch]")).toHaveCSS("background-color", "rgb(18, 52, 86)")
  await expect(picker.locator("..")).toHaveCSS("background-color", "rgb(18, 52, 86)")
  await expect(picker.locator("..")).toHaveCSS("color", "rgb(255, 255, 255)")
  // Read both rectangles in one frame; the dialog entrance animates their shared scale.
  const coverage = await picker.evaluate((input) => {
    const clickable = input.getBoundingClientRect()
    const swatch = input.parentElement!.querySelector("[data-color-swatch]")!.getBoundingClientRect()
    return { input: [clickable.width, clickable.height], swatch: [swatch.width, swatch.height] }
  })
  expect(coverage.swatch).toEqual(coverage.input)
  await expect(picker.locator("..")).toContainText("#123456")
  await picker.focus()
  await page.keyboard.press("Tab")
  await page.keyboard.press("Shift+Tab")
  await expect(picker).toBeFocused()
  await expect(picker.locator("..")).not.toHaveCSS("box-shadow", "none")
  await page.screenshot({ path: testInfo.outputPath("tier-list-color-picker.png"), fullPage: true })
  await page.getByRole("dialog").getByRole("button", { name: "Save", exact: true }).click()
  await expect(page.getByRole("region", { name: "S", exact: true }).locator("[data-tier-row-label]")).toHaveCSS("background-color", "rgb(18, 52, 86)")
  await expect(page.getByRole("status").filter({ hasText: "Saved on this device" })).toBeVisible()
  await page.reload()
  await expect(page.getByRole("region", { name: "S", exact: true }).locator("[data-tier-row-label]")).toHaveCSS("background-color", "rgb(18, 52, 86)")
  const card = row(page, "source").getByRole("button", { name: "Assign Puzzles", exact: true })
  await card.scrollIntoViewIfNeeded()
  await card.focus()
  await page.keyboard.press("Space")
  await expect(page.locator("[data-tier-drag-preview]")).toBeVisible()
  // The native keyboard sensor installs its document listener after activation.
  // Wait for the activated board to paint before the next synthetic key press.
  await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
  await page.keyboard.press("Escape")
  await expect(page.locator("[data-tier-drag-preview]")).toHaveCount(0)
  await expect(card).toBeFocused()
  await page.keyboard.press("Enter")
  await expect(page.getByRole("dialog")).toBeVisible()
  await page.keyboard.press("Escape")
  await page.getByRole("link", { name: "Remix template", exact: true }).click()
  await expect(page.locator('input[type="color"]').first().locator("..").locator("[data-color-swatch]")).toHaveCSS("background-color", "rgb(240, 128, 128)")
  await setColor(page, "#abcdef")
  await expect(page.locator('input[type="color"]').first().locator("..").locator("[data-color-swatch]")).toHaveCSS("background-color", "rgb(171, 205, 239)")
})

test("shared controls and embedded tier boards are documented in the component showcase", async ({ page }, testInfo) => {
  await page.addInitScript(() => localStorage.setItem("bm-sc3-chapter", "Primitivas"))
  await page.goto("/styles/components")
  await expect(page.locator("#color-input")).toContainText("Color picker")
  const colors = page.locator('#color-input input[type="color"]')
  await expect(colors).toHaveCount(3)
  await expect(colors.nth(2)).toBeDisabled()
  await page.getByRole("button", { name: /^Herramientas/ }).first().click()
  await page.getByRole("button", { name: /^Tier Lists/ }).click()
  await expect(page.locator("#tier-exclusive [data-tier-list]")).toBeVisible()
  await expect(page.locator("#tier-multi [data-tier-list]")).toBeVisible()
  await page.locator("#tier-exclusive").getByRole("button", { name: "Assign Exploration", exact: true }).click()
  await page.getByRole("dialog").getByRole("radio", { name: "S", exact: true }).click()
  await expect(page.locator('#tier-exclusive [data-tier-row="s"]').getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  await expect(page.locator('#tier-multi [data-tier-row="first"]').getByRole("button", { name: "Assign Exploration", exact: true })).toHaveCount(0)
  await page.locator("#tier-drag").screenshot({ path: testInfo.outputPath("shared-drag-controls.png") })
  await page.locator("#tier-exclusive").screenshot({ path: testInfo.outputPath("embedded-tier-list.png") })
  await page.screenshot({ path: testInfo.outputPath("tier-list-showcase.png"), fullPage: true })
})

test("mobile tap assignment, multi placement, source search and scoped clear", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/tier-lists/planner")
  await row(page, "source").getByRole("button", { name: "Assign Exploration", exact: true }).click()
  await page.getByRole("checkbox", { name: "Group 1", exact: true }).click()
  await page.getByRole("checkbox", { name: "Group 2", exact: true }).click()
  await page.keyboard.press("Escape")
  await expect(row(page, "first").getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  await expect(row(page, "second").getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  await expect(row(page, "source").getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  await page.getByPlaceholder("Search items…").fill("Strategy")
  await expect(row(page, "source").getByRole("button", { name: "Assign Strategy", exact: true })).toBeVisible()
  await expect(row(page, "source").getByRole("button", { name: "Assign Exploration", exact: true })).toHaveCount(0)
  await page.getByRole("button", { name: "Options for row Group 1", exact: true }).click()
  await page.getByRole("menuitem", { name: "Clear row Group 1", exact: true }).click()
  await page.getByRole("dialog").getByRole("button", { name: "Confirm", exact: true }).click()
  await expect(row(page, "first").getByRole("button", { name: "Assign Exploration", exact: true })).toHaveCount(0)
  await expect(row(page, "second").getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const touchCard = row(page, "source").getByRole("button", { name: "Assign Strategy", exact: true })
  await touchCard.scrollIntoViewIfNeeded()
  const origin = await touchCard.boundingBox()
  if (!origin) throw new Error("Missing touch card")
  const touch = await page.context().newCDPSession(page)
  try {
    await touch.send("Emulation.setTouchEmulationEnabled", { enabled: true })
    await touch.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [{ x: origin.x + 20, y: origin.y + 40 }] })
    await expect(page.locator("[data-tier-drag-preview]")).toBeVisible()
    await row(page, "first").scrollIntoViewIfNeeded()
    const target = await row(page, "first").boundingBox()
    if (!target) throw new Error("Missing touch destination")
    await touch.send("Input.dispatchTouchEvent", { type: "touchMove", touchPoints: [{ x: target.x + 40, y: target.y + 40 }] })
    await expect(row(page, "first")).toHaveAttribute("data-drop-state", "active")
    await expect(row(page, "first").locator('[data-tier-insertion-preview="strategy"]')).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath("tier-list-touch-drag.png") })
    await touch.send("Input.dispatchTouchEvent", { type: "touchEnd", touchPoints: [] })
    await expect(row(page, "first").getByRole("button", { name: "Assign Strategy", exact: true })).toBeVisible()
    await expect(row(page, "source").getByRole("button", { name: "Assign Strategy", exact: true })).toBeVisible()
    await expect(page.getByRole("dialog")).toHaveCount(0)
  } finally { await touch.detach() }
  await page.screenshot({ path: testInfo.outputPath("tier-list-mobile.png"), fullPage: true })
})

test("local template editor, image rendering, versioned JSON round trip and PNG", async ({ page, browser }, testInfo) => {
  const pixel = await sharp({ create: { width: 96, height: 24, channels: 4, background: { r: 90, g: 120, b: 160, alpha: 1 } } })
    .composite([{ input: await sharp({ create: { width: 48, height: 24, channels: 4, background: "#ff7a18" } }).png().toBuffer(), left: 48, top: 0 }]).png().toBuffer()
  await page.route("https://art.test/image.png", (route) => route.fulfill({ contentType: "image/png", headers: { "Access-Control-Allow-Origin": "*" }, body: pixel }))
  await page.goto("/tier-lists/new/edit")
  await page.getByRole("textbox", { name: "Title", exact: true }).fill("My private board")
  await page.getByRole("button", { name: "Add item", exact: true }).click()
  await page.getByRole("textbox", { name: "Item name", exact: true }).fill("Custom tile")
  await page.getByRole("textbox", { name: "Image URL", exact: true }).fill("https://art.test/image.png")
  await page.getByRole("button", { name: "Save template and open list", exact: true }).click()
  await expect(page.getByRole("heading", { name: "My private board", exact: true })).toBeVisible()
  await assign(page, "Custom tile", "S")
  await expect(row(page, "s").getByRole("button", { name: "Assign Custom tile", exact: true })).toBeVisible()
  await expect.poll(() => row(page, "s").getByAltText("Custom tile", { exact: true }).evaluate((image) => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  const privateUrl = page.url()
  await page.reload()
  await expect(row(page, "s").getByRole("button", { name: "Assign Custom tile", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Create another list", exact: true }).click()
  await expect(page).not.toHaveURL(privateUrl)
  await expect(row(page, "source").getByRole("button", { name: "Assign Custom tile", exact: true })).toBeVisible()
  await expect(row(page, "s").getByRole("button", { name: "Assign Custom tile", exact: true })).toHaveCount(0)
  await page.goto(privateUrl)
  await expect(row(page, "s").getByRole("button", { name: "Assign Custom tile", exact: true })).toBeVisible()
  const downloadPromise = page.waitForEvent("download")
  await page.getByRole("button", { name: "Export JSON", exact: true }).click()
  const download = await downloadPromise
  const path = await download.path()
  if (!path) throw new Error("Missing downloaded JSON")
  const data = await readFile(path)
  expect(JSON.parse(data.toString()).schemaVersion).toBe(1)
  await page.locator('input[type="file"]').setInputFiles({ name: "invalid.json", mimeType: "application/json", buffer: Buffer.from('{"schemaVersion":999}') })
  await expect(page.getByRole("alert").filter({ hasText: "Could not process" })).toBeVisible()
  await page.locator('input[type="file"]').setInputFiles({ name: "board.json", mimeType: "application/json", buffer: data })
  await expect(page).not.toHaveURL(privateUrl)
  await expect(row(page, "s").getByRole("button", { name: "Assign Custom tile", exact: true })).toBeVisible()
  await page.getByRole("switch", { name: "Item labels", exact: true }).focus()
  const presentation = page.locator("[data-tier-presentation]")
  const reference = await presentation.screenshot()
  const pngPromise = page.waitForEvent("download")
  await page.getByRole("button", { name: "Export PNG", exact: true }).click()
  const pngPath = await (await pngPromise).path()
  expect(pngPath).toBeTruthy()
  const png = await readFile(pngPath!)
  expect(png.subarray(1, 4).toString()).toBe("PNG")
  const referenceSize = await sharp(reference).metadata()
  const actual = await sharp(png).resize(referenceSize.width, referenceSize.height).removeAlpha().raw().toBuffer()
  const expected = await sharp(reference).removeAlpha().raw().toBuffer()
  let difference = 0
  for (let index = 0; index < actual.length; index++) difference += Math.abs(actual[index] - expected[index])
  expect(difference / actual.length).toBeLessThan(2)
  await (await pngPromise).saveAs(testInfo.outputPath("tier-list-export.png"))
  // A remotely displayed image can still forbid export. Report that clearly,
  // then allow a subsequent export once its asset becomes downloadable.
  let allowExport = false
  await page.route("https://blocked.test/image.png", (route) => {
    if (!allowExport && route.request().resourceType() === "fetch") return route.abort("accessdenied")
    return route.fulfill({ contentType: "image/png", body: pixel, headers: { "Access-Control-Allow-Origin": "*" } })
  })
  const blocked = JSON.parse(data.toString())
  blocked.items[0].image = "https://blocked.test/image.png"
  blocked.template.source.items = blocked.items
  await page.locator('input[type="file"]').setInputFiles({ name: "blocked.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(blocked)) })
  await expect(row(page, "s").getByAltText("Custom tile", { exact: true })).toHaveAttribute("src", "https://blocked.test/image.png")
  await expect.poll(() => row(page, "s").getByAltText("Custom tile", { exact: true }).evaluate((image) => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  await page.getByRole("button", { name: "Export PNG", exact: true }).click()
  await expect(page.getByRole("alert").filter({ hasText: "Could not export the image" })).toBeVisible()
  allowExport = true
  const recovered = page.waitForEvent("download")
  await page.getByRole("button", { name: "Export PNG", exact: true }).click()
  await recovered
  await expect(page.getByRole("alert").filter({ hasText: "Could not export the image" })).toHaveCount(0)
  const otherContext = await browser.newContext()
  await otherContext.addCookies([{ name: "NEXT_LOCALE", value: "en", url: "http://localhost:3000" }])
  const otherPage = await otherContext.newPage()
  await otherPage.goto(privateUrl)
  await expect(otherPage.getByRole("heading", { name: "My private board", exact: true })).toHaveCount(0)
  await expect(otherPage.getByRole("alert").filter({ hasText: "not available in this browser" })).toBeVisible()
  await otherContext.close()
})

test("PNG matches the live responsive board and shared appearance switches preserve placements", async ({ browser }, testInfo) => {
  const context = await browser.newContext({ deviceScaleFactor: 2, viewport: { width: 1280, height: 900 } })
  await context.addCookies([{ name: "NEXT_LOCALE", value: "en", url: "http://localhost:3000" }])
  const page = await context.newPage()
  try {
    await page.goto("http://localhost:3000/tier-lists/standard")
    await assign(page, "Exploration", "S")
    await assign(page, "Strategy", "A")
    await page.getByRole("switch", { name: "Item counts", exact: true }).click()
    await page.getByRole("button", { name: "Edit list heading", exact: true }).click()
    await page.getByRole("textbox", { name: "Title", exact: true }).fill("Our weekend games")
    await page.getByRole("textbox", { name: "Description", exact: true }).fill("A list for friends")
    await page.getByRole("dialog").getByRole("button", { name: "Save", exact: true }).click()
    await expect(page.getByRole("status").filter({ hasText: "Saved on this device" })).toBeVisible()
    const saved = await savedBoards(page)
    const presentation = page.locator("[data-tier-presentation]")
    const checkImage = async (name: string) => {
      await page.evaluate(() => document.fonts.ready)
      await page.locator("[data-tier-presentation] img").evaluateAll((images) => Promise.all(images.map((img) => (img as HTMLImageElement).decode())))
      await page.getByRole("switch", { name: "Item labels", exact: true }).focus()
      const reference = await presentation.screenshot({ path: testInfo.outputPath(`${name}-page.png`) })
      const promise = page.waitForEvent("download")
      await page.getByRole("button", { name: "Export PNG", exact: true }).click()
      const download = await promise
      await download.saveAs(testInfo.outputPath(`${name}-export.png`))
      const exported = await readFile((await download.path())!)
      const actual = await sharp(exported).removeAlpha().raw().toBuffer({ resolveWithObject: true })
      const expected = await sharp(reference).removeAlpha().raw().toBuffer({ resolveWithObject: true })
      expect(actual.info).toEqual(expected.info)
      let changed = 0
      for (let pixel = 0; pixel < actual.data.length; pixel += 3) {
        if ([0, 1, 2].some((channel) => Math.abs(actual.data[pixel + channel] - expected.data[pixel + channel]) > 32)) changed++
      }
      const ratio = changed / (actual.info.width * actual.info.height)
      console.log(`${name} PNG different pixels: ${ratio}`)
      expect(ratio).toBeLessThan(0.01)
    }
    await checkImage("desktop")
    for (const label of ["Title", "Item labels", "Row labels", "Item counts", "Descriptions", "Editing controls"]) {
      await page.getByRole("switch", { name: label, exact: true }).click()
    }
    await expect(presentation.getByRole("heading")).toHaveCount(0)
    await expect(presentation).not.toContainText("A classic exclusive ranking")
    await expect(presentation.locator('[title="Exploration"]')).toHaveCount(0)
    await expect(presentation.getByRole("button", { name: "Options for row S", exact: true })).toHaveCount(0)
    await expect(presentation.locator("[data-drag-grip]")).toHaveCount(0)
    await expect(presentation).not.toContainText("Drop items here")
    await expect(presentation.locator('[data-tier-row="s"]')).not.toContainText("1 item")
    await checkImage("unlabelled")
    expect(await savedBoards(page)).toEqual(saved)
    await page.setViewportSize({ width: 390, height: 844 })
    await checkImage("mobile")
    await page.getByRole("switch", { name: "Editing controls", exact: true }).click()
    await expect(presentation.getByRole("button", { name: "Options for row S", exact: true })).toBeVisible()
    await expect(row(page, "s").getByRole("button", { name: "Assign Exploration", exact: true })).toBeVisible()
  } finally { await context.close() }
})

test("Spanish row headers stay centered and list headings are editable, isolated and portable", async ({ page }, testInfo) => {
  await page.context().addCookies([{ name: "NEXT_LOCALE", value: "es", url: "http://localhost:3000" }])
  await page.goto("/tier-lists/planner")
  const presentation = page.locator("[data-tier-presentation]")
  await expect(presentation).not.toContainText("Asigna el mismo elemento")
  await expect(page.getByRole("switch", { name: "Cantidad de elementos", exact: true })).toHaveAttribute("aria-checked", "false")
  await row(page, "source").getByRole("button", { name: "Asignar Aventura", exact: true }).click()
  await page.getByRole("checkbox", { name: "Grupo 1", exact: true }).click()
  await page.keyboard.press("Escape")
  await row(page, "source").getByRole("button", { name: "Asignar Construcción", exact: true }).click()
  await page.getByRole("checkbox", { name: "Grupo 1", exact: true }).click()
  await page.keyboard.press("Escape")
  await page.getByRole("switch", { name: "Cantidad de elementos", exact: true }).click()
  const header = page.getByRole("region", { name: "Grupo 1", exact: true }).locator("[data-tier-row-header]")
  await expect(header.getByRole("heading")).toHaveCSS("font-style", "normal")
  await expect(header.getByRole("heading")).toHaveCSS("text-transform", "none")
  const aligned = await header.evaluate((node) => {
    const label = node.querySelector("h2")!.getBoundingClientRect()
    const count = node.querySelector("[data-tier-row-count]")!.getBoundingClientRect()
    const badge = node.querySelector("[data-tier-row-count] > span")!
    return { offset: Math.abs(label.x + label.width / 2 - count.x - count.width / 2), wrapping: getComputedStyle(badge).whiteSpace }
  })
  expect(aligned.offset).toBeLessThan(0.5)
  expect(aligned.wrapping).toBe("nowrap")
  await page.getByRole("button", { name: "Editar encabezado de la lista", exact: true }).click()
  await expect(page.getByRole("textbox", { name: "Descripción", exact: true })).toHaveValue("")
  await page.getByRole("textbox", { name: "Título", exact: true }).fill("Nuestros juegos favoritos")
  await page.getByRole("textbox", { name: "Descripción", exact: true }).fill("Para jugar con amigos")
  await page.getByRole("dialog").getByRole("button", { name: "Guardar", exact: true }).click()
  await expect(presentation.getByRole("heading", { name: "Nuestros juegos favoritos", exact: true })).toBeVisible()
  await expect(presentation).toContainText("Para jugar con amigos")
  await page.getByRole("button", { name: "Deshacer", exact: true }).click()
  await expect(presentation.getByRole("heading", { name: "Planificador de varias filas", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Rehacer", exact: true }).click()
  await expect(page.getByRole("status").filter({ hasText: "Guardado en este dispositivo" })).toBeVisible()
  await page.reload()
  await expect(presentation.getByRole("heading", { name: "Nuestros juegos favoritos", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Opciones de la fila Grupo 1", exact: true }).click()
  await page.getByRole("menuitem", { name: "Editar fila Grupo 1", exact: true }).click()
  await page.getByRole("textbox", { name: "Nombre de la fila", exact: true }).fill("Para jugar juntos")
  await page.getByRole("dialog").getByRole("button", { name: "Guardar", exact: true }).click()
  await page.getByRole("switch", { name: "Cantidad de elementos", exact: true }).click()
  const reference = await presentation.screenshot({ path: testInfo.outputPath("tier-list-spanish-headers.png") })
  const imagePromise = page.waitForEvent("download")
  await page.getByRole("button", { name: "Exportar PNG", exact: true }).click()
  const image = await imagePromise
  await image.saveAs(testInfo.outputPath("tier-list-spanish-export.png"))
  const metadata = await sharp(reference).metadata()
  const actual = await sharp(await readFile((await image.path())!)).resize(metadata.width, metadata.height).removeAlpha().raw().toBuffer()
  const expected = await sharp(reference).removeAlpha().raw().toBuffer()
  let difference = 0
  for (let index = 0; index < actual.length; index++) difference += Math.abs(actual[index] - expected[index])
  expect(difference / actual.length).toBeLessThan(2)
  const promise = page.waitForEvent("download")
  await page.getByRole("button", { name: "Exportar JSON", exact: true }).click()
  const data = JSON.parse((await readFile((await (await promise).path())!)).toString())
  expect(data.instance).toMatchObject({ title: "Nuestros juegos favoritos", description: "Para jugar con amigos" })
  expect(data.template.title).toBe("Planificador de varias filas")
  expect(data.instance.rows[0].label).toBe("Para jugar juntos")
  await page.getByRole("button", { name: "Crear otra lista", exact: true }).click()
  await expect(presentation.getByRole("heading", { name: "Planificador de varias filas", exact: true })).toBeVisible()
  await expect(presentation.getByRole("heading", { name: "Grupo 1", exact: true })).toBeVisible()
  await expect(presentation).not.toContainText("Para jugar con amigos")
})

test("existing game data is adapted without a copied dataset", async ({ page }) => {
  await page.route("**/events/games", (route) => route.fulfill({ json: { success: true, statusCode: 200, data: [
    { id: 42, title: "Existing game", description: "From the API", icon: "", createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  ] } }))
  await page.goto("/tier-lists/site-games")
  await assign(page, "Existing game", "S")
  await page.reload()
  await expect(row(page, "s").getByRole("button", { name: "Assign Existing game", exact: true })).toBeVisible()
})

test("Fortune’s Weave starts four lord-led routes, copies characters and exports the live board", async ({ page, request }, testInfo) => {
  // The whole board fits below the site's fixed navigation during reference capture.
  await page.setViewportSize({ width: 1280, height: 1100 })
  await page.goto("/tier-lists")
  const template = page.locator("section").filter({ has: page.getByRole("heading", { name: "Starter templates", exact: true }) })
  await expect(template.getByText("Fire Emblem: Fortune’s Weave", { exact: true })).toBeVisible()
  await page.goto("/tier-lists/fire-emblem-fortunes-weave")
  await expect(page.getByRole("heading", { name: "Fire Emblem: Fortune’s Weave", exact: true })).toBeVisible()
  const source = row(page, "source")
  await expect(source.getByRole("button", { name: /^Assign / })).toHaveCount(50)
  const urls = await source.locator("img").evaluateAll((images) => images.map((image) => new URL((image as HTMLImageElement).src).searchParams.get("url") ?? (image as HTMLImageElement).src))
  expect(new Set(urls).size).toBe(50)
  for (const url of urls) {
    expect(url).toContain("/boffmedia/img/games/fortunes-weave/portraits/")
    const response = await request.get(url)
    expect(response.ok()).toBe(true)
    expect(response.headers()["content-type"]).toContain("image/webp")
  }
  for (const lord of ["Cai", "Dietrich", "Theodora", "Leda"]) {
    const card = source.getByRole("button", { name: `Assign ${lord}`, exact: true })
    await card.scrollIntoViewIfNeeded()
    await expect(card.locator("img")).toBeVisible()
    await expect.poll(() => card.locator("img").evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true)
    await expect(card.locator("img")).toHaveAttribute("src", /pre-timeskip/)
    await expect(row(page, lord.toLowerCase()).getByRole("button", { name: `Assign ${lord}`, exact: true })).toBeVisible()
  }
  await source.getByRole("button", { name: "Assign Tialla", exact: true }).click()
  await page.getByRole("dialog").getByRole("checkbox", { name: "Cai", exact: true }).check()
  await page.getByRole("dialog").getByRole("checkbox", { name: "Dietrich", exact: true }).check()
  await page.keyboard.press("Escape")
  await expect(row(page, "cai").getByRole("button", { name: /^Assign / })).toHaveCount(2)
  await drag(page, "Tialla", "cai", "theodora")
  for (const id of ["cai", "dietrich", "theodora"]) await expect(row(page, id).getByRole("button", { name: "Assign Tialla", exact: true })).toBeVisible()
  await page.getByRole("combobox", { name: "Filter items", exact: true }).selectOption("assigned")
  await expect(source.getByRole("button", { name: /^Assign / })).toHaveCount(5)
  await page.getByRole("combobox", { name: "Filter items", exact: true }).selectOption("all")
  await page.reload()
  await expect(row(page, "cai").getByRole("button", { name: /^Assign / })).toHaveCount(2)
  await page.getByRole("switch", { name: "Editing controls", exact: true }).click()
  const presentation = page.locator("[data-tier-presentation]")
  await presentation.scrollIntoViewIfNeeded()
  await presentation.locator("img").evaluateAll(async (images) => { await Promise.all(images.map((image) => (image as HTMLImageElement).decode())) })
  const reference = await presentation.screenshot({ path: testInfo.outputPath("fortunes-weave-reference.png") })
  await page.screenshot({ path: testInfo.outputPath("fortunes-weave-page.png"), fullPage: true })
  const download = page.waitForEvent("download")
  await page.getByRole("button", { name: "Export PNG", exact: true }).click()
  const png = await download
  await png.saveAs(testInfo.outputPath("fortunes-weave-export.png"))
  const { width, height } = await sharp(reference).metadata()
  const expected = await sharp(reference).removeAlpha().raw().toBuffer()
  const actual = await sharp(await readFile((await png.path())!)).resize(width, height).removeAlpha().raw().toBuffer()
  let difference = 0
  for (let index = 0; index < actual.length; index++) difference += Math.abs(actual[index] - expected[index])
  expect(difference / actual.length).toBeLessThan(2)
  await page.getByRole("button", { name: "Create another list", exact: true }).click()
  await expect(source.getByRole("button", { name: /^Assign / })).toHaveCount(50)
  for (const id of ["cai", "dietrich", "theodora", "leda"]) await expect(row(page, id).getByRole("button", { name: /^Assign / })).toHaveCount(1)
  await page.getByRole("button", { name: "Clear all placements", exact: true }).click()
  await page.getByRole("dialog").getByRole("button", { name: "Confirm", exact: true }).click()
  for (const id of ["cai", "dietrich", "theodora", "leda"]) await expect(row(page, id).getByRole("button", { name: /^Assign / })).toHaveCount(0)
  await page.getByRole("button", { name: "Reset list", exact: true }).click()
  await page.getByRole("dialog").getByRole("button", { name: "Confirm", exact: true }).click()
  for (const id of ["cai", "dietrich", "theodora", "leda"]) await expect(row(page, id).getByRole("button", { name: /^Assign / })).toHaveCount(1)
})

test("preset editor saves reusable route defaults without changing the base preset", async ({ page }, testInfo) => {
  await page.goto("/tier-lists")
  await page.locator('a[href="/tier-lists/fire-emblem-fortunes-weave/edit"]').click()
  await expect(page.getByRole("heading", { name: "Preset editor", exact: true })).toBeVisible()
  await page.getByRole("textbox", { name: "Title", exact: true }).fill("My route preset")
  await page.getByRole("textbox", { name: "Row label", exact: true }).first().fill("Cai’s allies")
  const defaults = page.locator("[data-tier-starting-placements]")
  await expect(defaults.getByRole("heading", { name: "Cai’s allies", exact: true })).toBeVisible()
  await defaults.locator('[data-tier-row="source"]').getByRole("button", { name: "Assign Tialla", exact: true }).click()
  await page.getByRole("dialog").getByRole("checkbox", { name: "Cai’s allies", exact: true }).check()
  await page.getByRole("dialog").getByRole("checkbox", { name: "Dietrich", exact: true }).check()
  await page.keyboard.press("Escape")
  await defaults.screenshot({ path: testInfo.outputPath("route-preset-editor.png") })
  await page.getByRole("button", { name: "Save template and open list", exact: true }).click()
  await expect(page.getByRole("heading", { name: "My route preset", exact: true })).toBeVisible()
  const privateUrl = page.url()
  for (const id of ["cai", "dietrich"]) await expect(row(page, id).getByRole("button", { name: "Assign Tialla", exact: true })).toBeVisible()
  const downloadPromise = page.waitForEvent("download")
  await page.getByRole("button", { name: "Export JSON", exact: true }).click()
  const data = JSON.parse((await readFile((await (await downloadPromise).path())!)).toString())
  expect(data.template.initialPlacements).toMatchObject({ cai: ["cai", "tialla"], dietrich: ["dietrich", "tialla"] })
  await page.getByRole("button", { name: "Create another list", exact: true }).click()
  await expect(page).not.toHaveURL(privateUrl)
  for (const id of ["cai", "dietrich"]) await expect(row(page, id).getByRole("button", { name: "Assign Tialla", exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole("region", { name: "Cai’s allies", exact: true })).toBeVisible()
  await page.goto("/tier-lists/fire-emblem-fortunes-weave")
  await expect(page.getByRole("region", { name: "Cai", exact: true })).toBeVisible()
  await expect(row(page, "cai").getByRole("button", { name: "Assign Tialla", exact: true })).toHaveCount(0)
})

test("updated route presets keep old saved rankings and replace previous lord artwork", async ({ page }) => {
  await page.goto("/tier-lists/fire-emblem-fortunes-weave")
  await row(page, "source").getByRole("button", { name: "Assign Tialla", exact: true }).click()
  await page.getByRole("dialog").getByRole("checkbox", { name: "Cai", exact: true }).check()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("status").filter({ hasText: "Saved on this device" })).toBeVisible()
  const previous = await page.evaluate(() => {
    const key = "tier-list:v1:fire-emblem-fortunes-weave:default"
    const doc = JSON.parse(localStorage.getItem(key)!)
    doc.template.rows = [{ id: "s", label: "S", color: "#f08080" }, { id: "a", label: "A" }]
    doc.template.settings.placementMode = "exclusive"
    doc.template.settings.keepSourceVisible = false
    delete doc.template.initialPlacements
    doc.instance.placements = { s: [{ id: "original-cai", itemId: "cai" }] }
    doc.items = doc.items.map((item: { id: string; image: string }) => ["cai", "dietrich", "theodora", "leda"].includes(item.id) ? { ...item, image: `/boffmedia/img/games/fortunes-weave/portraits/${item.id}.webp` } : item)
    doc.template.source.items = doc.items
    const raw = JSON.stringify(doc)
    localStorage.setItem(key, raw)
    return { key, raw }
  })
  await page.reload()
  await expect(row(page, "s").getByRole("button", { name: "Assign Cai", exact: true })).toBeVisible()
  await expect(row(page, "s").getByRole("button", { name: "Assign Cai", exact: true }).locator("img")).toHaveAttribute("src", /cai-pre-timeskip/)
  await expect(page.getByText("This base preset has been updated.", { exact: false })).toBeVisible()
  await page.getByRole("button", { name: "Create another list", exact: true }).click()
  for (const id of ["cai", "dietrich", "theodora", "leda"]) await expect(row(page, id).getByRole("button", { name: /^Assign / })).toHaveCount(1)
  expect(await page.evaluate((key) => localStorage.getItem(key), previous.key)).toBe(previous.raw)
  await page.goto("/tier-lists/fire-emblem-fortunes-weave/edit")
  await expect(page.getByRole("textbox", { name: "Row label", exact: true }).first()).toHaveValue("Cai")
  await expect(page.locator("[data-tier-starting-placements]").getByRole("heading", { name: "Leda", exact: true })).toBeVisible()
  expect(await page.evaluate((key) => localStorage.getItem(key), previous.key)).toBe(previous.raw)
})
