-- Roles, administrator and app registry
--
-- GENERATED by src/seed/generate-sql.ts from seed/default.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- ═══ EDIT THESE TWO LINES ═══════════════════════════════════════════════════
--
-- bcrypt cannot be computed in SQL. Generate the hash on your own machine — the
-- password never leaves it, only the hash travels:
--
--   node -e "console.log(require('bcrypt').hashSync(process.argv[1],12))" 'your-password'
--   htpasswd -bnBC 12 "" 'your-password' | tr -d ':\n'     # if you prefer no Node
--
-- Minimum 12 characters: seed/default.ts refuses shorter ones and this file is the
-- same administrator. Leave the placeholder and NOTHING is inserted — the guard below
-- is what stops an unusable admin row being created silently.

SET @ADMIN_PASSWORD_HASH := '__PASTE_BCRYPT_HASH_HERE__';
SET @ADMIN_EMAIL         := 'admin@boffmedia.es';

-- ═══════════════════════════════════════════════════════════════════════════

-- ── Roles ──────────────────────────────────────────────────────────────────

INSERT INTO boffmedia_roles (name) VALUES ('BOFF_ADMIN')
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO boffmedia_roles (name) VALUES ('ROTOM_ADMIN')
ON DUPLICATE KEY UPDATE name = name;

-- ── SmartRotom identity ────────────────────────────────────────────────────
-- Must precede boffmedia_users: that table's uuid is an FK to this one.

INSERT INTO rotom_users (uuid, username) VALUES ('00000000-0000-0000-0000-000000000001', 'admin')
ON DUPLICATE KEY UPDATE username = username;

-- ── The administrator ──────────────────────────────────────────────────────
-- An existing row wins: re-running must never reset a password changed since.

INSERT INTO boffmedia_users (username, password, email, uuid)
SELECT 'admin', @ADMIN_PASSWORD_HASH, @ADMIN_EMAIL, '00000000-0000-0000-0000-000000000001' FROM DUAL
WHERE @ADMIN_PASSWORD_HASH LIKE '$2%'
  AND NOT EXISTS (SELECT 1 FROM boffmedia_users WHERE username = 'admin');

-- ── Role grants ────────────────────────────────────────────────────────────

INSERT INTO boffmedia_user_roles (user_id, role_id)
SELECT u.id, r.id
FROM boffmedia_users u, boffmedia_roles r
WHERE u.username = 'admin'
  AND r.name IN ('BOFF_ADMIN', 'ROTOM_ADMIN')
  AND NOT EXISTS (
    SELECT 1 FROM boffmedia_user_roles ur
    WHERE ur.user_id = u.id AND ur.role_id = r.id
  );

-- ── App registry ───────────────────────────────────────────────────────────

INSERT INTO rotom_apps (name, active) VALUES ('ChatApp', 1)
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO rotom_apps (name, active) VALUES ('StarBank', 1)
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO rotom_apps (name, active) VALUES ('Pokedex', 1)
ON DUPLICATE KEY UPDATE name = name;

-- ── Verify ─────────────────────────────────────────────────────────────────
-- admin_user must be 1. If it is 0 you left the placeholder in the SET above.

SELECT
  (SELECT COUNT(*) FROM boffmedia_users WHERE username = 'admin') AS admin_user,
  (SELECT COUNT(*) FROM boffmedia_user_roles ur
     JOIN boffmedia_users u ON u.id = ur.user_id
    WHERE u.username = 'admin')                                  AS admin_roles,
  (SELECT COUNT(*) FROM rotom_apps)                              AS apps;
