-- StarBank house accounts
--
-- GENERATED by src/seed/generate-sql.ts from starbank/house-accounts.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- Balances are never touched, only existence: this file cannot move money.

-- Teras (SYSTEM) — Where money enters and leaves the economy (AJUSTE mint/burn). Its balance is the negative of all money in circulation.
INSERT INTO rotom_starbank_accounts (name, balance, type)
SELECT 'Teras', 0, 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_starbank_accounts WHERE type = 'SYSTEM');

-- Hacienda de Teras (GOVERNMENT) — Civic money: fines and taxes credit it, payouts debit it.
INSERT INTO rotom_starbank_accounts (name, balance, type)
SELECT 'Hacienda de Teras', 0, 'GOVERNMENT' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_starbank_accounts WHERE type = 'GOVERNMENT');

-- Wigglypop Escrow (MARKET) — A buyer's money between 'paid' and 'delivered', plus the 2.5% fee the house keeps.
INSERT INTO rotom_starbank_accounts (name, balance, type)
SELECT 'Wigglypop Escrow', 0, 'MARKET' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_starbank_accounts WHERE type = 'MARKET');

-- Taxi de Teras (SERVICE) — Fares collected by the taxi service.
INSERT INTO rotom_starbank_accounts (name, balance, type)
SELECT 'Taxi de Teras', 0, 'SERVICE' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_starbank_accounts WHERE type = 'SERVICE' AND name = 'Taxi de Teras');
