-- Forum categories
--
-- GENERATED by src/seed/generate-sql.ts from seed/forum-categories.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- Re-running syncs label/icon/hue/position edits without duplicating rows.

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('anuncios', 'Anuncios', 'Novedades oficiales del equipo Boffmedia.', 'bell', 18, true, 0)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('general', 'General', 'Charla abierta de la comunidad sobre cualquier tema del ecosistema.', 'message', 28, false, 1)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('ayuda', 'Ayuda y soporte', 'Preguntas, dudas y resolución de problemas. Marca la respuesta como resuelta.', 'info', 152, false, 2)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('torneos', 'Torneos y eventos', 'Organización, resultados y debate sobre torneos y eventos.', 'trophy', 265, false, 3)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('competitivo', 'Competitivo VGC', 'Equipos, metajuego y estrategia del formato competitivo.', 'sword', 340, false, 4)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('herramientas', 'Herramientas', 'Sugerencias y reportes sobre las herramientas de la plataforma.', 'wrench', 200, false, 5)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('off-topic', 'Off-topic', 'Todo lo demás: fuera de tema y tiempo libre.', 'globe', 48, false, 6)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);
