-- Gobierno: roles + tasas rate card
--
-- GENERATED by src/seed/generate-sql.ts from seed/gobierno.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- House accounts are in 01-house-accounts.sql (the TS seed bundles them here).

-- ── Roles ──────────────────────────────────────────────────────────────────

INSERT INTO boffmedia_roles (name) VALUES ('GOBIERNO')
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO boffmedia_roles (name) VALUES ('GOB_AGENTE')
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO boffmedia_roles (name) VALUES ('GOB_INSPECTOR')
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO boffmedia_roles (name) VALUES ('GOB_ALCALDE')
ON DUPLICATE KEY UPDATE name = name;

-- ── Tasas ──────────────────────────────────────────────────────────────────

INSERT INTO rotom_gobierno_tasas (code, concept, kind, rate, amount, active)
VALUES ('TAS-PARCELA', 'Impuesto de parcela', 'parcela', '500₽/parcela', 500, 1)
ON DUPLICATE KEY UPDATE
  concept = VALUES(concept), kind = VALUES(kind),
  rate = VALUES(rate), amount = VALUES(amount);

INSERT INTO rotom_gobierno_tasas (code, concept, kind, rate, amount, active)
VALUES ('TAS-LICENCIA', 'Licencia comercial', 'comercio', '2000₽/trimestre', 2000, 1)
ON DUPLICATE KEY UPDATE
  concept = VALUES(concept), kind = VALUES(kind),
  rate = VALUES(rate), amount = VALUES(amount);

INSERT INTO rotom_gobierno_tasas (code, concept, kind, rate, amount, active)
VALUES ('TAS-PEAJE', 'Peaje de ruta', 'transporte', '50₽/tránsito', 50, 1)
ON DUPLICATE KEY UPDATE
  concept = VALUES(concept), kind = VALUES(kind),
  rate = VALUES(rate), amount = VALUES(amount);

INSERT INTO rotom_gobierno_tasas (code, concept, kind, rate, amount, active)
VALUES ('TAS-CAPTURA', 'Tasa de captura', 'subasta', '5% del botín', 0, 1)
ON DUPLICATE KEY UPDATE
  concept = VALUES(concept), kind = VALUES(kind),
  rate = VALUES(rate), amount = VALUES(amount);

INSERT INTO rotom_gobierno_tasas (code, concept, kind, rate, amount, active)
VALUES ('TAS-REGISTRO', 'Registro de propiedad', 'parcela', '1000₽/traspaso', 1000, 1)
ON DUPLICATE KEY UPDATE
  concept = VALUES(concept), kind = VALUES(kind),
  rate = VALUES(rate), amount = VALUES(amount);
