-- Mine drop table (70 rewards)
--
-- GENERATED by src/seed/generate-sql.ts from seed/mine-rewards.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- Never DELETE from this table: game history FKs to it ON DELETE CASCADE.

-- Gema prisma (Gemas) — 900, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Gema prisma', type = 'Gemas', value = 900,
  width = 2, height = 2
WHERE item_id = 'teras:gema_prisma';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema prisma', 'Gemas', 'teras:gema_prisma', 900, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_prisma');

-- Gema blanca (Gemas) — 850, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Gema blanca', type = 'Gemas', value = 850,
  width = 2, height = 2
WHERE item_id = 'teras:gema_blanca';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema blanca', 'Gemas', 'teras:gema_blanca', 850, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_blanca');

-- Gema roja (Gemas) — 800, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Gema roja', type = 'Gemas', value = 800,
  width = 2, height = 2
WHERE item_id = 'teras:gema_roja';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema roja', 'Gemas', 'teras:gema_roja', 800, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_roja');

-- Gema azul (Gemas) — 800, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Gema azul', type = 'Gemas', value = 800,
  width = 2, height = 2
WHERE item_id = 'teras:gema_azul';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema azul', 'Gemas', 'teras:gema_azul', 800, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_azul');

-- Gema verde (Gemas) — 800, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Gema verde', type = 'Gemas', value = 800,
  width = 2, height = 2
WHERE item_id = 'teras:gema_verde';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema verde', 'Gemas', 'teras:gema_verde', 800, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_verde');

-- Gema prisma pequeña (Gemas pequeñas) — 320, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Gema prisma pequeña', type = 'Gemas pequeñas', value = 320,
  width = 1, height = 1
WHERE item_id = 'teras:gema_prisma_peque';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema prisma pequeña', 'Gemas pequeñas', 'teras:gema_prisma_peque', 320, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_prisma_peque');

-- Gema blanca pequeña (Gemas pequeñas) — 300, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Gema blanca pequeña', type = 'Gemas pequeñas', value = 300,
  width = 1, height = 1
WHERE item_id = 'teras:gema_blanca_peque';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema blanca pequeña', 'Gemas pequeñas', 'teras:gema_blanca_peque', 300, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_blanca_peque');

-- Gema roja pequeña (Gemas pequeñas) — 280, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Gema roja pequeña', type = 'Gemas pequeñas', value = 280,
  width = 1, height = 1
WHERE item_id = 'teras:gema_roja_peque';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema roja pequeña', 'Gemas pequeñas', 'teras:gema_roja_peque', 280, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_roja_peque');

-- Gema azul pequeña (Gemas pequeñas) — 280, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Gema azul pequeña', type = 'Gemas pequeñas', value = 280,
  width = 1, height = 1
WHERE item_id = 'teras:gema_azul_peque';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema azul pequeña', 'Gemas pequeñas', 'teras:gema_azul_peque', 280, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_azul_peque');

-- Gema verde pequeña (Gemas pequeñas) — 280, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Gema verde pequeña', type = 'Gemas pequeñas', value = 280,
  width = 1, height = 1
WHERE item_id = 'teras:gema_verde_peque';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema verde pequeña', 'Gemas pequeñas', 'teras:gema_verde_peque', 280, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_verde_peque');

-- Piedra Teras (Piedras especiales) — 750, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Piedra Teras', type = 'Piedras especiales', value = 750,
  width = 2, height = 2
WHERE item_id = 'teras:piedra_teras';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Teras', 'Piedras especiales', 'teras:piedra_teras', 750, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:piedra_teras');

-- Piedra espíritu (Piedras especiales) — 700, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Piedra espíritu', type = 'Piedras especiales', value = 700,
  width = 2, height = 2
WHERE item_id = 'teras:piedra_espiritu';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra espíritu', 'Piedras especiales', 'teras:piedra_espiritu', 700, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:piedra_espiritu');

-- Pieza de deseo (Piezas de deseo) — 600, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Pieza de deseo', type = 'Piezas de deseo', value = 600,
  width = 2, height = 2
WHERE item_id = 'pixelmon:wishing_piece';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Pieza de deseo', 'Piezas de deseo', 'pixelmon:wishing_piece', 600, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:wishing_piece');

-- Pieza de deseo acuática (Piezas de deseo) — 600, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Pieza de deseo acuática', type = 'Piezas de deseo', value = 600,
  width = 2, height = 2
WHERE item_id = 'teras:waterdude_wishing_piece';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Pieza de deseo acuática', 'Piezas de deseo', 'teras:waterdude_wishing_piece', 600, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:waterdude_wishing_piece');

-- Fósil hélix (Fósiles) — 260, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil hélix', type = 'Fósiles', value = 260,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_helix';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil hélix', 'Fósiles', 'teras:fosil_helix', 260, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_helix');

-- Fósil domo (Fósiles) — 260, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil domo', type = 'Fósiles', value = 260,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_domo';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil domo', 'Fósiles', 'teras:fosil_domo', 260, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_domo');

-- Fósil ámbar (Fósiles) — 280, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil ámbar', type = 'Fósiles', value = 280,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_ambar';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil ámbar', 'Fósiles', 'teras:fosil_ambar', 280, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_ambar');

-- Fósil raíz (Fósiles) — 240, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil raíz', type = 'Fósiles', value = 240,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_raiz';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil raíz', 'Fósiles', 'teras:fosil_raiz', 240, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_raiz');

-- Fósil garra (Fósiles) — 240, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil garra', type = 'Fósiles', value = 240,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_garra';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil garra', 'Fósiles', 'teras:fosil_garra', 240, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_garra');

-- Fósil cráneo (Fósiles) — 250, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil cráneo', type = 'Fósiles', value = 250,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_craneo';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil cráneo', 'Fósiles', 'teras:fosil_craneo', 250, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_craneo');

-- Fósil coraza (Fósiles) — 250, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil coraza', type = 'Fósiles', value = 250,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_coraza';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil coraza', 'Fósiles', 'teras:fosil_coraza', 250, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_coraza');

-- Fósil tapa (Fósiles) — 230, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil tapa', type = 'Fósiles', value = 230,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_tapa';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil tapa', 'Fósiles', 'teras:fosil_tapa', 230, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_tapa');

-- Fósil pluma (Fósiles) — 230, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil pluma', type = 'Fósiles', value = 230,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_pluma';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil pluma', 'Fósiles', 'teras:fosil_pluma', 230, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_pluma');

-- Fósil mandíbula (Fósiles) — 270, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil mandíbula', type = 'Fósiles', value = 270,
  width = 3, height = 2
WHERE item_id = 'teras:fosil_mandibula';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil mandíbula', 'Fósiles', 'teras:fosil_mandibula', 270, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_mandibula');

-- Fósil aleta (Fósiles) — 270, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil aleta', type = 'Fósiles', value = 270,
  width = 3, height = 2
WHERE item_id = 'teras:fosil_aleta';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil aleta', 'Fósiles', 'teras:fosil_aleta', 270, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_aleta');

-- Fósil pájaro (Fósiles) — 240, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil pájaro', type = 'Fósiles', value = 240,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_pajaro';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil pájaro', 'Fósiles', 'teras:fosil_pajaro', 240, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_pajaro');

-- Fósil pez (Fósiles) — 240, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil pez', type = 'Fósiles', value = 240,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_pez';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil pez', 'Fósiles', 'teras:fosil_pez', 240, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_pez');

-- Fósil dragón (Fósiles) — 290, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil dragón', type = 'Fósiles', value = 290,
  width = 3, height = 2
WHERE item_id = 'teras:fosil_dragon';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil dragón', 'Fósiles', 'teras:fosil_dragon', 290, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_dragon');

-- Fósil dino (Fósiles) — 290, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil dino', type = 'Fósiles', value = 290,
  width = 3, height = 2
WHERE item_id = 'teras:fosil_dino';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil dino', 'Fósiles', 'teras:fosil_dino', 290, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_dino');

-- Hélix cubierto (Fósiles cubiertos) — 180, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Hélix cubierto', type = 'Fósiles cubiertos', value = 180,
  width = 2, height = 2
WHERE item_id = 'teras:covered_helix_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Hélix cubierto', 'Fósiles cubiertos', 'teras:covered_helix_fossil', 180, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_helix_fossil');

-- Domo cubierto (Fósiles cubiertos) — 180, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Domo cubierto', type = 'Fósiles cubiertos', value = 180,
  width = 2, height = 2
WHERE item_id = 'teras:covered_dome_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Domo cubierto', 'Fósiles cubiertos', 'teras:covered_dome_fossil', 180, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_dome_fossil');

-- Ámbar cubierto (Fósiles cubiertos) — 190, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Ámbar cubierto', type = 'Fósiles cubiertos', value = 190,
  width = 2, height = 2
WHERE item_id = 'teras:covered_old_amber';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Ámbar cubierto', 'Fósiles cubiertos', 'teras:covered_old_amber', 190, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_old_amber');

-- Raíz cubierta (Fósiles cubiertos) — 170, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Raíz cubierta', type = 'Fósiles cubiertos', value = 170,
  width = 2, height = 2
WHERE item_id = 'teras:covered_root_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Raíz cubierta', 'Fósiles cubiertos', 'teras:covered_root_fossil', 170, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_root_fossil');

-- Garra cubierta (Fósiles cubiertos) — 170, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Garra cubierta', type = 'Fósiles cubiertos', value = 170,
  width = 2, height = 2
WHERE item_id = 'teras:covered_claw_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Garra cubierta', 'Fósiles cubiertos', 'teras:covered_claw_fossil', 170, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_claw_fossil');

-- Cráneo cubierto (Fósiles cubiertos) — 175, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Cráneo cubierto', type = 'Fósiles cubiertos', value = 175,
  width = 2, height = 2
WHERE item_id = 'teras:covered_skull_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Cráneo cubierto', 'Fósiles cubiertos', 'teras:covered_skull_fossil', 175, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_skull_fossil');

-- Coraza cubierta (Fósiles cubiertos) — 175, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Coraza cubierta', type = 'Fósiles cubiertos', value = 175,
  width = 2, height = 2
WHERE item_id = 'teras:covered_armor_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Coraza cubierta', 'Fósiles cubiertos', 'teras:covered_armor_fossil', 175, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_armor_fossil');

-- Tapa cubierta (Fósiles cubiertos) — 160, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tapa cubierta', type = 'Fósiles cubiertos', value = 160,
  width = 2, height = 2
WHERE item_id = 'teras:covered_cover_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tapa cubierta', 'Fósiles cubiertos', 'teras:covered_cover_fossil', 160, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_cover_fossil');

-- Pluma cubierta (Fósiles cubiertos) — 160, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Pluma cubierta', type = 'Fósiles cubiertos', value = 160,
  width = 2, height = 2
WHERE item_id = 'teras:covered_plume_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Pluma cubierta', 'Fósiles cubiertos', 'teras:covered_plume_fossil', 160, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_plume_fossil');

-- Mandíbula cubierta (Fósiles cubiertos) — 185, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Mandíbula cubierta', type = 'Fósiles cubiertos', value = 185,
  width = 3, height = 2
WHERE item_id = 'teras:covered_jaw_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Mandíbula cubierta', 'Fósiles cubiertos', 'teras:covered_jaw_fossil', 185, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_jaw_fossil');

-- Aleta cubierta (Fósiles cubiertos) — 185, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Aleta cubierta', type = 'Fósiles cubiertos', value = 185,
  width = 3, height = 2
WHERE item_id = 'teras:covered_sail_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Aleta cubierta', 'Fósiles cubiertos', 'teras:covered_sail_fossil', 185, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_sail_fossil');

-- Pájaro cubierto (Fósiles cubiertos) — 170, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Pájaro cubierto', type = 'Fósiles cubiertos', value = 170,
  width = 2, height = 2
WHERE item_id = 'teras:covered_bird_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Pájaro cubierto', 'Fósiles cubiertos', 'teras:covered_bird_fossil', 170, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_bird_fossil');

-- Pez cubierto (Fósiles cubiertos) — 170, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Pez cubierto', type = 'Fósiles cubiertos', value = 170,
  width = 2, height = 2
WHERE item_id = 'teras:covered_fish_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Pez cubierto', 'Fósiles cubiertos', 'teras:covered_fish_fossil', 170, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_fish_fossil');

-- Dragón cubierto (Fósiles cubiertos) — 195, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Dragón cubierto', type = 'Fósiles cubiertos', value = 195,
  width = 3, height = 2
WHERE item_id = 'teras:covered_drake_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Dragón cubierto', 'Fósiles cubiertos', 'teras:covered_drake_fossil', 195, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_drake_fossil');

-- Dino cubierto (Fósiles cubiertos) — 195, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Dino cubierto', type = 'Fósiles cubiertos', value = 195,
  width = 3, height = 2
WHERE item_id = 'teras:covered_dino_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Dino cubierto', 'Fósiles cubiertos', 'teras:covered_dino_fossil', 195, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_dino_fossil');

-- Piedra Fuego (Piedras evolutivas) — 340, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Fuego', type = 'Piedras evolutivas', value = 340,
  width = 1, height = 1
WHERE item_id = 'pixelmon:fire_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Fuego', 'Piedras evolutivas', 'pixelmon:fire_stone', 340, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:fire_stone');

-- Piedra Agua (Piedras evolutivas) — 340, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Agua', type = 'Piedras evolutivas', value = 340,
  width = 1, height = 1
WHERE item_id = 'pixelmon:water_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Agua', 'Piedras evolutivas', 'pixelmon:water_stone', 340, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:water_stone');

-- Piedra Trueno (Piedras evolutivas) — 340, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Trueno', type = 'Piedras evolutivas', value = 340,
  width = 1, height = 1
WHERE item_id = 'pixelmon:thunder_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Trueno', 'Piedras evolutivas', 'pixelmon:thunder_stone', 340, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:thunder_stone');

-- Piedra Hoja (Piedras evolutivas) — 340, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Hoja', type = 'Piedras evolutivas', value = 340,
  width = 1, height = 1
WHERE item_id = 'pixelmon:leaf_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Hoja', 'Piedras evolutivas', 'pixelmon:leaf_stone', 340, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:leaf_stone');

-- Piedra Lunar (Piedras evolutivas) — 360, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Lunar', type = 'Piedras evolutivas', value = 360,
  width = 1, height = 1
WHERE item_id = 'pixelmon:moon_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Lunar', 'Piedras evolutivas', 'pixelmon:moon_stone', 360, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:moon_stone');

-- Piedra Solar (Piedras evolutivas) — 360, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Solar', type = 'Piedras evolutivas', value = 360,
  width = 1, height = 1
WHERE item_id = 'pixelmon:sun_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Solar', 'Piedras evolutivas', 'pixelmon:sun_stone', 360, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:sun_stone');

-- Piedra Alba (Piedras evolutivas) — 380, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Alba', type = 'Piedras evolutivas', value = 380,
  width = 1, height = 1
WHERE item_id = 'pixelmon:dawn_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Alba', 'Piedras evolutivas', 'pixelmon:dawn_stone', 380, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:dawn_stone');

-- Piedra Noche (Piedras evolutivas) — 380, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Noche', type = 'Piedras evolutivas', value = 380,
  width = 1, height = 1
WHERE item_id = 'pixelmon:dusk_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Noche', 'Piedras evolutivas', 'pixelmon:dusk_stone', 380, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:dusk_stone');

-- Piedra Día (Piedras evolutivas) — 380, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Día', type = 'Piedras evolutivas', value = 380,
  width = 1, height = 1
WHERE item_id = 'pixelmon:shiny_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Día', 'Piedras evolutivas', 'pixelmon:shiny_stone', 380, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:shiny_stone');

-- Piedra Hielo (Piedras evolutivas) — 360, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Hielo', type = 'Piedras evolutivas', value = 360,
  width = 1, height = 1
WHERE item_id = 'pixelmon:ice_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Hielo', 'Piedras evolutivas', 'pixelmon:ice_stone', 360, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:ice_stone');

-- Tabla draco (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla draco', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:draco_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla draco', 'Tablas', 'pixelmon:draco_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:draco_plate');

-- Tabla terror (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla terror', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:dread_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla terror', 'Tablas', 'pixelmon:dread_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:dread_plate');

-- Tabla terrax (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla terrax', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:earth_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla terrax', 'Tablas', 'pixelmon:earth_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:earth_plate');

-- Tabla fuerte (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla fuerte', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:fist_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla fuerte', 'Tablas', 'pixelmon:fist_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:fist_plate');

-- Tabla llama (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla llama', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:flame_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla llama', 'Tablas', 'pixelmon:flame_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:flame_plate');

-- Tabla helada (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla helada', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:icicle_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla helada', 'Tablas', 'pixelmon:icicle_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:icicle_plate');

-- Tabla bicho (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla bicho', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:insect_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla bicho', 'Tablas', 'pixelmon:insect_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:insect_plate');

-- Tabla acero (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla acero', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:iron_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla acero', 'Tablas', 'pixelmon:iron_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:iron_plate');

-- Tabla pradal (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla pradal', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:meadow_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla pradal', 'Tablas', 'pixelmon:meadow_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:meadow_plate');

-- Tabla mental (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla mental', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:mind_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla mental', 'Tablas', 'pixelmon:mind_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:mind_plate');

-- Tabla cielo (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla cielo', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:sky_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla cielo', 'Tablas', 'pixelmon:sky_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:sky_plate');

-- Tabla linfa (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla linfa', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:splash_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla linfa', 'Tablas', 'pixelmon:splash_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:splash_plate');

-- Tabla siniestra (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla siniestra', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:spooky_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla siniestra', 'Tablas', 'pixelmon:spooky_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:spooky_plate');

-- Tabla pétrea (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla pétrea', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:stone_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla pétrea', 'Tablas', 'pixelmon:stone_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:stone_plate');

-- Tabla tóxica (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla tóxica', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:toxic_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla tóxica', 'Tablas', 'pixelmon:toxic_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:toxic_plate');

-- Tabla trueno (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla trueno', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:zap_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla trueno', 'Tablas', 'pixelmon:zap_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:zap_plate');
