-- Pasaporte: active cycle + achievement weights
--
-- GENERATED by src/seed/generate-sql.ts from seed/pasaporte.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- ── The active cycle ───────────────────────────────────────────────────────
-- Guarded on "is any season active", not on the number: a cycle already running is
-- left alone rather than replaced.

INSERT INTO rotom_pasaporte_seasons (number, name, starts_at, ends_at, active)
SELECT 7, 'Ciclo de Otoño',
       DATE_SUB(NOW(), INTERVAL 90 DAY),
       DATE_ADD(NOW(), INTERVAL 90 DAY), 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_pasaporte_seasons WHERE active = 1);

-- ── Achievement weights ────────────────────────────────────────────────────
-- Only rows still at the default (10, 'bronce') are touched, so a value
-- tuned by hand is never overwritten.

UPDATE rotom_achievements SET points = 25, tier = 'plata'
WHERE category = 'Gimnasios'
  AND points = 10 AND tier = 'bronce';

UPDATE rotom_achievements SET points = 50, tier = 'oro'
WHERE category = 'Ligas'
  AND points = 10 AND tier = 'bronce';

UPDATE rotom_achievements SET points = 100, tier = 'platino'
WHERE category = 'Frente Batalla'
  AND points = 10 AND tier = 'bronce';
