-- Rooker profiles (derived)
--
-- GENERATED by src/seed/generate-sql.ts from seed/rooker.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- Run LAST — it derives one profile per existing rotom_users row.

INSERT INTO rotom_rooker_profiles (uuid, handle, display_name)
SELECT t.uuid, t.handle, t.username
FROM (
  SELECT
    s.uuid,
    s.username,
    CASE WHEN s.seq = 1 THEN s.base
         ELSE CONCAT(LEFT(s.base, 32 - CHAR_LENGTH(CAST(s.seq AS CHAR))), s.seq)
    END AS handle
  FROM (
    SELECT
      b.uuid,
      b.username,
      b.base,
      -- Offset past handles already sharing this prefix so a re-run climbs past
      -- whatever the previous run took, instead of colliding with it forever.
      ROW_NUMBER() OVER (PARTITION BY b.base ORDER BY b.uuid)
        + (SELECT COUNT(*) FROM rotom_rooker_profiles p
            WHERE p.handle = b.base OR p.handle LIKE CONCAT(b.base, '%')) AS seq
    FROM (
      SELECT
        r.uuid,
        r.username,
        -- baseHandle(): lowercase, non-[a-z0-9_] -> '_', cut to 32, pad up to 3.
        RPAD(LEFT(LOWER(REGEXP_REPLACE(r.username, '[^a-zA-Z0-9_]', '_')), 32), GREATEST(CHAR_LENGTH(LEFT(LOWER(REGEXP_REPLACE(r.username, '[^a-zA-Z0-9_]', '_')), 32)), 3), '_') AS base
      FROM rotom_users r
      WHERE NOT EXISTS (
        SELECT 1 FROM rotom_rooker_profiles p WHERE p.uuid = r.uuid
      )
    ) b
  ) s
) t
WHERE NOT EXISTS (
  SELECT 1 FROM rotom_rooker_profiles p2 WHERE p2.handle = t.handle
);

-- ── Verify ─────────────────────────────────────────────────────────────────
-- without_profile must be 0. A non-zero count means a handle collision was
-- skipped rather than suffixed — run this file again and it will resolve.

SELECT
  (SELECT COUNT(*) FROM rotom_users)                    AS users,
  (SELECT COUNT(*) FROM rotom_rooker_profiles)          AS profiles,
  (SELECT COUNT(*) FROM rotom_users r
    WHERE NOT EXISTS (SELECT 1 FROM rotom_rooker_profiles p
                       WHERE p.uuid = r.uuid))          AS without_profile;
