-- Every static seed, in order, for a one-shot bootstrap:
--   mysql --default-character-set=utf8mb4 -u … -p <db> < drizzle/seed/seed-all.sql
--
-- PASS THE CHARSET. This file carries "Ciclo de Otoño" and rates like "500₽/parcela";
-- piped into a client that falls back to latin1 they are silently mangled on the way in,
-- and you find out when the UI renders "OtoÃ±o".
--
-- GENERATED by src/seed/generate-sql.ts — do not edit by hand.
--
-- COMPLETE: no Node step is required on the server. But EDIT THE SET LINES in the
-- 00-admin section first — bcrypt cannot be computed in SQL, so the password hash
-- has to be pasted in. Leaving the placeholder inserts no administrator, by design.

-- ═══ 00-admin.sql ════════════════════════════════════════════════

-- Roles, administrator and app registry
--
-- GENERATED by src/seed/generate-sql.ts from seed/default.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- ═══ EDIT THESE TWO LINES ═══════════════════════════════════════════════════
--
-- bcrypt cannot be computed in SQL. Generate the hash on your own machine — the
-- password never leaves it, only the hash travels:
--
--   node -e "console.log(require('bcrypt').hashSync(process.argv[1],12))" 'your-password'
--   htpasswd -bnBC 12 "" 'your-password' | tr -d ':\n'     # if you prefer no Node
--
-- Minimum 12 characters: seed/default.ts refuses shorter ones and this file is the
-- same administrator. Leave the placeholder and NOTHING is inserted — the guard below
-- is what stops an unusable admin row being created silently.

SET @ADMIN_PASSWORD_HASH := '__PASTE_BCRYPT_HASH_HERE__';
SET @ADMIN_EMAIL         := 'admin@boffmedia.es';

-- ═══════════════════════════════════════════════════════════════════════════

-- ── Roles ──────────────────────────────────────────────────────────────────

INSERT INTO boffmedia_roles (name) VALUES ('BOFF_ADMIN')
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO boffmedia_roles (name) VALUES ('ROTOM_ADMIN')
ON DUPLICATE KEY UPDATE name = name;

-- ── SmartRotom identity ────────────────────────────────────────────────────
-- Must precede boffmedia_users: that table's uuid is an FK to this one.

INSERT INTO rotom_users (uuid, username) VALUES ('00000000-0000-0000-0000-000000000001', 'admin')
ON DUPLICATE KEY UPDATE username = username;

-- ── The administrator ──────────────────────────────────────────────────────
-- An existing row wins: re-running must never reset a password changed since.

INSERT INTO boffmedia_users (username, password, email, uuid)
SELECT 'admin', @ADMIN_PASSWORD_HASH, @ADMIN_EMAIL, '00000000-0000-0000-0000-000000000001' FROM DUAL
WHERE @ADMIN_PASSWORD_HASH LIKE '$2%'
  AND NOT EXISTS (SELECT 1 FROM boffmedia_users WHERE username = 'admin');

-- ── Role grants ────────────────────────────────────────────────────────────

INSERT INTO boffmedia_user_roles (user_id, role_id)
SELECT u.id, r.id
FROM boffmedia_users u, boffmedia_roles r
WHERE u.username = 'admin'
  AND r.name IN ('BOFF_ADMIN', 'ROTOM_ADMIN')
  AND NOT EXISTS (
    SELECT 1 FROM boffmedia_user_roles ur
    WHERE ur.user_id = u.id AND ur.role_id = r.id
  );

-- ── App registry ───────────────────────────────────────────────────────────

INSERT INTO rotom_apps (name, active) VALUES ('ChatApp', 1)
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO rotom_apps (name, active) VALUES ('StarBank', 1)
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO rotom_apps (name, active) VALUES ('Pokedex', 1)
ON DUPLICATE KEY UPDATE name = name;

-- ── Verify ─────────────────────────────────────────────────────────────────
-- admin_user must be 1. If it is 0 you left the placeholder in the SET above.

SELECT
  (SELECT COUNT(*) FROM boffmedia_users WHERE username = 'admin') AS admin_user,
  (SELECT COUNT(*) FROM boffmedia_user_roles ur
     JOIN boffmedia_users u ON u.id = ur.user_id
    WHERE u.username = 'admin')                                  AS admin_roles,
  (SELECT COUNT(*) FROM rotom_apps)                              AS apps;

-- ═══ 01-house-accounts.sql ═══════════════════════════════════════

-- StarBank house accounts
--
-- GENERATED by src/seed/generate-sql.ts from starbank/house-accounts.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- Balances are never touched, only existence: this file cannot move money.

-- Teras (SYSTEM) — Where money enters and leaves the economy (AJUSTE mint/burn). Its balance is the negative of all money in circulation.
INSERT INTO rotom_starbank_accounts (name, balance, type)
SELECT 'Teras', 0, 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_starbank_accounts WHERE type = 'SYSTEM');

-- Hacienda de Teras (GOVERNMENT) — Civic money: fines and taxes credit it, payouts debit it.
INSERT INTO rotom_starbank_accounts (name, balance, type)
SELECT 'Hacienda de Teras', 0, 'GOVERNMENT' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_starbank_accounts WHERE type = 'GOVERNMENT');

-- Wigglypop Escrow (MARKET) — A buyer's money between 'paid' and 'delivered', plus the 2.5% fee the house keeps.
INSERT INTO rotom_starbank_accounts (name, balance, type)
SELECT 'Wigglypop Escrow', 0, 'MARKET' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_starbank_accounts WHERE type = 'MARKET');

-- Taxi de Teras (SERVICE) — Fares collected by the taxi service.
INSERT INTO rotom_starbank_accounts (name, balance, type)
SELECT 'Taxi de Teras', 0, 'SERVICE' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_starbank_accounts WHERE type = 'SERVICE' AND name = 'Taxi de Teras');

-- ═══ 02-forum-categories.sql ═════════════════════════════════════

-- Forum categories
--
-- GENERATED by src/seed/generate-sql.ts from seed/forum-categories.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- Re-running syncs label/icon/hue/position edits without duplicating rows.

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('anuncios', 'Anuncios', 'Novedades oficiales del equipo Boffmedia.', 'bell', 18, true, 0)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('general', 'General', 'Charla abierta de la comunidad sobre cualquier tema del ecosistema.', 'message', 28, false, 1)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('ayuda', 'Ayuda y soporte', 'Preguntas, dudas y resolución de problemas. Marca la respuesta como resuelta.', 'info', 152, false, 2)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('torneos', 'Torneos y eventos', 'Organización, resultados y debate sobre torneos y eventos.', 'trophy', 265, false, 3)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('competitivo', 'Competitivo VGC', 'Equipos, metajuego y estrategia del formato competitivo.', 'sword', 340, false, 4)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('herramientas', 'Herramientas', 'Sugerencias y reportes sobre las herramientas de la plataforma.', 'wrench', 200, false, 5)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);

INSERT INTO boffmedia_forum_categories
  (slug, name, description, icon, hue, locked, position)
VALUES ('off-topic', 'Off-topic', 'Todo lo demás: fuera de tema y tiempo libre.', 'globe', 48, false, 6)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),
  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);

-- ═══ 03-gobierno.sql ═════════════════════════════════════════════

-- Gobierno: roles + tasas rate card
--
-- GENERATED by src/seed/generate-sql.ts from seed/gobierno.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- House accounts are in 01-house-accounts.sql (the TS seed bundles them here).

-- ── Roles ──────────────────────────────────────────────────────────────────

INSERT INTO boffmedia_roles (name) VALUES ('GOBIERNO')
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO boffmedia_roles (name) VALUES ('GOB_AGENTE')
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO boffmedia_roles (name) VALUES ('GOB_INSPECTOR')
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO boffmedia_roles (name) VALUES ('GOB_ALCALDE')
ON DUPLICATE KEY UPDATE name = name;

-- ── Tasas ──────────────────────────────────────────────────────────────────

INSERT INTO rotom_gobierno_tasas (code, concept, kind, rate, amount, active)
VALUES ('TAS-PARCELA', 'Impuesto de parcela', 'parcela', '500₽/parcela', 500, 1)
ON DUPLICATE KEY UPDATE
  concept = VALUES(concept), kind = VALUES(kind),
  rate = VALUES(rate), amount = VALUES(amount);

INSERT INTO rotom_gobierno_tasas (code, concept, kind, rate, amount, active)
VALUES ('TAS-LICENCIA', 'Licencia comercial', 'comercio', '2000₽/trimestre', 2000, 1)
ON DUPLICATE KEY UPDATE
  concept = VALUES(concept), kind = VALUES(kind),
  rate = VALUES(rate), amount = VALUES(amount);

INSERT INTO rotom_gobierno_tasas (code, concept, kind, rate, amount, active)
VALUES ('TAS-PEAJE', 'Peaje de ruta', 'transporte', '50₽/tránsito', 50, 1)
ON DUPLICATE KEY UPDATE
  concept = VALUES(concept), kind = VALUES(kind),
  rate = VALUES(rate), amount = VALUES(amount);

INSERT INTO rotom_gobierno_tasas (code, concept, kind, rate, amount, active)
VALUES ('TAS-CAPTURA', 'Tasa de captura', 'subasta', '5% del botín', 0, 1)
ON DUPLICATE KEY UPDATE
  concept = VALUES(concept), kind = VALUES(kind),
  rate = VALUES(rate), amount = VALUES(amount);

INSERT INTO rotom_gobierno_tasas (code, concept, kind, rate, amount, active)
VALUES ('TAS-REGISTRO', 'Registro de propiedad', 'parcela', '1000₽/traspaso', 1000, 1)
ON DUPLICATE KEY UPDATE
  concept = VALUES(concept), kind = VALUES(kind),
  rate = VALUES(rate), amount = VALUES(amount);

-- ═══ 04-mine-rewards.sql ═════════════════════════════════════════

-- Mine drop table (70 rewards)
--
-- GENERATED by src/seed/generate-sql.ts from seed/mine-rewards.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- Never DELETE from this table: game history FKs to it ON DELETE CASCADE.

-- Gema prisma (Gemas) — 900, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Gema prisma', type = 'Gemas', value = 900,
  width = 2, height = 2
WHERE item_id = 'teras:gema_prisma';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema prisma', 'Gemas', 'teras:gema_prisma', 900, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_prisma');

-- Gema blanca (Gemas) — 850, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Gema blanca', type = 'Gemas', value = 850,
  width = 2, height = 2
WHERE item_id = 'teras:gema_blanca';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema blanca', 'Gemas', 'teras:gema_blanca', 850, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_blanca');

-- Gema roja (Gemas) — 800, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Gema roja', type = 'Gemas', value = 800,
  width = 2, height = 2
WHERE item_id = 'teras:gema_roja';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema roja', 'Gemas', 'teras:gema_roja', 800, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_roja');

-- Gema azul (Gemas) — 800, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Gema azul', type = 'Gemas', value = 800,
  width = 2, height = 2
WHERE item_id = 'teras:gema_azul';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema azul', 'Gemas', 'teras:gema_azul', 800, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_azul');

-- Gema verde (Gemas) — 800, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Gema verde', type = 'Gemas', value = 800,
  width = 2, height = 2
WHERE item_id = 'teras:gema_verde';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema verde', 'Gemas', 'teras:gema_verde', 800, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_verde');

-- Gema prisma pequeña (Gemas pequeñas) — 320, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Gema prisma pequeña', type = 'Gemas pequeñas', value = 320,
  width = 1, height = 1
WHERE item_id = 'teras:gema_prisma_peque';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema prisma pequeña', 'Gemas pequeñas', 'teras:gema_prisma_peque', 320, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_prisma_peque');

-- Gema blanca pequeña (Gemas pequeñas) — 300, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Gema blanca pequeña', type = 'Gemas pequeñas', value = 300,
  width = 1, height = 1
WHERE item_id = 'teras:gema_blanca_peque';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema blanca pequeña', 'Gemas pequeñas', 'teras:gema_blanca_peque', 300, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_blanca_peque');

-- Gema roja pequeña (Gemas pequeñas) — 280, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Gema roja pequeña', type = 'Gemas pequeñas', value = 280,
  width = 1, height = 1
WHERE item_id = 'teras:gema_roja_peque';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema roja pequeña', 'Gemas pequeñas', 'teras:gema_roja_peque', 280, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_roja_peque');

-- Gema azul pequeña (Gemas pequeñas) — 280, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Gema azul pequeña', type = 'Gemas pequeñas', value = 280,
  width = 1, height = 1
WHERE item_id = 'teras:gema_azul_peque';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema azul pequeña', 'Gemas pequeñas', 'teras:gema_azul_peque', 280, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_azul_peque');

-- Gema verde pequeña (Gemas pequeñas) — 280, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Gema verde pequeña', type = 'Gemas pequeñas', value = 280,
  width = 1, height = 1
WHERE item_id = 'teras:gema_verde_peque';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Gema verde pequeña', 'Gemas pequeñas', 'teras:gema_verde_peque', 280, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:gema_verde_peque');

-- Piedra Teras (Piedras especiales) — 750, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Piedra Teras', type = 'Piedras especiales', value = 750,
  width = 2, height = 2
WHERE item_id = 'teras:piedra_teras';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Teras', 'Piedras especiales', 'teras:piedra_teras', 750, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:piedra_teras');

-- Piedra espíritu (Piedras especiales) — 700, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Piedra espíritu', type = 'Piedras especiales', value = 700,
  width = 2, height = 2
WHERE item_id = 'teras:piedra_espiritu';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra espíritu', 'Piedras especiales', 'teras:piedra_espiritu', 700, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:piedra_espiritu');

-- Pieza de deseo (Piezas de deseo) — 600, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Pieza de deseo', type = 'Piezas de deseo', value = 600,
  width = 2, height = 2
WHERE item_id = 'pixelmon:wishing_piece';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Pieza de deseo', 'Piezas de deseo', 'pixelmon:wishing_piece', 600, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:wishing_piece');

-- Pieza de deseo acuática (Piezas de deseo) — 600, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Pieza de deseo acuática', type = 'Piezas de deseo', value = 600,
  width = 2, height = 2
WHERE item_id = 'teras:waterdude_wishing_piece';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Pieza de deseo acuática', 'Piezas de deseo', 'teras:waterdude_wishing_piece', 600, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:waterdude_wishing_piece');

-- Fósil hélix (Fósiles) — 260, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil hélix', type = 'Fósiles', value = 260,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_helix';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil hélix', 'Fósiles', 'teras:fosil_helix', 260, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_helix');

-- Fósil domo (Fósiles) — 260, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil domo', type = 'Fósiles', value = 260,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_domo';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil domo', 'Fósiles', 'teras:fosil_domo', 260, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_domo');

-- Fósil ámbar (Fósiles) — 280, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil ámbar', type = 'Fósiles', value = 280,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_ambar';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil ámbar', 'Fósiles', 'teras:fosil_ambar', 280, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_ambar');

-- Fósil raíz (Fósiles) — 240, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil raíz', type = 'Fósiles', value = 240,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_raiz';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil raíz', 'Fósiles', 'teras:fosil_raiz', 240, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_raiz');

-- Fósil garra (Fósiles) — 240, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil garra', type = 'Fósiles', value = 240,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_garra';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil garra', 'Fósiles', 'teras:fosil_garra', 240, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_garra');

-- Fósil cráneo (Fósiles) — 250, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil cráneo', type = 'Fósiles', value = 250,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_craneo';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil cráneo', 'Fósiles', 'teras:fosil_craneo', 250, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_craneo');

-- Fósil coraza (Fósiles) — 250, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil coraza', type = 'Fósiles', value = 250,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_coraza';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil coraza', 'Fósiles', 'teras:fosil_coraza', 250, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_coraza');

-- Fósil tapa (Fósiles) — 230, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil tapa', type = 'Fósiles', value = 230,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_tapa';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil tapa', 'Fósiles', 'teras:fosil_tapa', 230, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_tapa');

-- Fósil pluma (Fósiles) — 230, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil pluma', type = 'Fósiles', value = 230,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_pluma';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil pluma', 'Fósiles', 'teras:fosil_pluma', 230, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_pluma');

-- Fósil mandíbula (Fósiles) — 270, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil mandíbula', type = 'Fósiles', value = 270,
  width = 3, height = 2
WHERE item_id = 'teras:fosil_mandibula';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil mandíbula', 'Fósiles', 'teras:fosil_mandibula', 270, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_mandibula');

-- Fósil aleta (Fósiles) — 270, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil aleta', type = 'Fósiles', value = 270,
  width = 3, height = 2
WHERE item_id = 'teras:fosil_aleta';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil aleta', 'Fósiles', 'teras:fosil_aleta', 270, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_aleta');

-- Fósil pájaro (Fósiles) — 240, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil pájaro', type = 'Fósiles', value = 240,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_pajaro';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil pájaro', 'Fósiles', 'teras:fosil_pajaro', 240, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_pajaro');

-- Fósil pez (Fósiles) — 240, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil pez', type = 'Fósiles', value = 240,
  width = 2, height = 2
WHERE item_id = 'teras:fosil_pez';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil pez', 'Fósiles', 'teras:fosil_pez', 240, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_pez');

-- Fósil dragón (Fósiles) — 290, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil dragón', type = 'Fósiles', value = 290,
  width = 3, height = 2
WHERE item_id = 'teras:fosil_dragon';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil dragón', 'Fósiles', 'teras:fosil_dragon', 290, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_dragon');

-- Fósil dino (Fósiles) — 290, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Fósil dino', type = 'Fósiles', value = 290,
  width = 3, height = 2
WHERE item_id = 'teras:fosil_dino';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Fósil dino', 'Fósiles', 'teras:fosil_dino', 290, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:fosil_dino');

-- Hélix cubierto (Fósiles cubiertos) — 180, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Hélix cubierto', type = 'Fósiles cubiertos', value = 180,
  width = 2, height = 2
WHERE item_id = 'teras:covered_helix_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Hélix cubierto', 'Fósiles cubiertos', 'teras:covered_helix_fossil', 180, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_helix_fossil');

-- Domo cubierto (Fósiles cubiertos) — 180, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Domo cubierto', type = 'Fósiles cubiertos', value = 180,
  width = 2, height = 2
WHERE item_id = 'teras:covered_dome_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Domo cubierto', 'Fósiles cubiertos', 'teras:covered_dome_fossil', 180, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_dome_fossil');

-- Ámbar cubierto (Fósiles cubiertos) — 190, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Ámbar cubierto', type = 'Fósiles cubiertos', value = 190,
  width = 2, height = 2
WHERE item_id = 'teras:covered_old_amber';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Ámbar cubierto', 'Fósiles cubiertos', 'teras:covered_old_amber', 190, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_old_amber');

-- Raíz cubierta (Fósiles cubiertos) — 170, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Raíz cubierta', type = 'Fósiles cubiertos', value = 170,
  width = 2, height = 2
WHERE item_id = 'teras:covered_root_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Raíz cubierta', 'Fósiles cubiertos', 'teras:covered_root_fossil', 170, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_root_fossil');

-- Garra cubierta (Fósiles cubiertos) — 170, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Garra cubierta', type = 'Fósiles cubiertos', value = 170,
  width = 2, height = 2
WHERE item_id = 'teras:covered_claw_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Garra cubierta', 'Fósiles cubiertos', 'teras:covered_claw_fossil', 170, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_claw_fossil');

-- Cráneo cubierto (Fósiles cubiertos) — 175, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Cráneo cubierto', type = 'Fósiles cubiertos', value = 175,
  width = 2, height = 2
WHERE item_id = 'teras:covered_skull_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Cráneo cubierto', 'Fósiles cubiertos', 'teras:covered_skull_fossil', 175, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_skull_fossil');

-- Coraza cubierta (Fósiles cubiertos) — 175, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Coraza cubierta', type = 'Fósiles cubiertos', value = 175,
  width = 2, height = 2
WHERE item_id = 'teras:covered_armor_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Coraza cubierta', 'Fósiles cubiertos', 'teras:covered_armor_fossil', 175, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_armor_fossil');

-- Tapa cubierta (Fósiles cubiertos) — 160, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tapa cubierta', type = 'Fósiles cubiertos', value = 160,
  width = 2, height = 2
WHERE item_id = 'teras:covered_cover_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tapa cubierta', 'Fósiles cubiertos', 'teras:covered_cover_fossil', 160, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_cover_fossil');

-- Pluma cubierta (Fósiles cubiertos) — 160, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Pluma cubierta', type = 'Fósiles cubiertos', value = 160,
  width = 2, height = 2
WHERE item_id = 'teras:covered_plume_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Pluma cubierta', 'Fósiles cubiertos', 'teras:covered_plume_fossil', 160, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_plume_fossil');

-- Mandíbula cubierta (Fósiles cubiertos) — 185, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Mandíbula cubierta', type = 'Fósiles cubiertos', value = 185,
  width = 3, height = 2
WHERE item_id = 'teras:covered_jaw_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Mandíbula cubierta', 'Fósiles cubiertos', 'teras:covered_jaw_fossil', 185, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_jaw_fossil');

-- Aleta cubierta (Fósiles cubiertos) — 185, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Aleta cubierta', type = 'Fósiles cubiertos', value = 185,
  width = 3, height = 2
WHERE item_id = 'teras:covered_sail_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Aleta cubierta', 'Fósiles cubiertos', 'teras:covered_sail_fossil', 185, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_sail_fossil');

-- Pájaro cubierto (Fósiles cubiertos) — 170, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Pájaro cubierto', type = 'Fósiles cubiertos', value = 170,
  width = 2, height = 2
WHERE item_id = 'teras:covered_bird_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Pájaro cubierto', 'Fósiles cubiertos', 'teras:covered_bird_fossil', 170, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_bird_fossil');

-- Pez cubierto (Fósiles cubiertos) — 170, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Pez cubierto', type = 'Fósiles cubiertos', value = 170,
  width = 2, height = 2
WHERE item_id = 'teras:covered_fish_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Pez cubierto', 'Fósiles cubiertos', 'teras:covered_fish_fossil', 170, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_fish_fossil');

-- Dragón cubierto (Fósiles cubiertos) — 195, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Dragón cubierto', type = 'Fósiles cubiertos', value = 195,
  width = 3, height = 2
WHERE item_id = 'teras:covered_drake_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Dragón cubierto', 'Fósiles cubiertos', 'teras:covered_drake_fossil', 195, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_drake_fossil');

-- Dino cubierto (Fósiles cubiertos) — 195, 3x2
UPDATE rotom_mine_rewards SET
  name = 'Dino cubierto', type = 'Fósiles cubiertos', value = 195,
  width = 3, height = 2
WHERE item_id = 'teras:covered_dino_fossil';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Dino cubierto', 'Fósiles cubiertos', 'teras:covered_dino_fossil', 195, 3, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'teras:covered_dino_fossil');

-- Piedra Fuego (Piedras evolutivas) — 340, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Fuego', type = 'Piedras evolutivas', value = 340,
  width = 1, height = 1
WHERE item_id = 'pixelmon:fire_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Fuego', 'Piedras evolutivas', 'pixelmon:fire_stone', 340, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:fire_stone');

-- Piedra Agua (Piedras evolutivas) — 340, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Agua', type = 'Piedras evolutivas', value = 340,
  width = 1, height = 1
WHERE item_id = 'pixelmon:water_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Agua', 'Piedras evolutivas', 'pixelmon:water_stone', 340, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:water_stone');

-- Piedra Trueno (Piedras evolutivas) — 340, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Trueno', type = 'Piedras evolutivas', value = 340,
  width = 1, height = 1
WHERE item_id = 'pixelmon:thunder_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Trueno', 'Piedras evolutivas', 'pixelmon:thunder_stone', 340, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:thunder_stone');

-- Piedra Hoja (Piedras evolutivas) — 340, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Hoja', type = 'Piedras evolutivas', value = 340,
  width = 1, height = 1
WHERE item_id = 'pixelmon:leaf_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Hoja', 'Piedras evolutivas', 'pixelmon:leaf_stone', 340, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:leaf_stone');

-- Piedra Lunar (Piedras evolutivas) — 360, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Lunar', type = 'Piedras evolutivas', value = 360,
  width = 1, height = 1
WHERE item_id = 'pixelmon:moon_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Lunar', 'Piedras evolutivas', 'pixelmon:moon_stone', 360, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:moon_stone');

-- Piedra Solar (Piedras evolutivas) — 360, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Solar', type = 'Piedras evolutivas', value = 360,
  width = 1, height = 1
WHERE item_id = 'pixelmon:sun_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Solar', 'Piedras evolutivas', 'pixelmon:sun_stone', 360, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:sun_stone');

-- Piedra Alba (Piedras evolutivas) — 380, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Alba', type = 'Piedras evolutivas', value = 380,
  width = 1, height = 1
WHERE item_id = 'pixelmon:dawn_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Alba', 'Piedras evolutivas', 'pixelmon:dawn_stone', 380, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:dawn_stone');

-- Piedra Noche (Piedras evolutivas) — 380, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Noche', type = 'Piedras evolutivas', value = 380,
  width = 1, height = 1
WHERE item_id = 'pixelmon:dusk_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Noche', 'Piedras evolutivas', 'pixelmon:dusk_stone', 380, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:dusk_stone');

-- Piedra Día (Piedras evolutivas) — 380, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Día', type = 'Piedras evolutivas', value = 380,
  width = 1, height = 1
WHERE item_id = 'pixelmon:shiny_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Día', 'Piedras evolutivas', 'pixelmon:shiny_stone', 380, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:shiny_stone');

-- Piedra Hielo (Piedras evolutivas) — 360, 1x1
UPDATE rotom_mine_rewards SET
  name = 'Piedra Hielo', type = 'Piedras evolutivas', value = 360,
  width = 1, height = 1
WHERE item_id = 'pixelmon:ice_stone';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Piedra Hielo', 'Piedras evolutivas', 'pixelmon:ice_stone', 360, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:ice_stone');

-- Tabla draco (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla draco', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:draco_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla draco', 'Tablas', 'pixelmon:draco_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:draco_plate');

-- Tabla terror (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla terror', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:dread_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla terror', 'Tablas', 'pixelmon:dread_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:dread_plate');

-- Tabla terrax (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla terrax', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:earth_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla terrax', 'Tablas', 'pixelmon:earth_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:earth_plate');

-- Tabla fuerte (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla fuerte', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:fist_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla fuerte', 'Tablas', 'pixelmon:fist_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:fist_plate');

-- Tabla llama (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla llama', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:flame_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla llama', 'Tablas', 'pixelmon:flame_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:flame_plate');

-- Tabla helada (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla helada', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:icicle_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla helada', 'Tablas', 'pixelmon:icicle_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:icicle_plate');

-- Tabla bicho (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla bicho', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:insect_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla bicho', 'Tablas', 'pixelmon:insect_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:insect_plate');

-- Tabla acero (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla acero', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:iron_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla acero', 'Tablas', 'pixelmon:iron_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:iron_plate');

-- Tabla pradal (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla pradal', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:meadow_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla pradal', 'Tablas', 'pixelmon:meadow_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:meadow_plate');

-- Tabla mental (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla mental', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:mind_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla mental', 'Tablas', 'pixelmon:mind_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:mind_plate');

-- Tabla cielo (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla cielo', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:sky_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla cielo', 'Tablas', 'pixelmon:sky_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:sky_plate');

-- Tabla linfa (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla linfa', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:splash_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla linfa', 'Tablas', 'pixelmon:splash_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:splash_plate');

-- Tabla siniestra (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla siniestra', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:spooky_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla siniestra', 'Tablas', 'pixelmon:spooky_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:spooky_plate');

-- Tabla pétrea (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla pétrea', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:stone_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla pétrea', 'Tablas', 'pixelmon:stone_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:stone_plate');

-- Tabla tóxica (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla tóxica', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:toxic_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla tóxica', 'Tablas', 'pixelmon:toxic_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:toxic_plate');

-- Tabla trueno (Tablas) — 300, 2x2
UPDATE rotom_mine_rewards SET
  name = 'Tabla trueno', type = 'Tablas', value = 300,
  width = 2, height = 2
WHERE item_id = 'pixelmon:zap_plate';
INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)
SELECT 'Tabla trueno', 'Tablas', 'pixelmon:zap_plate', 300, 2, 2 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = 'pixelmon:zap_plate');

-- ═══ 05-pasaporte.sql ════════════════════════════════════════════

-- Pasaporte: active cycle + achievement weights
--
-- GENERATED by src/seed/generate-sql.ts from seed/pasaporte.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- ── The active cycle ───────────────────────────────────────────────────────
-- Guarded on "is any season active", not on the number: a cycle already running is
-- left alone rather than replaced.

INSERT INTO rotom_pasaporte_seasons (number, name, starts_at, ends_at, active)
SELECT 7, 'Ciclo de Otoño',
       DATE_SUB(NOW(), INTERVAL 90 DAY),
       DATE_ADD(NOW(), INTERVAL 90 DAY), 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM rotom_pasaporte_seasons WHERE active = 1);

-- ── Achievement weights ────────────────────────────────────────────────────
-- Only rows still at the default (10, 'bronce') are touched, so a value
-- tuned by hand is never overwritten.

UPDATE rotom_achievements SET points = 25, tier = 'plata'
WHERE category = 'Gimnasios'
  AND points = 10 AND tier = 'bronce';

UPDATE rotom_achievements SET points = 50, tier = 'oro'
WHERE category = 'Ligas'
  AND points = 10 AND tier = 'bronce';

UPDATE rotom_achievements SET points = 100, tier = 'platino'
WHERE category = 'Frente Batalla'
  AND points = 10 AND tier = 'bronce';

-- ═══ 06-rooker.sql ═══════════════════════════════════════════════

-- Rooker profiles (derived)
--
-- GENERATED by src/seed/generate-sql.ts from seed/rooker.ts — do not edit by hand.
-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.
--
-- Idempotent: re-running changes nothing that is already correct.

-- Run LAST — it derives one profile per existing rotom_users row.

INSERT INTO rotom_rooker_profiles (uuid, handle, display_name)
SELECT t.uuid, t.handle, t.username
FROM (
  SELECT
    s.uuid,
    s.username,
    CASE WHEN s.seq = 1 THEN s.base
         ELSE CONCAT(LEFT(s.base, 32 - CHAR_LENGTH(CAST(s.seq AS CHAR))), s.seq)
    END AS handle
  FROM (
    SELECT
      b.uuid,
      b.username,
      b.base,
      -- Offset past handles already sharing this prefix so a re-run climbs past
      -- whatever the previous run took, instead of colliding with it forever.
      ROW_NUMBER() OVER (PARTITION BY b.base ORDER BY b.uuid)
        + (SELECT COUNT(*) FROM rotom_rooker_profiles p
            WHERE p.handle = b.base OR p.handle LIKE CONCAT(b.base, '%')) AS seq
    FROM (
      SELECT
        r.uuid,
        r.username,
        -- baseHandle(): lowercase, non-[a-z0-9_] -> '_', cut to 32, pad up to 3.
        RPAD(LEFT(LOWER(REGEXP_REPLACE(r.username, '[^a-zA-Z0-9_]', '_')), 32), GREATEST(CHAR_LENGTH(LEFT(LOWER(REGEXP_REPLACE(r.username, '[^a-zA-Z0-9_]', '_')), 32)), 3), '_') AS base
      FROM rotom_users r
      WHERE NOT EXISTS (
        SELECT 1 FROM rotom_rooker_profiles p WHERE p.uuid = r.uuid
      )
    ) b
  ) s
) t
WHERE NOT EXISTS (
  SELECT 1 FROM rotom_rooker_profiles p2 WHERE p2.handle = t.handle
);

-- ── Verify ─────────────────────────────────────────────────────────────────
-- without_profile must be 0. A non-zero count means a handle collision was
-- skipped rather than suffixed — run this file again and it will resolve.

SELECT
  (SELECT COUNT(*) FROM rotom_users)                    AS users,
  (SELECT COUNT(*) FROM rotom_rooker_profiles)          AS profiles,
  (SELECT COUNT(*) FROM rotom_users r
    WHERE NOT EXISTS (SELECT 1 FROM rotom_rooker_profiles p
                       WHERE p.uuid = r.uuid))          AS without_profile;
