/**
 * The view-model Wigglypop's components actually render.
 *
 * These are deliberately NOT the raw server DTOs: the API returns the
 * `@boffmedia/shared` `Wigglypop*Entity` models (regenerated by
 * `pnpm generate:shared`), and `_hooks/queries.ts` flattens them into the shapes
 * below — resolving the derived fields (rarity, ivPct, types, the seller wash) once
 * at the query boundary rather than in every card. The mapping lives in exactly one
 * place; components never touch a server entity.
 *
 * Even so, every field that is a straight PASSTHROUGH from the server sources its
 * TYPE from the matching `Wigglypop*Entity` field via indexed access
 * (`Foo["bar"]`). That is the drift anchor: if the server renames or retypes such a
 * field, THIS file stops compiling — the failure surfaces here at build time instead
 * of as a wrong value on screen (the gobierno `Oficial.rank` trap). Fields the UI
 * genuinely owns — narrowed unions, renamed keys, values derived client-side, or
 * `Date`→`string` serialisations — are marked `// [web-only]` and stay local.
 */
import type {
  WigglypopBidEntity,
  WigglypopListingEntity,
  WigglypopListingItemEntity,
  WigglypopListingMonEntity,
  WigglypopOfferEntity,
  WigglypopOrderEntity,
  WigglypopOrderLineEntity,
  WigglypopSellerEntity,
  WigglypopTradeOfferEntity,
} from "@boffmedia/shared"

export type WpFormat = "fixed" | "auction" | "offer" | "trade"
export type WpKind = "mon" | "item" | "bundle"
export type WpRarity = "comun" | "raro" | "epico" | "legendario"
export type WpListingStatus = "activo" | "pausado" | "vendido" | "cancelado"
export type WpOrderStatus =
  | "escrow"
  | "transferido"
  | "completado"
  | "cancelado"
  | "reembolsado"
export type WpDeliveryStatus = "pendiente" | "transferido" | "confirmado" | "reembolsado"

export type WpSpriteWall =
  | "classic"
  | "forest"
  | "ocean"
  | "volcano"
  | "space"
  | "meadow"
  | "dusk"
  | "cave"
  | "rainbow"
  | "sakura"

/** A Pokémon as a listing carries it: a snapshot taken when it was listed, plus
 *  the content hash that lets us prove it is still the same individual at delivery. */
export interface WpMon {
  /** The content hash from `pc/_utils/pokemonKey.ts`. A Pokémon has no server id. */
  pokemonKey: WigglypopListingMonEntity["pokemonKey"]
  dex: WigglypopListingMonEntity["dex"]
  species: WigglypopListingMonEntity["species"]
  /** [web-only] server `name` is nullable; the mapper falls back to the species. */
  name: string
  form?: string // [web-only] server string | null → optional
  palette?: string // [web-only] server string | null → optional
  level: WigglypopListingMonEntity["level"]
  nature: string // [web-only] server nullable → "—" fallback
  ability: string // [web-only] server nullable → "—" fallback
  gender: "male" | "female" | "genderless" // [web-only] narrowed from server string | null
  heldItem?: string | null
  ball?: string // [web-only] server string | null → optional
  ot?: string // [web-only] server string | null → optional
  caughtIn?: string // [web-only] server string | null → optional
  shiny: WigglypopListingMonEntity["shiny"]
  legendary: WigglypopListingMonEntity["legendary"]
  /** [web-only] not on the server snapshot — looked up on the species' form. */
  types: string[]
  ivs: number[] // [web-only] server number[] | null → [] fallback
  evs: number[] // [web-only] server number[] | null → [] fallback
  stats: number[] // [web-only] server number[] | null → [] fallback
  moves: string[] // [web-only] server (string | null)[] | null → nulls filtered
  /** [web-only] narrowed from server `rarity: string`. */
  rarity: WpRarity
  /** [web-only] derived from `ivs` at the query boundary. */
  ivPct: number
  /** The deterministic valuation (server-side `WigglypopValuationService`). */
  value: WigglypopListingMonEntity["value"]
}

export interface WpItem {
  itemId: WigglypopListingItemEntity["itemId"]
  /** [web-only] mapped from server `itemName`. */
  name: string
  /** [web-only] narrowed from server `category: string | null` (defaults to "Objetos"). */
  category: string
  qty: WigglypopListingItemEntity["qty"]
  unitPrice: WigglypopListingItemEntity["unitPrice"]
}

export interface WpSeller {
  /** [web-only] flattened from the server's nested `seller: { uuid, username }`. */
  uuid: string
  /** [web-only] flattened from the server ref; "Entrenador" when unknown. */
  username: string
  /**
   * All four DERIVED from real completed orders + reviews. Zero until there are any —
   * never fabricated. A brand-new seller genuinely has no rating.
   *
   * [web-only] NOT bound to `WigglypopSellerEntity["rating"]`: the generated model types it
   * `Record<string, any> | null` (the API entity's `@ApiProperty` was missing `type: Number` —
   * now fixed, so a `pnpm generate:shared` will make the shared type `number | null` too).
   */
  rating: number | null
  /** [web-only] a COUNT — mapped from the server's `reviewCount` (not the reviews array). */
  reviews: number
  sales: WigglypopSellerEntity["sales"]
  joinedAt?: string // [web-only] not sent by the API — reserved
}

export interface WpListing {
  id: WigglypopListingEntity["id"]
  code: WigglypopListingEntity["code"]
  /** [web-only] narrowed from server `kind: string`. */
  kind: WpKind
  /** [web-only] narrowed from server `format: string`. */
  format: WpFormat
  /** [web-only] narrowed from server `status: string`. */
  status: WpListingStatus
  title: WigglypopListingEntity["title"]
  note?: string // [web-only] server string | null → optional
  price: WigglypopListingEntity["price"]
  /** The valuation. `price - value` is what drives the "bajo mercado" chip. */
  value: WigglypopListingEntity["value"]
  /** [web-only] derived from the listing's best mon (item listings fall back to común). */
  rarity: WpRarity
  /** [web-only] enriched view of the server's `seller` ref (adds rating/sales/reviews). */
  seller: WpSeller
  escrow: WigglypopListingEntity["escrow"]
  views: WigglypopListingEntity["views"]
  watchers: WigglypopListingEntity["watchers"]
  createdAt: string // [web-only] server `Date` serialised to string
  /** A `mon` listing has one; a `bundle` has many; an `item` listing has none. */
  mons: WpMon[]
  /** An `item` listing has one; a `bundle` may have many. */
  items: WpItem[]

  // ── auction only ──────────────────────────────────────────────────────────
  currentBid?: number // [web-only] server required; optional in the VM (0 → undefined)
  bids?: number
  minIncrement?: number
  buyNow?: number | null
  endsAt?: string // [web-only] server `Date | null` serialised to string

  // ── offer only ────────────────────────────────────────────────────────────
  offers?: number
  bestOffer?: number | null

  // ── trade only ──────────────────────────────────────────────────────────────
  wants?: string[]
  tradePlus?: boolean
}

export interface WpOrderLine {
  id: WigglypopOrderLineEntity["id"]
  listingId: WigglypopOrderLineEntity["listingId"]
  /** [web-only] narrowed from server `kind: string`. */
  kind: WpKind
  /** [web-only] taken from the joined listing title. */
  title: string
  qty: WigglypopOrderLineEntity["qty"]
  unitPrice: WigglypopOrderLineEntity["unitPrice"]
  lineTotal: WigglypopOrderLineEntity["lineTotal"]
  /** [web-only] narrowed from server `deliveryStatus: string`. */
  deliveryStatus: WpDeliveryStatus
  seller: WpSeller
  mons: WpMon[]
  items: WpItem[]
}

export interface WpOrder {
  id: WigglypopOrderEntity["id"]
  code: WigglypopOrderEntity["code"]
  /** [web-only] narrowed from server `status: string`. */
  status: WpOrderStatus
  subtotal: WigglypopOrderEntity["subtotal"]
  /** The 2.5% protection fee. Charged on top of the subtotal, never deducted. */
  fee: WigglypopOrderEntity["fee"]
  total: WigglypopOrderEntity["total"]
  createdAt: string // [web-only] server `Date` serialised to string
  lines: WpOrderLine[]
}

export interface WpBid {
  id: WigglypopBidEntity["id"]
  /** [web-only] flattened from the server's nested `bidder` ref. */
  bidderUuid: string
  bidderName: string // [web-only] flattened from the server's nested `bidder` ref
  amount: WigglypopBidEntity["amount"]
  createdAt: string // [web-only] server `Date` serialised to string
}

export interface WpOffer {
  id: WigglypopOfferEntity["id"]
  listingId: WigglypopOfferEntity["listingId"]
  /** [web-only] taken from the joined listing title. */
  listingTitle: string
  /** [web-only] flattened from the server's nested `buyer` ref. */
  buyerUuid: string
  buyerName: string // [web-only] flattened from the server's nested `buyer` ref
  amount: WigglypopOfferEntity["amount"]
  qty: WigglypopOfferEntity["qty"]
  /** [web-only] narrowed from server `status: string`. */
  status: "pendiente" | "aceptada" | "rechazada" | "retirada" | "caducada"
  createdAt: string // [web-only] server `Date` serialised to string
}

export interface WpTradeOffer {
  id: WigglypopTradeOfferEntity["id"]
  listingId: WigglypopTradeOfferEntity["listingId"]
  /** [web-only] taken from the joined listing title. */
  listingTitle: string
  /** [web-only] flattened from the server's nested `proposer` ref. */
  proposerUuid: string
  proposerName: string // [web-only] flattened from the server's nested `proposer` ref
  /** [web-only] the server's `offeredSnapshot` (typed `unknown`) mapped through `toMon`. */
  offered: WpMon
  /** [web-only] narrowed from server `status: string`. */
  status: "pendiente" | "aceptada" | "rechazada" | "retirada"
  createdAt: string // [web-only] server `Date` serialised to string
}

/** A line in the local cart. The cart is client-only until checkout POSTs it. */
export interface WpCartLine {
  key: string
  listing: WpListing
  qty: number
}
