/**
 * The view-model Wigglypop's components actually render.
 *
 * These are deliberately NOT the server DTOs. The API returns `@boffmedia/shared`
 * models (regenerated by `pnpm generate:shared`); this file is the shape the UI
 * wants — flattened, with the derived fields (rarity, ivPct, the wash) already
 * resolved once at the query boundary in `_hooks/queries.ts` rather than
 * recomputed in every card. Map server → these in one place, never in a component.
 */

export type WpFormat = "fixed" | "auction" | "offer" | "trade"
export type WpKind = "mon" | "item" | "bundle"
export type WpRarity = "comun" | "raro" | "epico" | "legendario"
export type WpListingStatus = "activo" | "pausado" | "vendido" | "cancelado"
export type WpOrderStatus =
  | "escrow"
  | "transferido"
  | "completado"
  | "cancelado"
  | "reembolsado"
export type WpDeliveryStatus = "pendiente" | "transferido" | "confirmado" | "reembolsado"

export type WpSpriteWall =
  | "classic"
  | "forest"
  | "ocean"
  | "volcano"
  | "space"
  | "meadow"
  | "dusk"
  | "cave"
  | "rainbow"
  | "sakura"

/** A Pokémon as a listing carries it: a snapshot taken when it was listed, plus
 *  the content hash that lets us prove it is still the same individual at delivery. */
export interface WpMon {
  /** The content hash from `pc/_utils/pokemonKey.ts`. A Pokémon has no server id. */
  pokemonKey: string
  dex: number
  species: string
  name: string
  form?: string
  palette?: string
  level: number
  nature: string
  ability: string
  gender: "male" | "female" | "genderless"
  heldItem?: string | null
  ball?: string
  ot?: string
  caughtIn?: string
  shiny: boolean
  legendary: boolean
  types: string[]
  ivs: number[]
  evs: number[]
  stats: number[]
  moves: string[]
  /** Derived once at the query boundary — see the file header. */
  rarity: WpRarity
  ivPct: number
  /** The deterministic valuation (server-side `WigglypopValuationService`). */
  value: number
}

export interface WpItem {
  itemId: string
  name: string
  category: string
  qty: number
  unitPrice: number
}

export interface WpSeller {
  uuid: string
  username: string
  /** All four DERIVED from real completed orders + reviews. Zero until there
   *  are any — never fabricated. A brand-new seller genuinely has no rating. */
  rating: number | null
  reviews: number
  sales: number
  joinedAt?: string
}

export interface WpListing {
  id: number
  code: string
  kind: WpKind
  format: WpFormat
  status: WpListingStatus
  title: string
  note?: string
  price: number
  /** The valuation. `price - value` is what drives the "bajo mercado" chip. */
  value: number
  rarity: WpRarity
  seller: WpSeller
  escrow: boolean
  views: number
  watchers: number
  createdAt: string
  /** A `mon` listing has one; a `bundle` has many; an `item` listing has none. */
  mons: WpMon[]
  /** An `item` listing has one; a `bundle` may have many. */
  items: WpItem[]

  // ── auction only ──────────────────────────────────────────────────────────
  currentBid?: number
  bids?: number
  minIncrement?: number
  buyNow?: number | null
  endsAt?: string

  // ── offer only ────────────────────────────────────────────────────────────
  offers?: number
  bestOffer?: number | null

  // ── trade only ────────────────────────────────────────────────────────────
  wants?: string[]
  tradePlus?: boolean
}

export interface WpOrderLine {
  id: number
  listingId: number
  kind: WpKind
  title: string
  qty: number
  unitPrice: number
  lineTotal: number
  deliveryStatus: WpDeliveryStatus
  seller: WpSeller
  mons: WpMon[]
  items: WpItem[]
}

export interface WpOrder {
  id: number
  code: string
  status: WpOrderStatus
  subtotal: number
  /** The 2.5% protection fee. Charged on top of the subtotal, never deducted. */
  fee: number
  total: number
  createdAt: string
  lines: WpOrderLine[]
}

export interface WpBid {
  id: number
  bidderUuid: string
  bidderName: string
  amount: number
  createdAt: string
}

export interface WpOffer {
  id: number
  listingId: number
  listingTitle: string
  buyerUuid: string
  buyerName: string
  amount: number
  qty: number
  status: "pendiente" | "aceptada" | "rechazada" | "retirada" | "caducada"
  createdAt: string
}

export interface WpTradeOffer {
  id: number
  listingId: number
  listingTitle: string
  proposerUuid: string
  proposerName: string
  offered: WpMon
  status: "pendiente" | "aceptada" | "rechazada" | "retirada"
  createdAt: string
}

/** A line in the local cart. The cart is client-only until checkout POSTs it. */
export interface WpCartLine {
  key: string
  listing: WpListing
  qty: number
}
