const GL_BASE = `${process.env.GITLAB_URL}/api/v4`
const GL_HEADERS = {
  'PRIVATE-TOKEN': process.env.GITLAB_TOKEN!,
  'Content-Type': 'application/json'
}
// URL-encode so both numeric IDs and "namespace/project" slugs work
const PROJECT_ID = encodeURIComponent(process.env.GITLAB_PROJECT_ID!)

async function glGet(apiPath: string) {
  const r = await fetch(`${GL_BASE}/${apiPath}`, { headers: GL_HEADERS })
  if (!r.ok) throw new Error(`GitLab GET ${apiPath} failed: ${r.status}`)
  return r.json()
}

async function glPost(apiPath: string, body: object) {
  const r = await fetch(`${GL_BASE}/${apiPath}`, {
    method: 'POST',
    headers: GL_HEADERS,
    body: JSON.stringify(body)
  })
  if (!r.ok) throw new Error(`GitLab POST ${apiPath} failed: ${r.status}`)
  return r.json()
}

// E6: create a merge request after a successful run
export async function createGitLabMR(input: {
  sourceBranch: string
  title: string
  taskSpec: string
  verificationSummary: string
  bookstackPageUrl?: string
  tracePath?: string
  runId: string
}): Promise<{ mrId: number; mrUrl: string }> {
  const description = buildMRDescription(input)

  const mr = await glPost(`projects/${PROJECT_ID}/merge_requests`, {
    source_branch: input.sourceBranch,
    target_branch: process.env.GITLAB_DEFAULT_BRANCH ?? 'main',
    title: input.title,
    description,
    labels: ['agent-generated'],
    remove_source_branch: false
  })

  return { mrId: mr.iid, mrUrl: mr.web_url }
}

function buildMRDescription(input: Parameters<typeof createGitLabMR>[0]): string {
  return `## Summary
${input.taskSpec}

## Verification
${input.verificationSummary}

${input.tracePath ? `## Visual review\n\`\`\`\nnpx playwright show-trace ${input.tracePath}\n\`\`\`\n` : ''}${input.bookstackPageUrl ? `## Spec\n[BookStack task page](${input.bookstackPageUrl})\n` : ''}
---
*Generated by harness agent · Run ID: \`${input.runId}\`*`
}

// E7: create an issue when a run fails after max retries
export async function createGitLabIssue(input: {
  title: string
  failureSummary: string
  failures: string[]
  runId: string
  bookstackPageUrl?: string
}): Promise<{ issueId: number; issueUrl: string }> {
  const description = `## What the agent tried
${input.title}

## Why it failed
${input.failureSummary}

## Failure details
${input.failures.map(f => `- ${f}`).join('\n')}

${input.bookstackPageUrl ? `## Spec\n[BookStack task page](${input.bookstackPageUrl})\n` : ''}
---
*Created by harness agent · Run ID: \`${input.runId}\` · Needs human review*`

  const issue = await glPost(`projects/${PROJECT_ID}/issues`, {
    title: `[Agent failed] ${input.title}`,
    description,
    labels: ['agent-failed', 'needs-review']
  })

  return { issueId: issue.iid, issueUrl: issue.web_url }
}

// E8: poll CI pipeline status for a branch
export async function getGitLabPipelineStatus(input: {
  branch: string
}): Promise<{
  status: 'running' | 'success' | 'failed' | 'canceled' | 'pending' | 'none'
  pipelineUrl?: string
  failedJobs: string[]
}> {
  const pipelines = await glGet(
    `projects/${PROJECT_ID}/pipelines?ref=${encodeURIComponent(input.branch)}&per_page=1`
  )

  if (!pipelines.length) return { status: 'none', failedJobs: [] }

  const pipeline = pipelines[0]
  const jobs = await glGet(`projects/${PROJECT_ID}/pipelines/${pipeline.id}/jobs`)
  const failedJobs = (jobs as Array<{ status: string; name: string }>)
    .filter(j => j.status === 'failed')
    .map(j => j.name)

  return {
    status: pipeline.status,
    pipelineUrl: pipeline.web_url,
    failedJobs
  }
}

// E8: fetch a GitLab issue and return it as task input
export async function fetchGitLabIssue(input: {
  issueId: number
}): Promise<{ title: string; content: string; labels: string[] }> {
  const issue = await glGet(`projects/${PROJECT_ID}/issues/${input.issueId}`)
  return {
    title: issue.title,
    content: issue.description ?? '',
    labels: issue.labels
  }
}
