import { searchBookStack, writeBookStackPage } from './bookstack.js'

interface OpenAPISpec {
  paths: Record<string, Record<string, OpenAPIOperation>>
  components?: {
    schemas?: Record<string, unknown>
  }
}

interface OpenAPIOperation {
  tags?: string[]
  summary?: string
  description?: string
  parameters?: Array<{
    name: string
    in: string
    required?: boolean
    description?: string
    schema?: { type?: string }
  }>
  requestBody?: unknown
  responses?: Record<string, { description?: string }>
}

// E13: fetch the NestJS OpenAPI spec and sync affected modules to BookStack
export async function syncOpenApiDocs(input: {
  runId: string
  affectedModules: string[]
  bookId: number
  project: 'boffmedia' | 'smartrotom'
}): Promise<{ pagesUpdated: string[]; pagesCreated: string[] }> {
  const specUrl = `${process.env.API_BASE_URL}/api-json`
  const r = await fetch(specUrl)
  if (!r.ok) throw new Error(`Failed to fetch OpenAPI spec: ${r.status}`)
  const spec = (await r.json()) as OpenAPISpec

  const pagesUpdated: string[] = []
  const pagesCreated: string[] = []

  for (const module of input.affectedModules) {
    const paths = Object.entries(spec.paths).filter(([, ops]) =>
      Object.values(ops).some(
        op => op.tags?.some(t => t.toLowerCase() === module.toLowerCase())
      )
    )

    if (!paths.length) continue

    const content = buildApiRefMarkdown(module, paths, spec.components)

    const existing = await searchBookStack({
      query: `${module} API reference`,
      tags: [input.project, 'api-reference'],
      limit: 1
    })

    if (existing.length) {
      await writeBookStackPage({
        bookId: input.bookId,
        pageId: existing[0].pageId,
        title: `${module} — API reference`,
        content,
        tags: [input.project, 'api-reference', 'agent:generated']
      })
      pagesUpdated.push(module)
    } else {
      await writeBookStackPage({
        bookId: input.bookId,
        title: `${module} — API reference`,
        content,
        tags: [input.project, 'api-reference', 'agent:generated']
      })
      pagesCreated.push(module)
    }
  }

  return { pagesUpdated, pagesCreated }
}

function buildApiRefMarkdown(
  module: string,
  paths: [string, Record<string, OpenAPIOperation>][],
  components: OpenAPISpec['components']
): string {
  const lines: string[] = [
    `# ${module} API reference\n`,
    `> Auto-generated by harness agent. Do not edit manually.\n`
  ]

  for (const [routePath, ops] of paths) {
    for (const [method, op] of Object.entries(ops)) {
      lines.push(`## \`${method.toUpperCase()} ${routePath}\``)
      if (op.summary) lines.push(`\n${op.summary}`)
      if (op.description) lines.push(`\n${op.description}`)

      if (op.parameters?.length) {
        lines.push('\n**Parameters**\n')
        lines.push('| Name | In | Type | Required | Description |')
        lines.push('|---|---|---|---|---|')
        for (const p of op.parameters) {
          lines.push(
            `| \`${p.name}\` | ${p.in} | ${p.schema?.type ?? '—'} | ${p.required ? 'Yes' : 'No'} | ${p.description ?? '—'} |`
          )
        }
      }

      if (op.requestBody) {
        lines.push('\n**Request body**\n```json')
        lines.push(JSON.stringify(resolveSchema(op.requestBody, components), null, 2))
        lines.push('```')
      }

      lines.push('\n**Responses**\n')
      for (const [code, res] of Object.entries(op.responses ?? {})) {
        lines.push(`- \`${code}\` — ${res.description ?? ''}`)
      }

      lines.push('')
    }
  }

  return lines.join('\n')
}

function resolveSchema(node: unknown, components: OpenAPISpec['components']): unknown {
  if (!node || typeof node !== 'object') return node
  const obj = node as Record<string, unknown>

  if (obj.$ref && typeof obj.$ref === 'string') {
    const refPath = obj.$ref.replace('#/components/schemas/', '')
    return resolveSchema(components?.schemas?.[refPath], components)
  }

  const resolved: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(obj)) {
    resolved[key] = resolveSchema(value, components)
  }
  return resolved
}
