export enum TransactionType {
  TRANSFERENCIA = 'TRANSFERENCIA',
  COMPRA = 'COMPRA',
  VENTA = 'VENTA',
  PREMIO = 'PREMIO',
  DERROTA_ENTRENADOR = 'DERROTA_ENTRENADOR',
  DEPOSITO = 'DEPOSITO',
  RETIRO = 'RETIRO',
}
