export const questDungeons = [
    { id: 1, value: "Beach Cave" },
    { id: 3, value: "Drenched Bluff" },
    { id: 4, value: "Mt. Bristle" },
    { id: 6, value: "Waterfall Cave" },
    { id: 7, value: "Apple Woods" },
    { id: 8, value: "Craggy Coast" },
    { id: 10, value: "Mt. Horn" },
    { id: 12, value: "Foggy Forest" },
    { id: 14, value: "Steam Cave" },
    { id: 17, value: "Amp Plains" },
    { id: 20, value: "Northern Desert" },
    { id: 21, value: "Quicksand Cave" },
    { id: 24, value: "Crystal Cave" },
    { id: 25, value: "Crystal Crossing" },
    { id: 34, value: "Treeshroud Forest" },
    { id: 35, value: "Brine Cave" },
    { id: 44, value: "Mystifying Forest" },
    { id: 46, value: "Blizzard Island" },
    { id: 47, value: "Crevice Cave" },
    { id: 50, value: "Surrounded Sea" },
    { id: 51, value: "Miracle Sea" },
    { id: 62, value: "Mt. Travail" },
    { id: 64, value: "Spacial Rift" },
    { id: 67, value: "Dark Crater" },
    { id: 70, value: "Concealed Ruins" },
    { id: 72, value: "Marine Resort" },
    { id: 73, value: "Bottomless Sea" },
    { id: 75, value: "Shimmer Desert" },
    { id: 77, value: "Mt. Avalanche" },
    { id: 79, value: "Giant Volcano" },
    { id: 81, value: "World Abyss" },
    { id: 83, value: "Sky Stairway" },
    { id: 85, value: "Mystery Jungle" },
    { id: 87, value: "Serenity River" },
    { id: 88, value: "Landslide Cave" },
    { id: 89, value: "Lush Prairie" },
    { id: 90, value: "Tiny Meadow" },
    { id: 91, value: "Labyrinth Cave" },
    { id: 92, value: "Oran Forest" },
    { id: 93, value: "Lake Afar" },
    { id: 94, value: "Happy Outlook" },
    { id: 95, value: "Mt. Mistral" },
    { id: 96, value: "Shimmer Hill" },
    { id: 97, value: "Lost Wilderness" },
    { id: 98, value: "Midnight Forest" },
    { id: 99, value: "Zero Isle North" },
    { id: 100, value: "Zero Isle East" },
    { id: 101, value: "Zero Isle West" },
    { id: 102, value: "Zero Isle South" },
    { id: 103, value: "Zero Isle Center" },
    { id: 107, value: "Oblivion Forest" },
    { id: 108, value: "Treacherous Waters" },
    { id: 109, value: "Southeastern Islands" },
    { id: 110, value: "Inferno Cave" },
] as { id: number, value: string }[];