export const questItems = [
    { key: 0, value: "None" },
    { key: 1, value: "Stick" },
    { key: 2, value: "Iron Thorn" },
    { key: 3, value: "Silver Spike" },
    { key: 4, value: "Gold Fang" },
    { key: 5, value: "Cacnea Spike" },
    { key: 6, value: "Corsola Twig" },
    { key: 7, value: "Gravelerock" },
    { key: 8, value: "Geo Pebble" },
    { key: 9, value: "Gold Thorn" },
    { key: 10, value: "Rare Fossil" },
    { key: 13, value: "No-Slip Cap" },
    { key: 14, value: "Y-Ray Specs" },
    { key: 15, value: "Gaggle Specs" },
    { key: 16, value: "Mobile Scarf" },
    { key: 17, value: "Heal Ribbon" },
    { key: 18, value: "Twist Band" },
    { key: 19, value: "Scope Lens" },
    { key: 20, value: "Patsy Band" },
    { key: 21, value: "No-Stick Cap" },
    { key: 22, value: "Pierce Band" },
    { key: 23, value: "Joy Ribbon" },
    { key: 24, value: "X-Ray Specs" },
    { key: 25, value: "Persim Band" },
    { key: 26, value: "Power Band" },
    { key: 27, value: "Pecha Scarf" },
    { key: 28, value: "Insomniscope" },
    { key: 29, value: "Warp Scarf" },
    { key: 30, value: "Tight Belt" },
    { key: 31, value: "Sneak Scarf" },
    { key: 32, value: "Gold Ribbon" },
    { key: 33, value: "Goggle Specs" },
    { key: 34, value: "Diet Ribbon" },
    { key: 35, value: "Trap Scarf" },
    { key: 36, value: "Racket Band" },
    { key: 37, value: "Def. Scarf" },
    { key: 38, value: "Stamina Band" },
    { key: 39, value: "Plain Ribbon" },
    { key: 40, value: "Special Band" },
    { key: 41, value: "Zinc Band" },
    { key: 42, value: "Detect Band" },
    { key: 43, value: "Space Globe" },
    { key: 44, value: "Dodge Scarf" },
    { key: 45, value: "Bounce Band" },
    { key: 46, value: "Curve Band" },
    { key: 47, value: "Whiff Specs" },
    { key: 48, value: "No-Aim Scope" },
    { key: 49, value: "Lockon Specs" },
    { key: 50, value: "Munch Belt" },
    { key: 51, value: "Pass Scarf" },
    { key: 52, value: "Weather Band" },
    { key: 53, value: "Friend Bow" },
    { key: 54, value: "Beauty Scarf" },
    { key: 55, value: "Sun Ribbon" },
    { key: 56, value: "Lunar Ribbon" },
    { key: 57, value: "Golden Mask" },
    { key: 58, value: "Amber Tear" },
    { key: 59, value: "Icy Flute" },
    { key: 60, value: "Fiery Drum" },
    { key: 61, value: "Terra Cymbal" },
    { key: 62, value: "Aqua-Monica" },
    { key: 63, value: "Rock Horn" },
    { key: 64, value: "Grass Cornet" },
    { key: 65, value: "Sky Melodica" },
    { key: 66, value: "Miracle Chest" },
    { key: 67, value: "Wonder Chest" },
    { key: 68, value: "IQ Booster" },
    { key: 69, value: "Heal Seed" },
    { key: 70, value: "Oran Berry" },
    { key: 71, value: "Sitrus Berry" },
    { key: 72, value: "Eyedrop Seed" },
    { key: 73, value: "Reviver Seed" },
    { key: 74, value: "Blinker Seed" },
    { key: 75, value: "Doom Seed" },
    { key: 76, value: "X-Eye Seed" },
    { key: 77, value: "Life Seed" },
    { key: 78, value: "Rawst Berry" },
    { key: 79, value: "Hunger Seed" },
    { key: 80, value: "Quick Seed" },
    { key: 81, value: "Pecha Berry" },
    { key: 82, value: "Cheri Berry" },
    { key: 83, value: "Totter Seed" },
    { key: 84, value: "Sleep Seed" },
    { key: 85, value: "Plain Seed" },
    { key: 86, value: "Warp Seed" },
    { key: 87, value: "Blast Seed" },
    { key: 88, value: "Ginseng" },
    { key: 89, value: "Joy Seed" },
    { key: 90, value: "Chesto Berry" },
    { key: 91, value: "Stun Seed" },
    { key: 92, value: "Gabite Scale" },
    { key: 93, value: "Golden Seed" },
    { key: 94, value: "Vile Seed" },
    { key: 95, value: "Pure Seed" },
    { key: 96, value: "Violent Seed" },
    { key: 97, value: "Vanish Seed" },
    { key: 99, value: "Max Elixir" },
    { key: 100, value: "Protein" },
    { key: 101, value: "Calcium" },
    { key: 102, value: "Iron" },
    { key: 103, value: "Nectar" },
    { key: 104, value: "Dropeye Seed" },
    { key: 105, value: "Reviser Seed" },
    { key: 106, value: "Slip Seed" },
    { key: 107, value: "Via Seed" },
    { key: 108, value: "Zinc" },
    { key: 109, value: "Apple" },
    { key: 110, value: "Big Apple" },
    { key: 111, value: "Grimy Food" },
    { key: 112, value: "Huge Apple" },
    { key: 115, value: "Golden Apple" },
    { key: 116, value: "Mix Elixir" },
    { key: 117, value: "Oren Berry" },
    { key: 118, value: "Dough Seed" },
    { key: 119, value: "White Gummi" },
    { key: 120, value: "Red Gummi" },
    { key: 121, value: "Blue Gummi" },
    { key: 122, value: "Grass Gummi" },
    { key: 123, value: "Yellow Gummi" },
    { key: 124, value: "Clear Gummi" },
    { key: 125, value: "Orange Gummi" },
    { key: 126, value: "Pink Gummi" },
    { key: 127, value: "Brown Gummi" },
    { key: 128, value: "Sky Gummi" },
    { key: 129, value: "Gold Gummi" },
    { key: 130, value: "Green Gummi" },
    { key: 131, value: "Gray Gummi" },
    { key: 132, value: "Purple Gummi" },
    { key: 133, value: "Royal Gummi" },
    { key: 134, value: "Black Gummi" },
    { key: 135, value: "Silver Gummi" },
    { key: 136, value: "Wonder Gummi" },
    { key: 137, value: "Gravelyrock" },
    { key: 139, value: "Upgrade" },
    { key: 140, value: "King's Rock" },
    { key: 141, value: "Thunderstone" },
    { key: 142, value: "Deepseascale" },
    { key: 143, value: "Deepseatooth" },
    { key: 144, value: "Sun Stone" },
    { key: 145, value: "Moon Stone" },
    { key: 146, value: "Fire Stone" },
    { key: 147, value: "Water Stone" },
    { key: 148, value: "Metal Coat" },
    { key: 149, value: "Leaf Stone" },
    { key: 150, value: "Dragon Scale" },
    { key: 151, value: "Link Cable" },
    { key: 152, value: "Dubious Disc" },
    { key: 153, value: "Protector" },
    { key: 154, value: "Reaper Cloth" },
    { key: 155, value: "Razor Fang" },
    { key: 156, value: "Razor Claw" },
    { key: 157, value: "Electirizer" },
    { key: 158, value: "Magmarizer" },
    { key: 159, value: "Oval Stone" },
    { key: 160, value: "Dawn Stone" },
    { key: 161, value: "Shiny Stone" },
    { key: 162, value: "Dusk Stone" },
    { key: 163, value: "Coronet Rock" },
    { key: 164, value: "Mossy Rock" },
    { key: 165, value: "Frozen Rock" },
    { key: 167, value: "Gone Pebble" },
    { key: 168, value: "Wander Gummi" },
    { key: 169, value: "Prize Ticket" },
    { key: 170, value: "Silver Ticket" },
    { key: 171, value: "Gold Ticket" },
    { key: 172, value: "Prism Ticket" },
    { key: 173, value: "Mystery Part" },
    { key: 174, value: "Secret Slab" },
    { key: 178, value: "Wonder Egg" },
    { key: 179, value: "Gracidea" },
    { key: 180, value: "Sky Gift" },
    { key: 182, value: "Key" },
    { key: 183, value: "None" },
    { key: 186, value: "Lost Loot" },
    { key: 187, value: "Used TM" },
    { key: 188, value: "Focus Punch" },
    { key: 189, value: "Dragon Claw" },
    { key: 190, value: "Water Pulse" },
    { key: 191, value: "Calm Mind" },
    { key: 192, value: "Roar" },
    { key: 193, value: "Toxic" },
    { key: 195, value: "Bulk Up" },
    { key: 196, value: "Bullet Seed" },
    { key: 197, value: "Hidden Power" },
    { key: 199, value: "Taunt" },
    { key: 200, value: "Ice Beam" },
    { key: 201, value: "Blizzard" },
    { key: 202, value: "Hyper Beam" },
    { key: 203, value: "Light Screen" },
    { key: 204, value: "Protect" },
    { key: 206, value: "Giga Drain" },
    { key: 207, value: "Safeguard" },
    { key: 208, value: "Frustration" },
    { key: 209, value: "SolarBeam" },
    { key: 210, value: "Iron Tail" },
    { key: 211, value: "Thunderbolt" },
    { key: 212, value: "Thunder" },
    { key: 213, value: "Earthquake" },
    { key: 214, value: "Return" },
    { key: 215, value: "Dig" },
    { key: 216, value: "Psychic" },
    { key: 217, value: "Shadow Ball" },
    { key: 218, value: "Brick Break" },
    { key: 220, value: "Reflect" },
    { key: 221, value: "Shock Wave" },
    { key: 222, value: "Flamethrower" },
    { key: 223, value: "Sludge Bomb" },
    { key: 225, value: "Fire Blast" },
    { key: 227, value: "Aerial Ace" },
    { key: 228, value: "Torment" },
    { key: 229, value: "Facade" },
    { key: 230, value: "Secret Power" },
    { key: 231, value: "Rest" },
    { key: 232, value: "Attract" },
    { key: 233, value: "Thief" },
    { key: 234, value: "Steel Wing" },
    { key: 235, value: "Skill Swap" },
    { key: 237, value: "Overheat" },
    { key: 238, value: "Roost" },
    { key: 239, value: "Focus Blast" },
    { key: 240, value: "Energy Ball" },
    { key: 241, value: "False Swipe" },
    { key: 242, value: "Brine" },
    { key: 243, value: "Fling" },
    { key: 244, value: "Charge Beam" },
    { key: 245, value: "Endure" },
    { key: 246, value: "Dragon Pulse" },
    { key: 247, value: "Drain Punch" },
    { key: 248, value: "Will-O-Wisp" },
    { key: 249, value: "Silver Wind" },
    { key: 250, value: "Embargo" },
    { key: 251, value: "Explosion" },
    { key: 252, value: "Shadow Claw" },
    { key: 253, value: "Payback" },
    { key: 254, value: "Recycle" },
    { key: 255, value: "Giga Impact" },
    { key: 256, value: "Rock Polish" },
    { key: 257, value: "Wide Slash" },
    { key: 260, value: "Vacuum-Cut" },
    { key: 261, value: "Dive" },
    { key: 262, value: "Flash" },
    { key: 263, value: "Stone Edge" },
    { key: 264, value: "Avalanche" },
    { key: 265, value: "Thunder Wave" },
    { key: 266, value: "Gyro Ball" },
    { key: 267, value: "Swords Dance" },
    { key: 268, value: "Stealth Rock" },
    { key: 269, value: "Psych Up" },
    { key: 270, value: "Captivate" },
    { key: 271, value: "Dark Pulse" },
    { key: 272, value: "Rock Slide" },
    { key: 273, value: "X-Scissor" },
    { key: 274, value: "Sleep Talk" },
    { key: 275, value: "Natural Gift" },
    { key: 276, value: "Poison Jab" },
    { key: 277, value: "Dream Eater" },
    { key: 278, value: "Grass Knot" },
    { key: 279, value: "Swagger" },
    { key: 280, value: "Pluck" },
    { key: 281, value: "U-turn" },
    { key: 282, value: "Substitute" },
    { key: 283, value: "Flash Cannon" },
    { key: 284, value: "Trick Room" },
    { key: 285, value: "Cut" },
    { key: 286, value: "Fly" },
    { key: 287, value: "Surf" },
    { key: 288, value: "Strength" },
    { key: 289, value: "Defog" },
    { key: 290, value: "Rock Smash" },
    { key: 291, value: "Waterfall" },
    { key: 292, value: "Rock Climb" },
    { key: 301, value: "Hail Orb" },
    { key: 302, value: "Sunny Orb" },
    { key: 303, value: "Rainy Orb" },
    { key: 304, value: "Evasion Orb" },
    { key: 305, value: "Sandy Orb" },
    { key: 306, value: "Rocky Orb" },
    { key: 307, value: "Snatch Orb" },
    { key: 308, value: "See-Trap Orb" },
    { key: 309, value: "Mug Orb" },
    { key: 310, value: "Rebound Orb" },
    { key: 311, value: "Lob Orb" },
    { key: 312, value: "Switcher Orb" },
    { key: 313, value: "Blowback Orb" },
    { key: 314, value: "Warp Orb" },
    { key: 315, value: "Transfer Orb" },
    { key: 316, value: "Slow Orb" },
    { key: 317, value: "Quick Orb" },
    { key: 318, value: "Luminous Orb" },
    { key: 319, value: "Petrify Orb" },
    { key: 320, value: "Stayaway Orb" },
    { key: 321, value: "Pounce Orb" },
    { key: 322, value: "Trawl Orb" },
    { key: 323, value: "Cleanse Orb" },
    { key: 325, value: "Decoy Orb" },
    { key: 326, value: "Slumber Orb" },
    { key: 327, value: "Totter Orb" },
    { key: 328, value: "Two-Edge Orb" },
    { key: 329, value: "Silence Orb" },
    { key: 330, value: "Escape Orb" },
    { key: 331, value: "Scanner Orb" },
    { key: 332, value: "Radar Orb" },
    { key: 333, value: "Drought Orb" },
    { key: 334, value: "Trapbust Orb" },
    { key: 335, value: "Rollcall Orb" },
    { key: 336, value: "Invisify Orb" },
    { key: 337, value: "One-Shot Orb" },
    { key: 338, value: "Identify Orb" },
    { key: 340, value: "Shocker Orb" },
    { key: 341, value: "Sizebust Orb" },
    { key: 342, value: "One-Room Orb" },
    { key: 343, value: "Fill-In Orb" },
    { key: 344, value: "Trapper Orb" },
    { key: 346, value: "Itemizer Orb" },
    { key: 347, value: "Hurl Orb" },
    { key: 348, value: "Mobile Orb" },
    { key: 350, value: "Stairs Orb" },
    { key: 351, value: "Longtoss Orb" },
    { key: 352, value: "Pierce Orb" },
    { key: 354, value: "Spurn Orb" },
    { key: 355, value: "Foe-Hold Orb" },
    { key: 356, value: "All-Mach Orb" },
    { key: 357, value: "Foe-Fear Orb" },
    { key: 358, value: "All-Hit Orb" },
    { key: 359, value: "Foe-Seal Orb" },
    { key: 362, value: "Link Box" },
    { key: 364, value: "Gorgeous Box" },
    { key: 365, value: "Gorgeous Box" },
    { key: 366, value: "Gorgeous Box" },
    { key: 367, value: "Heavy Box" },
    { key: 368, value: "Heavy Box" },
    { key: 369, value: "Heavy Box" },
    { key: 370, value: "Shiny Box" },
    { key: 371, value: "Shiny Box" },
    { key: 372, value: "Shiny Box" },
    { key: 373, value: "Nifty Box" },
    { key: 374, value: "Nifty Box" },
    { key: 375, value: "Nifty Box" },
    { key: 376, value: "Dainty Box" },
    { key: 377, value: "Dainty Box" },
    { key: 378, value: "Dainty Box" },
    { key: 379, value: "Glittery Box" },
    { key: 380, value: "Glittery Box" },
    { key: 381, value: "Glittery Box" },
    { key: 382, value: "Pretty Box" },
    { key: 383, value: "Pretty Box" },
    { key: 384, value: "Pretty Box" },
    { key: 385, value: "Deluxe Box" },
    { key: 386, value: "Deluxe Box" },
    { key: 387, value: "Deluxe Box" },
    { key: 388, value: "Light Box" },
    { key: 389, value: "Light Box" },
    { key: 390, value: "Light Box" },
    { key: 391, value: "Cute Box" },
    { key: 392, value: "Cute Box" },
    { key: 393, value: "Cute Box" },
    { key: 394, value: "Hard Box" },
    { key: 395, value: "Hard Box" },
    { key: 396, value: "Hard Box" },
    { key: 397, value: "Sinister Box" },
    { key: 398, value: "Sinister Box" },
    { key: 399, value: "Sinister Box" },
    { key: 400, value: "A-Stone" },
    { key: 401, value: "B-Stone" },
    { key: 402, value: "C-Stone" },
    { key: 403, value: "D-Stone" },
    { key: 404, value: "E-Stone" },
    { key: 405, value: "F-Stone" },
    { key: 406, value: "G-Stone" },
    { key: 407, value: "H-Stone" },
    { key: 408, value: "I-Stone" },
    { key: 409, value: "J-Stone" },
    { key: 410, value: "K-Stone" },
    { key: 411, value: "L-Stone" },
    { key: 412, value: "M-Stone" },
    { key: 413, value: "N-Stone" },
    { key: 414, value: "O-Stone" },
    { key: 415, value: "P-Stone" },
    { key: 416, value: "Q-Stone" },
    { key: 417, value: "R-Stone" },
    { key: 418, value: "S-Stone" },
    { key: 419, value: "T-Stone" },
    { key: 420, value: "U-Stone" },
    { key: 421, value: "V-Stone" },
    { key: 422, value: "W-Stone" },
    { key: 423, value: "X-Stone" },
    { key: 424, value: "Y-Stone" },
    { key: 425, value: "Z-Stone" },
    { key: 426, value: "!-Stone" },
    { key: 427, value: "?-Stone" },
    { key: 428, value: "Silver Bow" },
    { key: 429, value: "Brown Bow" },
    { key: 430, value: "Red Bow" },
    { key: 431, value: "Pink Bow" },
    { key: 432, value: "Orange Bow" },
    { key: 433, value: "Yellow Bow" },
    { key: 434, value: "Lime Bow" },
    { key: 435, value: "Green Bow" },
    { key: 436, value: "Viridian Bow" },
    { key: 437, value: "Minty Bow" },
    { key: 438, value: "Sky Blue Bow" },
    { key: 439, value: "Blue Bow" },
    { key: 440, value: "Cobalt Bow" },
    { key: 441, value: "Purple Bow" },
    { key: 442, value: "Violet Bow" },
    { key: 443, value: "Fuchsia Bow" },
    { key: 444, value: "Prism Ruff" },
    { key: 445, value: "Aqua Collar" },
    { key: 446, value: "Volt Collar" },
    { key: 447, value: "Fire Collar" },
    { key: 448, value: "Light Collar" },
    { key: 449, value: "Dusk Collar" },
    { key: 450, value: "Virid Collar" },
    { key: 451, value: "Icy Collar" },
    { key: 452, value: "Pep Sash" },
    { key: 453, value: "Counter Ruff" },
    { key: 454, value: "Victory Belt" },
    { key: 455, value: "Power Bangle" },
    { key: 456, value: "Thundershard" },
    { key: 457, value: "Fallen Star" },
    { key: 458, value: "Fluff Dust" },
    { key: 459, value: "Egg Shard" },
    { key: 460, value: "Heroic Medal" },
    { key: 461, value: "Chic Shard" },
    { key: 462, value: "Yellow Jewel" },
    { key: 463, value: "Red Jewel" },
    { key: 464, value: "Blue Jewel" },
    { key: 465, value: "Laugh Dust" },
    { key: 466, value: "Guard Sand" },
    { key: 467, value: "Purple Jewel" },
    { key: 468, value: "White Jewel" },
    { key: 469, value: "Brave Dust" },
    { key: 470, value: "Heal Dew" },
    { key: 471, value: "Marine Cache" },
    { key: 472, value: "Freeze Veil" },
    { key: 473, value: "Thunder Veil" },
    { key: 474, value: "Fire Veil" },
    { key: 475, value: "Havoc Robe" },
    { key: 476, value: "Life Ring" },
    { key: 477, value: "Bolt Fang" },
    { key: 478, value: "Flare Fang" },
    { key: 479, value: "Aqua Mantle" },
    { key: 480, value: "Silver Veil" },
    { key: 481, value: "Rainbow Veil" },
    { key: 482, value: "Chrono Veil" },
    { key: 483, value: "Rock Sash" },
    { key: 484, value: "Ice Sash" },
    { key: 485, value: "Steel Sash" },
    { key: 486, value: "Heart Brooch" },
    { key: 487, value: "Eon Veil" },
    { key: 488, value: "Seabed Veil" },
    { key: 489, value: "Terra Ring" },
    { key: 490, value: "SkyHigh Veil" },
    { key: 491, value: "Wish Mantle" },
    { key: 492, value: "Revive Robe" },
    { key: 493, value: "Shadow Veil" },
    { key: 494, value: "Plasma Veil" },
    { key: 495, value: "Edify Robe" },
    { key: 496, value: "Charity Robe" },
    { key: 497, value: "Hope Robe" },
    { key: 498, value: "Time Shield" },
    { key: 499, value: "Air Blade" },
    { key: 500, value: "Searing Ring" },
    { key: 501, value: "Ancient Ring" },
    { key: 502, value: "Nether Veil" },
    { key: 503, value: "Lunar Veil" },
    { key: 504, value: "Tidal Cape" },
    { key: 505, value: "Eclipse Robe" },
    { key: 506, value: "White Silk" },
    { key: 507, value: "Normal Dust" },
    { key: 508, value: "White Gem" },
    { key: 509, value: "Joy Globe" },
    { key: 510, value: "Red Silk" },
    { key: 511, value: "Fire Dust" },
    { key: 512, value: "Fiery Gem" },
    { key: 513, value: "Fiery Globe" },
    { key: 514, value: "Blue Silk" },
    { key: 515, value: "Water Dust" },
    { key: 516, value: "Aqua Gem" },
    { key: 517, value: "Aqua Globe" },
    { key: 518, value: "Grass Slik" },
    { key: 519, value: "Grass Dust" },
    { key: 520, value: "Grass Gem" },
    { key: 521, value: "Soothe Globe" },
    { key: 522, value: "Yellow Globe" },
    { key: 523, value: "Thunder Dust" },
    { key: 524, value: "Thunder Gem" },
    { key: 525, value: "Volt Globe" },
    { key: 526, value: "Clear Silk" },
    { key: 527, value: "Icy Dust" },
    { key: 528, value: "Icy Gem" },
    { key: 529, value: "Icy Globe" },
    { key: 530, value: "Orange Silk" },
    { key: 531, value: "Courage Dust" },
    { key: 532, value: "Fight Gem" },
    { key: 533, value: "Power Globe" },
    { key: 534, value: "Pink Silk" },
    { key: 535, value: "Poison Dust" },
    { key: 536, value: "Poison Gem" },
    { key: 537, value: "Poison Globe" },
    { key: 538, value: "Brown Silk" },
    { key: 539, value: "Ground Dust" },
    { key: 540, value: "Earth Gem" },
    { key: 541, value: "Terra Globe" },
    { key: 542, value: "Sky Silk" },
    { key: 543, value: "Sky Dust" },
    { key: 544, value: "Sky Gem" },
    { key: 545, value: "Sky Globe" },
    { key: 546, value: "Gold Silk" },
    { key: 547, value: "Psyche Dust" },
    { key: 548, value: "Psyche Gem" },
    { key: 549, value: "Psyche Globe" },
    { key: 550, value: "Green Silk" },
    { key: 551, value: "Wonder Dust" },
    { key: 552, value: "Guard Gem" },
    { key: 553, value: "Defend Globe" },
    { key: 554, value: "Gray Silk" },
    { key: 555, value: "Rock Dust" },
    { key: 556, value: "Stone Gem" },
    { key: 557, value: "Rock Globe" },
    { key: 558, value: "Purple Silk" },
    { key: 559, value: "Shady Dust" },
    { key: 560, value: "Shadow Gem" },
    { key: 561, value: "Nether Globe" },
    { key: 562, value: "Royal Silk" },
    { key: 563, value: "Dragon Dust" },
    { key: 564, value: "Dragon Gem" },
    { key: 565, value: "Dragon Globe" },
    { key: 566, value: "Black Silk" },
    { key: 567, value: "Dark Dust" },
    { key: 568, value: "Dark Gem" },
    { key: 569, value: "Dusk Globe" },
    { key: 570, value: "Iron Silk" },
    { key: 571, value: "Steel Dust" },
    { key: 572, value: "Metal Gem" },
    { key: 573, value: "Steel Globe" },
    { key: 574, value: "Bulba-Claw" },
    { key: 575, value: "Bulba-Fang" },
    { key: 576, value: "Grass-Guard" },
    { key: 577, value: "Leafy Tie" },
    { key: 578, value: "Ivy-Claw" },
    { key: 579, value: "Ivy-Fang" },
    { key: 580, value: "Ivy-Crest" },
    { key: 581, value: "Plant Torc" },
    { key: 582, value: "Venus-Claw" },
    { key: 583, value: "Venus-Fang" },
    { key: 584, value: "Venus-Seal" },
    { key: 585, value: "Solar Sash" },
    { key: 586, value: "Char-Claw" },
    { key: 587, value: "Char-Fang" },
    { key: 588, value: "Fiery Heart" },
    { key: 589, value: "Heat Armlet" },
    { key: 590, value: "Charme-Claw" },
    { key: 591, value: "Charme-Fang" },
    { key: 592, value: "Charme-Crest" },
    { key: 593, value: "Kindle Scarf" },
    { key: 594, value: "Chariz-Claw" },
    { key: 595, value: "Chariz-Fang" },
    { key: 596, value: "Chariz-Seal" },
    { key: 597, value: "Flame Bangle" },
    { key: 598, value: "Squirt-Foam" },
    { key: 599, value: "Squirt-Card" },
    { key: 600, value: "Water-Guard" },
    { key: 601, value: "Aqua Tie" },
    { key: 602, value: "Wartor-Claw" },
    { key: 603, value: "Wartor-Fang" },
    { key: 604, value: "Wartor-Crest" },
    { key: 605, value: "BubbleBangle" },
    { key: 606, value: "Blasto-Claw" },
    { key: 607, value: "Blasto-Card" },
    { key: 608, value: "Blasto-Seal" },
    { key: 609, value: "Hydro Band" },
    { key: 610, value: "Pichu Hair" },
    { key: 611, value: "Pichu Card" },
    { key: 612, value: "Express Tag" },
    { key: 613, value: "Shocker Cape" },
    { key: 614, value: "Pikachu Hair" },
    { key: 615, value: "Pikachu Card" },
    { key: 616, value: "Volt Charm" },
    { key: 617, value: "Volt Torc" },
    { key: 618, value: "Raichu Hair" },
    { key: 619, value: "Raichu Card" },
    { key: 620, value: "Raichu Crest" },
    { key: 621, value: "Zapper Scarf" },
    { key: 622, value: "Meowth Claw" },
    { key: 623, value: "Meowth Fang" },
    { key: 624, value: "Coin Charm" },
    { key: 625, value: "Bling Ruff" },
    { key: 626, value: "Persian Claw" },
    { key: 627, value: "Persain Fang" },
    { key: 628, value: "Insight Rock" },
    { key: 629, value: "Noble Scarf" },
    { key: 630, value: "Chiko-Claw" },
    { key: 631, value: "Chiko-Card" },
    { key: 632, value: "Dawn Jewel" },
    { key: 633, value: "Fresh Bow" },
    { key: 634, value: "Bayleef Claw" },
    { key: 635, value: "Bayleef Card" },
    { key: 636, value: "Bayleef Seal" },
    { key: 637, value: "Spice Bow" },
    { key: 638, value: "Megani-Claw" },
    { key: 639, value: "Megani-Card" },
    { key: 640, value: "Shiny Charm" },
    { key: 641, value: "Bright Veil" },
    { key: 642, value: "Cynda-Hair" },
    { key: 643, value: "Cynda-Claw" },
    { key: 644, value: "Blazing Rock" },
    { key: 645, value: "Storm Sash" },
    { key: 646, value: "Quila-Hair" },
    { key: 647, value: "Quila-Card" },
    { key: 648, value: "Quila-Crest" },
    { key: 649, value: "Volcano Torc" },
    { key: 650, value: "Typhlo-Gasp" },
    { key: 651, value: "Typhlo-Fang" },
    { key: 652, value: "Typhlo-Seal" },
    { key: 653, value: "Blast Bangle" },
    { key: 654, value: "Totodi-Dew" },
    { key: 655, value: "Totodi-Fang" },
    { key: 656, value: "Water Heart" },
    { key: 657, value: "Wash Bow" },
    { key: 658, value: "Croco-Fang" },
    { key: 659, value: "Croco-Card" },
    { key: 660, value: "Swirl Rock" },
    { key: 661, value: "Anger Scarf" },
    { key: 662, value: "Feral-Claw" },
    { key: 663, value: "Feral-Fang" },
    { key: 664, value: "Feral-Crest" },
    { key: 665, value: "Hydro Jaw" },
    { key: 666, value: "Treeck-Thorn" },
    { key: 667, value: "Treeck-Card" },
    { key: 668, value: "Forest Ore" },
    { key: 669, value: "Guard Ring" },
    { key: 670, value: "Grovy-Shoot" },
    { key: 671, value: "Grovy-Card" },
    { key: 672, value: "Jungle-Tag" },
    { key: 673, value: "Grass Blade" },
    { key: 674, value: "Scept-Claw" },
    { key: 675, value: "Scept-Card" },
    { key: 676, value: "Scept-Seal" },
    { key: 677, value: "Drain Bangle" },
    { key: 678, value: "Torchic Hair" },
    { key: 679, value: "Torchic Card" },
    { key: 680, value: "Hot Pebble" },
    { key: 681, value: "Fire Cape" },
    { key: 682, value: "Combus-Sweat" },
    { key: 683, value: "Combus-Claw" },
    { key: 684, value: "Charge Tag" },
    { key: 685, value: "Gutsy Band" },
    { key: 686, value: "Blazi-Claw" },
    { key: 687, value: "Blazi-Card" },
    { key: 688, value: "Blazi-Seal" },
    { key: 689, value: "Blaze Torc" },
    { key: 690, value: "Mudkip Mud" },
    { key: 691, value: "Mudkip Card" },
    { key: 692, value: "Mud Jewel" },
    { key: 693, value: "Speed Scarf" },
    { key: 694, value: "Marsh-Mud" },
    { key: 695, value: "Marsh-Card" },
    { key: 696, value: "Marsh-Crest" },
    { key: 697, value: "Marsh Torc" },
    { key: 698, value: "Swamp-Mud" },
    { key: 699, value: "Swamp-Card" },
    { key: 700, value: "Swamp-Seal"},
    { key: 701, value: "Swamp Bangle"},
    { key: 702, value: "Skitty Fang"},
    { key: 703, value: "Skitty Card"},
    { key: 704, value: "Smile Pebble"},
    { key: 705, value: "Heal Pendant"},
    { key: 706, value: "Delcat-Hair"},
    { key: 707, value: "Delcat-Fang"},
    { key: 708, value: "Prim Pebble"},
    { key: 709, value: "Guard Collar"},
    { key: 710, value: "Lucky Leaf"},
    { key: 711, value: "Turtwig Card"},
    { key: 712, value: "Sprout Rock"},
    { key: 713, value: "Leafy Hat"},
    { key: 714, value: "Grotle Twig"},
    { key: 715, value: "Grotle Claw"},
    { key: 716, value: "Grotle Crest"},
    { key: 717, value: "Woody Scarf"},
    { key: 718, value: "Tort-Claw"},
    { key: 719, value: "Tort-Horn"},
    { key: 720, value: "Tort-Seal"},
    { key: 721, value: "Forest Torc"},
    { key: 722, value: "Chim-Hair"},
    { key: 723, value: "Chim-Fang"},
    { key: 724, value: "Nimble Charm"},
    { key: 725, value: "Ember Cap"},
    { key: 726, value: "Monfer-Hair"},
    { key: 727, value: "Monfer-Fang"},
    { key: 728, value: "Monfer-Crest"},
    { key: 729, value: "Burst Sash"},
    { key: 730, value: "Infern-Hair"},
    { key: 731, value: "Infern-Fang"},
    { key: 732, value: "Infern-Seal"},
    { key: 733, value: "Blazing Ruff"},
    { key: 734, value: "Piplup Foam"},
    { key: 735, value: "Piplup Card"},
    { key: 736, value: "Sea Ore"},
    { key: 737, value: "Water Cape"},
    { key: 738, value: "Prin-Foam"},
    { key: 739, value: "Prin-Card"},
    { key: 740, value: "Prin-Crest"},
    { key: 741, value: "Aqua Blade"},
    { key: 742, value: "Empol-Claw"},
    { key: 743, value: "Empol-Horn"},
    { key: 744, value: "Empol-Seal"},
    { key: 745, value: "Marine Crown"},
    { key: 746, value: "Munch Drool"},
    { key: 747, value: "Munch-Claw"},
    { key: 748, value: "Tummy Charm"},
    { key: 749, value: "Glutton Cape"},
    { key: 750, value: "Snorlax Gasp"},
    { key: 751, value: "Snorlax Fang"},
    { key: 752, value: "Valor Charm"},
    { key: 753, value: "Glee Scarf"},
    { key: 754, value: "Scyther Fang"},
    { key: 755, value: "Scyther Card"},
    { key: 756, value: "Ambush Rock"},
    { key: 757, value: "Strike Ruff"},
    { key: 758, value: "Scizor Wing"},
    { key: 759, value: "Scizor Card"},
    { key: 760, value: "Steel Charm"},
    { key: 761, value: "Red Armlet"},
    { key: 762, value: "Lapras Song"},
    { key: 763, value: "Lapras Card"},
    { key: 764, value: "Wavy Charm"},
    { key: 765, value: "Mystic Scarf"},
    { key: 766, value: "Eevee Tail"},
    { key: 767, value: "Eevee Card"},
    { key: 768, value: "Evolve Charm"},
    { key: 770, value: "Cleffa Dew"},
    { key: 771, value: "Cleffa Card"},
    { key: 772, value: "Starry Ore"},
    { key: 773, value: "Comet Ring"},
    { key: 774, value: "Clef-Claw"},
    { key: 775, value: "Clef-Fang"},
    { key: 776, value: "Moon Jewel"},
    { key: 777, value: "Moon Scarf"},
    { key: 778, value: "Clefa-Claw"},
    { key: 779, value: "Clefa-Card"},
    { key: 780, value: "Moon Rock"},
    { key: 781, value: "Fairy Bow"},
    { key: 782, value: "Iggly-Dew"},
    { key: 783, value: "Iggly-Card"},
    { key: 784, value: "Bouncy Charm"},
    { key: 785, value: "Pretty Bow"},
    { key: 786, value: "Jiggly-Song"},
    { key: 787, value: "Jiggly-Card"},
    { key: 788, value: "Slumber Rock"},
    { key: 789, value: "Snooze Ring"},
    { key: 790, value: "Wiggly-Hair"},
    { key: 791, value: "Wiggly-Card"},
    { key: 792, value: "Buddy Rock"},
    { key: 793, value: "Friend Torc"},
    { key: 794, value: "Togepi Dew"},
    { key: 795, value: "Togepi Card"},
    { key: 796, value: "Pure Heart"},
    { key: 797, value: "Angel Scarf"},
    { key: 798, value: "Togetic Wing"},
    { key: 799, value: "Togetic Card"},
    { key: 800, value: "Happy Rock"},
    { key: 801, value: "Luck Brooch"},
    { key: 802, value: "Togek-Wing"},
    { key: 803, value: "Togek-Card"},
    { key: 804, value: "Ovation Rock"},
    { key: 805, value: "Glitter Robe"},
    { key: 806, value: "Sneasel Claw"},
    { key: 807, value: "Sneasel Card"},
    { key: 808, value: "Dusk Jewel"},
    { key: 809, value: "Cruel Ring"},
    { key: 810, value: "Weavile Claw"},
    { key: 811, value: "Weavile Fang"},
    { key: 812, value: "Vile Tag"},
    { key: 813, value: "Ruin Armlet"},
    { key: 814, value: "Teddi-Claw"},
    { key: 815, value: "Teddi-Card"},
    { key: 816, value: "Honey Rock"},
    { key: 817, value: "Heal Scarf"},
    { key: 818, value: "Ursa-Claw"},
    { key: 819, value: "Ursa-Fang"},
    { key: 820, value: "Calming Rock"},
    { key: 821, value: "Hiber Scarf"},
    { key: 822, value: "Tyro-Sweat"},
    { key: 823, value: "Tyro-Card"},
    { key: 824, value: "Muscle Charm"},
    { key: 826, value: "Smooch-Song"},
    { key: 827, value: "Smooch-Card"},
    { key: 828, value: "Kiss Charm"},
    { key: 829, value: "Heart Tiara"},
    { key: 830, value: "Jynx Song"},
    { key: 831, value: "Jynx Card"},
    { key: 832, value: "Frozen Ore"},
    { key: 833, value: "Ruin Scarf"},
    { key: 834, value: "Elekid Claw"},
    { key: 835, value: "Elekid Claw"},
    { key: 836, value: "Jolt Charm"},
    { key: 837, value: "Current Ring"},
    { key: 838, value: "Electa-Claw"},
    { key: 839, value: "Electa-Fang"},
    { key: 840, value: "Charge Seal"},
    { key: 841, value: "Volt Bangle"},
    { key: 842, value: "Electi-Claw"},
    { key: 843, value: "Electi-Card"},
    { key: 844, value: "Voltaic Rock"},
    { key: 845, value: "Voltaic Band"},
    { key: 846, value: "Magby Claw"},
    { key: 847, value: "Magby Card"},
    { key: 848, value: "Ember Jewel"},
    { key: 849, value: "Coal Ring"},
    { key: 850, value: "Magmar Claw"},
    { key: 851, value: "Magmar Card"},
    { key: 852, value: "Erupt Ore"},
    { key: 853, value: "Magma Scarf"},
    { key: 854, value: "Magmor-Claw"},
    { key: 855, value: "Magmor-Card"},
    { key: 856, value: "Vulcan Rock"},
    { key: 857, value: "Burning Torc"},
    { key: 858, value: "Azuri-Dew"},
    { key: 859, value: "Azuri-Card"},
    { key: 860, value: "Fount Charm"},
    { key: 861, value: "Water Float"},
    { key: 862, value: "Marill Dew"},
    { key: 863, value: "Marill Card"},
    { key: 864, value: "Surfer Rock"},
    { key: 865, value: "Brine Scarf"},
    { key: 866, value: "Azuma-Dew"},
    { key: 867, value: "Azuma-Card"},
    { key: 868, value: "Stream Charm"},
    { key: 869, value: "Dotted Scarf"},
    { key: 870, value: "Plusle Tail"},
    { key: 871, value: "Plusle Card"},
    { key: 872, value: "Cheer Rock"},
    { key: 873, value: "Pulse Bow"},
    { key: 874, value: "Minun Tail"},
    { key: 875, value: "Minun Card"},
    { key: 876, value: "Volt Heart"},
    { key: 877, value: "Spark Tie"},
    { key: 878, value: "Cast-Dew"},
    { key: 879, value: "Cast-Card"},
    { key: 880, value: "Cloud Rock"},
    { key: 881, value: "Weather Cape"},
    { key: 882, value: "Wynaut Tail"},
    { key: 883, value: "Wynaut Card"},
    { key: 884, value: "Grin Charm"},
    { key: 885, value: "Cheery Scarf"},
    { key: 886, value: "Wobbu-Sweat"},
    { key: 887, value: "Wobbu-Card"},
    { key: 888, value: "Endure Rock"},
    { key: 889, value: "Suffer Scarf"},
    { key: 890, value: "Bidoof Scarf"},
    { key: 891, value: "Bidoof Card"},
    { key: 892, value: "Fall Charm"},
    { key: 893, value: "Stolid Scarf"},
    { key: 894, value: "Biba-Tooth"},
    { key: 895, value: "Biba-Card"},
    { key: 896, value: "River Charm"},
    { key: 897, value: "Dam Scarf"},
    { key: 898, value: "Shinx Claw"},
    { key: 899, value: "Shinx Fang"},
    { key: 900, value: "Flash Tag"},
    { key: 901, value: "Energy Scarf"},
    { key: 902, value: "Luxio Claw"},
    { key: 903, value: "Luxio Fang"},
    { key: 904, value: "Spark Tag"},
    { key: 905, value: "Spark Scarf"},
    { key: 906, value: "Luxray Claw"},
    { key: 907, value: "Luxray Fang"},
    { key: 908, value: "Glare Tag"},
    { key: 909, value: "Glare Sash"},
    { key: 910, value: "Pachi-Tooth"},
    { key: 911, value: "Pachi-Card"},
    { key: 912, value: "Rouse Charm"},
    { key: 913, value: "Miracle Bow"},
    { key: 914, value: "Buizel Fang"},
    { key: 915, value: "Buizel Card"},
    { key: 916, value: "Swimmer Rock"},
    { key: 917, value: "Screw Torc"},
    { key: 918, value: "Float-Fang"},
    { key: 919, value: "Float-Card"},
    { key: 920, value: "Rescue Rock"},
    { key: 921, value: "Float Aid"},
    { key: 922, value: "Drifloo-Gasp"},
    { key: 923, value: "Drifloo-Card"},
    { key: 924, value: "Wind Heart"},
    { key: 925, value: "Draft Ring"},
    { key: 926, value: "Drifbli-Gasp"},
    { key: 927, value: "Drifbli-Card"},
    { key: 928, value: "Easy Charm"},
    { key: 929, value: "Breeze Scarf"},
    { key: 930, value: "Cherubi Seed"},
    { key: 931, value: "Cherubi Card"},
    { key: 932, value: "Cute Ore"},
    { key: 933, value: "Charm Bow"},
    { key: 934, value: "Cherrim Dew"},
    { key: 935, value: "Cherrim Card"},
    { key: 936, value: "Sweet Aroma"},
    { key: 937, value: "Petal Dress"},
    { key: 938, value: "Bonsly Dew"},
    { key: 939, value: "Bonsly Card"},
    { key: 940, value: "Arid Tag"},
    { key: 941, value: "Teary Cape"},
    { key: 942, value: "Sudo-Sweat"},
    { key: 943, value: "Sudo-Card"},
    { key: 944, value: "Drain Rock"},
    { key: 945, value: "Fake Torc"},
    { key: 946, value: "Junior Beam"},
    { key: 947, value: "Junior Card"},
    { key: 948, value: "Mimic Pebble"},
    { key: 949, value: "Copy Mask"},
    { key: 950, value: "Mime Key"},
    { key: 951, value: "Mime Card"},
    { key: 952, value: "Bulwark Rock"},
    { key: 953, value: "Barrier Bow"},
    { key: 954, value: "Happiny Dew"},
    { key: 955, value: "Happiny Card"},
    { key: 956, value: "Play Tag"},
    { key: 957, value: "Nurture Cape"},
    { key: 958, value: "Chansey Song"},
    { key: 959, value: "Chansey Card"},
    { key: 960, value: "Lucky Charm"},
    { key: 961, value: "Lucky Scarf"},
    { key: 962, value: "Blissey Song"},
    { key: 963, value: "Blissey Card"},
    { key: 964, value: "Amity Rock"},
    { key: 965, value: "Faith Ring"},
    { key: 966, value: "Gible Fang"},
    { key: 967, value: "Gible Card"},
    { key: 968, value: "Dragon Jewel"},
    { key: 969, value: "Dragon Tie"},
    { key: 970, value: "Gabite Claw"},
    { key: 971, value: "Gabite Fang"},
    { key: 972, value: "Star Rock"},
    { key: 973, value: "Meteor Torc"},
    { key: 974, value: "Gar-Claw"},
    { key: 975, value: "Gar-Fang"},
    { key: 976, value: "Speed Tag"},
    { key: 977, value: "Mach Scarf"},
    { key: 978, value: "Riolu Tail"},
    { key: 979, value: "Riolu Card"},
    { key: 980, value: "Valiant Rock"},
    { key: 981, value: "Emit Ring"},
    { key: 982, value: "Lucario Fang"},
    { key: 983, value: "Lucario Card"},
    { key: 984, value: "Pledge Rock"},
    { key: 985, value: "Ravage Ring"},
    { key: 986, value: "Mantyke Beam"},
    { key: 987, value: "Mantyke Card"},
    { key: 988, value: "Waft Rock"},
    { key: 989, value: "Ocean Bow"},
    { key: 990, value: "Mantine Foam"},
    { key: 991, value: "Mantine Card"},
    { key: 992, value: "Sunset Rock"},
    { key: 993, value: "Horizon Bow"},
    { key: 994, value: "Phione Song"},
    { key: 995, value: "Phione Card"},
    { key: 996, value: "Wave Jewel"},
    { key: 997, value: "Ripple Cape"},
    { key: 998, value: "Vulpix Tail"},
    { key: 999, value: "Vulpix Card"},
    { key: 1000, value: "Vulpix Tag" },
    { key: 1001, value: "Glowing Bow" },
    { key: 1002, value: "Nine-Hair" },
    { key: 1003, value: "Nine-Card" },
    { key: 1004, value: "Nine-Seal" },
    { key: 1005, value: "Afire Collar" },
    { key: 1006, value: "Phanpy Claw" },
    { key: 1007, value: "Phanpy Card" },
    { key: 1008, value: "Phanpy Tag" },
    { key: 1009, value: "Value Ruff" },
    { key: 1010, value: "Donphan Fang" },
    { key: 1011, value: "Donphan Card" },
    { key: 1012, value: "Don-Crest" },
    { key: 1013, value: "Armor Scarf" },
    { key: 1014, value: "Cater-Belt" },
    { key: 1015, value: "Defense Bow" },
    { key: 1016, value: "Glittery Bow" },
    { key: 1017, value: "Weedle Bow" },
    { key: 1018, value: "Kakuna Scarf" },
    { key: 1019, value: "Charge Scarf" },
    { key: 1020, value: "Pidgey Bow" },
    { key: 1021, value: "Pidgeo-Scarf" },
    { key: 1022, value: "Pidgeot Torc" },
    { key: 1023, value: "Ratta-Scarf" },
    { key: 1024, value: "Overcome Bow" },
    { key: 1025, value: "Quirky Bow" },
    { key: 1026, value: "Wing Scarf" },
    { key: 1027, value: "Leash Bow" },
    { key: 1028, value: "Shock Ruff" },
    { key: 1029, value: "Sand-Scarf" },
    { key: 1030, value: "Sandy Torc" },
    { key: 1031, value: "Pointy Scarf" },
    { key: 1032, value: "Return Scarf" },
    { key: 1033, value: "Impact Torc" },
    { key: 1034, value: "Halve Scarf" },
    { key: 1035, value: "Thorny Scarf" },
    { key: 1036, value: "King Sash" },
    { key: 1037, value: "Dodge Bow" },
    { key: 1038, value: "Absorb Scarf" },
    { key: 1039, value: "Odd Bow" },
    { key: 1040, value: "Guard Hat" },
    { key: 1041, value: "Aroma Scarf" },
    { key: 1042, value: "Moving Scarf" },
    { key: 1043, value: "Firm Hat" },
    { key: 1044, value: "Gaze Goggles" },
    { key: 1045, value: "Venomoth Bow" },
    { key: 1046, value: "Diglett Hat" },
    { key: 1047, value: "Dugtrio Bow" },
    { key: 1048, value: "Psyduck Hat" },
    { key: 1049, value: "Paddle Scarf" },
    { key: 1050, value: "Mankey Torc" },
    { key: 1051, value: "Nullify Belt" },
    { key: 1052, value: "Growl-Scarf" },
    { key: 1053, value: "Legend Bow" },
    { key: 1054, value: "Damp Bow" },
    { key: 1055, value: "Poli-Bow" },
    { key: 1056, value: "Bold Belt" },
    { key: 1057, value: "Predict Torc" },
    { key: 1058, value: "Psychic Torc" },
    { key: 1059, value: "Sparkle Ruff" },
    { key: 1060, value: "Impish Band" },
    { key: 1061, value: "Strong Belt" },
    { key: 1062, value: "Machamp Belt" },
    { key: 1063, value: "Bell-Bow" },
    { key: 1064, value: "Digest Scarf" },
    { key: 1065, value: "Victree-Torc" },
    { key: 1066, value: "Tangle Bow" },
    { key: 1067, value: "Tenta-Cape" },
    { key: 1068, value: "Geodude Torc" },
    { key: 1069, value: "Rocky Torc" },
    { key: 1070, value: "Rugged Sash" },
    { key: 1071, value: "Heated Bow" },
    { key: 1072, value: "Sunlight Bow" },
    { key: 1073, value: "Slowpoke Hat" },
    { key: 1074, value: "Slow-Scarf" },
    { key: 1075, value: "Magne-Torc" },
    { key: 1076, value: "Magneton Bow" },
    { key: 1077, value: "Bullseye Bow" },
    { key: 1078, value: "Buddy Torc" },
    { key: 1079, value: "Fight Torc" },
    { key: 1080, value: "Gentle Bow" },
    { key: 1081, value: "North Torc" },
    { key: 1082, value: "Grimy Scarf" },
    { key: 1083, value: "Slimy Bow" },
    { key: 1084, value: "Shell-Torc" },
    { key: 1085, value: "Cover Armor" },
    { key: 1086, value: "Gastly Veil" },
    { key: 1087, value: "Slip Scarf" },
    { key: 1088, value: "Sunglasses" },
    { key: 1089, value: "Trust Brooch" },
    { key: 1090, value: "Drowzee Tie" },
    { key: 1091, value: "Dream Coin" },
    { key: 1092, value: "Krabby Bow" },
    { key: 1093, value: "Super Sash" },
    { key: 1094, value: "Ball Scarf" },
    { key: 1095, value: "Electro-Bow" },
    { key: 1096, value: "Repel Scarf" },
    { key: 1097, value: "Exeggu-Sash" },
    { key: 1098, value: "Cubone Scarf" },
    { key: 1099, value: "Marowak Torc" },
    { key: 1100, value: "Licky Scarf" },
    { key: 1101, value: "Koffing Bow" },
    { key: 1102, value: "Weez-Scarf" },
    { key: 1103, value: "Solid Shield" },
    { key: 1104, value: "Pierce Drill" },
    { key: 1105, value: "Sticky Bow" },
    { key: 1106, value: "Kang-Apron" },
    { key: 1107, value: "Horsea Bow" },
    { key: 1108, value: "Swirl Scarf" },
    { key: 1109, value: "Goldeen Bow" },
    { key: 1110, value: "Seaking Bow" },
    { key: 1111, value: "Recover Torc" },
    { key: 1112, value: "Starmie Belt" },
    { key: 1113, value: "Pinsir Sash" },
    { key: 1114, value: "Rushing Bow" },
    { key: 1115, value: "Magikarp Bow" },
    { key: 1116, value: "Tempest Sash" },
    { key: 1117, value: "Ditto Torc" },
    { key: 1118, value: "AI Brooch" },
    { key: 1119, value: "Spike Brooch" },
    { key: 1120, value: "Aged Scarf" },
    { key: 1121, value: "Kabuto Hat" },
    { key: 1122, value: "Kabu-Torc" },
    { key: 1123, value: "Old Brooch" },
    { key: 1124, value: "Dragon Sash" },
    { key: 1125, value: "Aloft Mantle" },
    { key: 1126, value: "Mirage Cape" },
    { key: 1127, value: "Sentret Ruff" },
    { key: 1128, value: "Body Collar" },
    { key: 1129, value: "Expose Specs" },
    { key: 1130, value: "Noctowl Torc" },
    { key: 1131, value: "Morning Bow" },
    { key: 1132, value: "Ledian Bow" },
    { key: 1133, value: "Spina-Scarf" },
    { key: 1134, value: "Ariados Bow" },
    { key: 1135, value: "Slash Bow" },
    { key: 1136, value: "Shine Torc" },
    { key: 1137, value: "Lanturn Bow" },
    { key: 1138, value: "Lively Scarf" },
    { key: 1139, value: "Xatu Bow" },
    { key: 1140, value: "Wool Bow" },
    { key: 1141, value: "Fluffy Scarf" },
    { key: 1142, value: "Sacred Scarf" },
    { key: 1143, value: "Bright Tiara" },
    { key: 1144, value: "Rain Crown" },
    { key: 1145, value: "Zephyr Bow" },
    { key: 1146, value: "Skip-Scarf" },
    { key: 1147, value: "Cotton Torc" },
    { key: 1148, value: "Revenge Ruff" },
    { key: 1149, value: "Hasty Bow" },
    { key: 1150, value: "Sun Scarf" },
    { key: 1151, value: "Chitin Bow" },
    { key: 1152, value: "Wooper Bow" },
    { key: 1153, value: "Quag-Torc" },
    { key: 1154, value: "Murkrow Hat" },
    { key: 1155, value: "King Cap" },
    { key: 1156, value: "Misdrea-Cape" },
    { key: 1157, value: "Cryptic Sash" },
    { key: 1158, value: "Reverse Bow" },
    { key: 1159, value: "Robust Bow" },
    { key: 1160, value: "Dense Poncho" },
    { key: 1161, value: "Escape Scarf" },
    { key: 1162, value: "Takeoff Ruff" },
    { key: 1163, value: "Quartz Torc" },
    { key: 1164, value: "Snub-Cape" },
    { key: 1165, value: "Stern Sash" },
    { key: 1166, value: "Qwilfish Bow" },
    { key: 1167, value: "Shuckle Bow" },
    { key: 1168, value: "Horn Torc" },
    { key: 1169, value: "Lava Bow" },
    { key: 1170, value: "Torrid Scarf" },
    { key: 1171, value: "Frigid Bow" },
    { key: 1172, value: "Frost Torc" },
    { key: 1173, value: "Eager Brooch" },
    { key: 1174, value: "Reach Bow" },
    { key: 1175, value: "Psy Bow" },
    { key: 1176, value: "Snow Brooch" },
    { key: 1177, value: "Skar-Cape" },
    { key: 1178, value: "Dark Choker" },
    { key: 1179, value: "Pit Fang" },
    { key: 1180, value: "Tornado Bow" },
    { key: 1181, value: "Virtual Bow" },
    { key: 1182, value: "Delusion Bow" },
    { key: 1183, value: "Paint Scarf" },
    { key: 1184, value: "Milky Scarf" },
    { key: 1185, value: "Larvitar Bow" },
    { key: 1186, value: "Pupita-Scarf" },
    { key: 1187, value: "Crash Claw" },
    { key: 1188, value: "Pooch-Collar" },
    { key: 1189, value: "Dark Fang" },
    { key: 1190, value: "Merry Scarf" },
    { key: 1191, value: "Linoone Ruff" },
    { key: 1192, value: "Wurmple Bow" },
    { key: 1193, value: "Tough Scarf" },
    { key: 1194, value: "Vivid Silk" },
    { key: 1195, value: "Guard Bow" },
    { key: 1196, value: "Dustox Bow" },
    { key: 1197, value: "Kelp Hat" },
    { key: 1198, value: "Jolly Scarf" },
    { key: 1199, value: "Ludicolo Hat" },
    { key: 1200, value: "Seedot Hat" },
    { key: 1201, value: "Nuzleaf Bow" },
    { key: 1202, value: "Shiftry Belt" },
    { key: 1203, value: "Taillow Bow" },
    { key: 1204, value: "Midair Scarf" },
    { key: 1205, value: "Wingull Bow" },
    { key: 1206, value: "Stock Scarf" },
    { key: 1207, value: "Sensing Hat" },
    { key: 1208, value: "Magical Bow" },
    { key: 1209, value: "Caring Scarf" },
    { key: 1210, value: "Bliss Scarf" },
    { key: 1211, value: "Blocking Bow" },
    { key: 1212, value: "Mobile Bow" },
    { key: 1213, value: "Thwart Bow" },
    { key: 1214, value: "Slak-Scarf" },
    { key: 1215, value: "Vigor Sash" },
    { key: 1216, value: "Lazy Ruff" },
    { key: 1217, value: "Novice Scarf" },
    { key: 1218, value: "Ninja Ruff" },
    { key: 1219, value: "Awe Mantle" },
    { key: 1220, value: "Good Earring" },
    { key: 1221, value: "Nice Bangle" },
    { key: 1222, value: "Great Torc" },
    { key: 1223, value: "Makuhit-Belt" },
    { key: 1224, value: "Thrust Belt" },
    { key: 1225, value: "Nose-Torc" },
    { key: 1226, value: "Sable-Scope" },
    { key: 1227, value: "Deceit Mask" },
    { key: 1228, value: "Iron Torc" },
    { key: 1229, value: "Metal Bangle" },
    { key: 1230, value: "Iron Helmet" },
    { key: 1231, value: "Intuit Bow" },
    { key: 1232, value: "Ponder Sash" },
    { key: 1233, value: "Punish Torc" },
    { key: 1234, value: "Protect Mask" },
    { key: 1235, value: "Neon Scarf" },
    { key: 1236, value: "Evening Bow" },
    { key: 1237, value: "Thorned Torc" },
    { key: 1238, value: "Gulpin Bow" },
    { key: 1239, value: "Swalot Belt" },
    { key: 1240, value: "Carva-Sash" },
    { key: 1241, value: "Vicious Bow" },
    { key: 1242, value: "Spout Scarf" },
    { key: 1243, value: "Huge Bow" },
    { key: 1244, value: "Numel Bow" },
    { key: 1245, value: "Erupt Scarf" },
    { key: 1246, value: "Sooty Sash" },
    { key: 1247, value: "Spring Bow" },
    { key: 1248, value: "Scheme Scarf" },
    { key: 1249, value: "Hula Bow" },
    { key: 1250, value: "Desert Bow" },
    { key: 1251, value: "Vibra Scarf" },
    { key: 1252, value: "Red Glasses" },
    { key: 1253, value: "Desert Sash" },
    { key: 1254, value: "Cacturne Hat" },
    { key: 1255, value: "Tuft Bow" },
    { key: 1256, value: "Cloud Ruff" },
    { key: 1257, value: "Strong Sash" },
    { key: 1258, value: "Seviper Bow" },
    { key: 1259, value: "Lunaton-Torc" },
    { key: 1260, value: "Solrock Bow" },
    { key: 1261, value: "Soak Scarf" },
    { key: 1262, value: "Whiscash Bow" },
    { key: 1263, value: "Bossy Scarf" },
    { key: 1264, value: "Cower Sash" },
    { key: 1265, value: "Bal-Brooch" },
    { key: 1266, value: "Claydol Torc" },
    { key: 1267, value: "Bind Scarf" },
    { key: 1268, value: "Cradily Bow" },
    { key: 1269, value: "Guard Claw" },
    { key: 1270, value: "Rigid Cape" },
    { key: 1271, value: "Admire Scarf" },
    { key: 1272, value: "Grace Scarf" },
    { key: 1273, value: "Kecleon Torc" },
    { key: 1274, value: "Shuppet Cape" },
    { key: 1275, value: "Ominous Torc" },
    { key: 1276, value: "Duskull Ruff" },
    { key: 1277, value: "Illusion Bow" },
    { key: 1278, value: "Tropius Bow" },
    { key: 1279, value: "Chime-Scarf" },
    { key: 1280, value: "Perish Torc" },
    { key: 1281, value: "Chilly Hat" },
    { key: 1282, value: "Hail Scarf" },
    { key: 1283, value: "Sleet Bow" },
    { key: 1284, value: "Safe Scarf" },
    { key: 1285, value: "Walrein Torc" },
    { key: 1286, value: "Clam-Brooch" },
    { key: 1287, value: "Deep Torc" },
    { key: 1288, value: "Gore-Scarf" },
    { key: 1289, value: "Reli-Torc" },
    { key: 1290, value: "Luvdisc Torc" },
    { key: 1291, value: "Crag Helmet" },
    { key: 1292, value: "Outlast Bow" },
    { key: 1293, value: "Sala-Cape" },
    { key: 1294, value: "Beldum Torc" },
    { key: 1295, value: "Metang Scarf" },
    { key: 1296, value: "Meta-Torc" },
    { key: 1297, value: "Starly Bow" },
    { key: 1298, value: "Regret Torc" },
    { key: 1299, value: "Guts Sash" },
    { key: 1300, value: "Still Bow" },
    { key: 1301, value: "Kricke-Torc" },
    { key: 1302, value: "Budew Scarf" },
    { key: 1303, value: "Bouquet Cape" },
    { key: 1304, value: "Hard Helmet" },
    { key: 1305, value: "Skull Helmet" },
    { key: 1306, value: "Rebound Bow" },
    { key: 1307, value: "Block Brooch" },
    { key: 1308, value: "Straw Cape" },
    { key: 1309, value: "Worma-Bow" },
    { key: 1310, value: "Mothim Bow" },
    { key: 1311, value: "Nectar Bow" },
    { key: 1312, value: "Vespi-Torc" },
    { key: 1313, value: "Awake Bow" },
    { key: 1314, value: "Gastro-Torc" },
    { key: 1315, value: "Ambipom Bow" },
    { key: 1316, value: "Defrost Ruff" },
    { key: 1317, value: "Allure Coat" },
    { key: 1318, value: "Magic Hat" },
    { key: 1319, value: "Honch-Cape" },
    { key: 1320, value: "Glameow Bow" },
    { key: 1321, value: "Scary Belt" },
    { key: 1322, value: "Ching-Torc" },
    { key: 1323, value: "Stinky Scarf" },
    { key: 1324, value: "Stench Sash" },
    { key: 1325, value: "Image Brooch" },
    { key: 1326, value: "Mirror Torc" },
    { key: 1327, value: "Chatot Scarf" },
    { key: 1328, value: "Thick Scarf" },
    { key: 1329, value: "Grit Veil" },
    { key: 1330, value: "Skorupi Bow" },
    { key: 1331, value: "Dust Scarf" },
    { key: 1332, value: "Croa-Torc" },
    { key: 1333, value: "Toxi-Belt" },
    { key: 1334, value: "Carni-Bow" },
    { key: 1335, value: "Swim Bow" },
    { key: 1336, value: "Lumi-Torc" },
    { key: 1337, value: "Snowy Torc" },
    { key: 1338, value: "Frozen Cape" },
    { key: 1339, value: "Builder Sash" },
    { key: 1340, value: "Flabby Belt" },
    { key: 1341, value: "Rhyperi-Torc" },
    { key: 1342, value: "Clinging Bow" },
    { key: 1343, value: "Yanmega Bow" },
    { key: 1344, value: "Gliscor Cape" },
    { key: 1345, value: "Glacier Cape" },
    { key: 1346, value: "Best Scarf" },
    { key: 1347, value: "Gallant Torc" },
    { key: 1348, value: "Probo-Hat" },
    { key: 1349, value: "Unlucky Sash" },
    { key: 1350, value: "Froslass Bow" },
    { key: 1351, value: "Purify Veil" }
  ];