export const getSpawnsPlaceholder = [
    { dex: 1, species: 'Bulbasaur', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 2, species: 'Ivysaur', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 3, species: 'Venusaur', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 4, species: 'Charmander', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 5, species: 'Charmeleon', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 6, species: 'Charizard', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 7, species: 'Squirtle', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 8, species: 'Wartortle', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 9, species: 'Blastoise', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 10, species: 'Caterpie', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 11, species: 'Metapod', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 12, species: 'Butterfree', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 13, species: 'Weedle', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 14, species: 'Kakuna', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 15, species: 'Beedrill', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 16, species: 'Pidgey', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 17, species: 'Pidgeotto', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 18, species: 'Pidgeot', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 19, species: 'Rattata', form: 'alolan', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 10012, species: 'Cococute', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 10013, species: 'Cocoareca', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
    { dex: 10014, species: 'Cocolada', form: 'base', palette: 'none', rarity: 0, percentage: 5 },
]