import { z } from "zod"

/**
 * RandomizerSettings schema — generated from FVX v1.6.1 settings-fields.json.
 * 187 fields mapping the proven FVX shim contract (sample-settings.roundtrip.json).
 *
 * This schema is the source of truth for web↔API serialization: it ensures that
 * settings edited in the web UI encode back to byte-perfect `.rnqs` files.
 * Must be regenerated on FVX version upgrades if the field set changes.
 */

// Structured complex types
const GenRestrictions = z.object({
  gens: z.array(z.number().int()),
  allowEvolutionaryRelatives: z.boolean(),
}).strict()

const BattleStyle = z.object({
  modification: z.enum(["UNCHANGED", "RANDOM", "SINGLE_STYLE"]),
  style: z.enum(["SINGLE_BATTLE", "DOUBLE_BATTLE", "TRIPLE_BATTLE", "ROTATION_BATTLE"]),
}).strict()

export const RandomizerSettings = z.object({
  abilitiesFollowEvolutions: z.boolean(),
  abilitiesFollowMegaEvolutions: z.boolean(),
  abilitiesMod: z.enum(["UNCHANGED", "RANDOMIZE"]),
  addCheapRareCandiesToShops: z.boolean(),
  additionalBossTrainerPokemon: z.number().int(),
  additionalImportantTrainerPokemon: z.number().int(),
  additionalRegularTrainerPokemon: z.number().int(),
  adjustEvolutionLevels: z.boolean(),
  allowStarterAltFormes: z.boolean(),
  allowStaticAltFormes: z.boolean(),
  allowTotemAltFormes: z.boolean(),
  allowTrainerAlternateFormes: z.boolean(),
  allowWildAltFormes: z.boolean(),
  allowWonderGuard: z.boolean(),
  allyPokemonMod: z.enum(["UNCHANGED", "RANDOM", "SIMILAR_STRENGTH"]),
  assignEvoStatsRandomly: z.boolean(),
  auraMod: z.enum(["UNCHANGED", "RANDOM", "SAME_STRENGTH"]),
  balanceShakingGrass: z.boolean(),
  balanceShopPrices: z.boolean(),
  banBadAbilities: z.boolean(),
  banBadRandomFieldItems: z.boolean(),
  banBadRandomPickupItems: z.boolean(),
  banBadRandomShopItems: z.boolean(),
  banBadRandomStarterHeldItems: z.boolean(),
  banBadRandomWildPokemonHeldItems: z.boolean(),
  banIrregularAltFormes: z.boolean(),
  banNegativeAbilities: z.boolean(),
  banOPShopItems: z.boolean(),
  banPrematureEvos: z.boolean(),
  banRegularShopItems: z.boolean(),
  banTrappingAbilities: z.boolean(),
  baseStatisticsMod: z.enum(["UNCHANGED", "SHUFFLE", "RANDOM"]),
  baseStatsFollowEvolutions: z.boolean(),
  baseStatsFollowMegaEvolutions: z.boolean(),
  betterBossTrainerMovesets: z.boolean(),
  betterImportantTrainerMovesets: z.boolean(),
  betterRegularTrainerMovesets: z.boolean(),
  blockBrokenMovesetMoves: z.boolean(),
  blockBrokenTMMoves: z.boolean(),
  blockBrokenTutorMoves: z.boolean(),
  blockWildLegendaries: z.boolean(),
  bstBuffNerfMaxPercentage: z.number().int(),
  bstFollowEvolutions: z.boolean(),
  bstMod: z.enum(["UNCHANGED", "RANDOM_BUFF_NERF", "SHUFFLE", "RANDOM"]),
  bstShuffleSwapLegendaries: z.boolean(),
  catchEmAllEncounters: z.boolean(),
  changeImpossibleEvolutions: z.boolean(),
  consumableItemsOnlyForTrainerPokemon: z.boolean(),
  correctStaticMusic: z.boolean(),
  currentMiscTweaks: z.number().int(),
  currentRestrictions: GenRestrictions,
  customStarters: z.array(z.number().int()),
  diverseTypesForBossTrainers: z.boolean(),
  diverseTypesForImportantTrainers: z.boolean(),
  diverseTypesForRegularTrainers: z.boolean(),
  dualTypeOnly: z.boolean(),
  eliteFourUniquePokemonNumber: z.number().int(),
  ensureTwoAbilities: z.boolean(),
  estimateLevelForEvolutionImprovements: z.boolean(),
  evolutionMovesForAll: z.boolean(),
  evolutionsMod: z.enum(["UNCHANGED", "RANDOM", "RANDOM_EVERY_LEVEL"]),
  evosAllowAltFormes: z.boolean(),
  evosForceChange: z.boolean(),
  evosForceGrowth: z.boolean(),
  evosMaxThreeStages: z.boolean(),
  evosNoConvergence: z.boolean(),
  evosSameTyping: z.boolean(),
  evosSimilarStrength: z.boolean(),
  expCurveMod: z.enum(["LEGENDARIES", "STRONG_LEGENDARIES", "ALL"]),
  fieldItemsMod: z.enum(["UNCHANGED", "SHUFFLE", "RANDOM", "RANDOM_EVEN"]),
  fullHMCompat: z.boolean(),
  guaranteeEvolutionItems: z.boolean(),
  guaranteeXItems: z.boolean(),
  guaranteedMoveCount: z.number().int(),
  highestLevelOnlyGetsItemsForTrainerPokemon: z.boolean(),
  inGameTradesMod: z.enum(["UNCHANGED", "RANDOMIZE_GIVEN", "RANDOMIZE_GIVEN_AND_REQUESTED"]),
  inverseTypesRandomImmunities: z.boolean(),
  keepFieldMoveTMs: z.boolean(),
  keepFieldMoveTutors: z.boolean(),
  keepWildEvolutionFamilies: z.boolean(),
  keepWildTypeThemes: z.boolean(),
  limit600: z.boolean(),
  limitMainGameLegendaries: z.boolean(),
  limitPokemon: z.boolean(),
  makeEvolutionsEasier: z.boolean(),
  makeEvolutionsEasierLvl: z.number().int(),
  minimumCatchRateLevel: z.number().int(),
  moveTutorMovesMod: z.enum(["UNCHANGED", "RANDOM"]),
  moveTutorsCompatibilityMod: z.enum(["UNCHANGED", "RANDOM_PREFER_TYPE", "COMPLETELY_RANDOM", "FULL"]),
  movesetsForceGoodDamaging: z.boolean(),
  movesetsGoodDamagingPercent: z.number().int(),
  movesetsMod: z.enum(["UNCHANGED", "RANDOM_PREFER_SAME_TYPE", "COMPLETELY_RANDOM", "METRONOME_ONLY"]),
  pickupItemsMod: z.enum(["UNCHANGED", "RANDOM"]),
  pokemonPalettesFollowEvolutions: z.boolean(),
  pokemonPalettesFollowTypes: z.boolean(),
  pokemonPalettesMod: z.enum(["UNCHANGED", "RANDOM"]),
  pokemonPalettesShinyFromNormal: z.boolean(),
  raceMode: z.boolean(),
  randomizeHeldItemsForBossTrainerPokemon: z.boolean(),
  randomizeHeldItemsForImportantTrainerPokemon: z.boolean(),
  randomizeHeldItemsForRegularTrainerPokemon: z.boolean(),
  randomizeInGameTradesIVs: z.boolean(),
  randomizeInGameTradesItems: z.boolean(),
  randomizeInGameTradesNicknames: z.boolean(),
  randomizeInGameTradesOTs: z.boolean(),
  randomizeIntroMon: z.boolean(),
  randomizeMoveAccuracies: z.boolean(),
  randomizeMoveCategory: z.boolean(),
  randomizeMoveNames: z.boolean(),
  randomizeMovePPs: z.boolean(),
  randomizeMovePowers: z.boolean(),
  randomizeMoveTypes: z.boolean(),
  randomizeStartersHeldItems: z.boolean(),
  randomizeTotemHeldItems: z.boolean(),
  randomizeTrainerClassNames: z.boolean(),
  randomizeTrainerNames: z.boolean(),
  randomizeWildPokemon: z.boolean(),
  randomizeWildPokemonHeldItems: z.boolean(),
  removeTimeBasedEvolutions: z.boolean(),
  reorderDamagingMoves: z.boolean(),
  rivalCarriesStarterThroughout: z.boolean(),
  romName: z.string(),
  selectedEXPCurve: z.enum(["SLOW", "MEDIUM_SLOW", "MEDIUM_FAST", "FAST", "ERRATIC", "FLUCTUATING"]),
  sensibleItemsOnlyForTrainerPokemon: z.boolean(),
  settingBattleStyle: BattleStyle,
  shinyChance: z.boolean(),
  shopItemsMod: z.enum(["UNCHANGED", "SHUFFLE", "RANDOM"]),
  similarStrengthEncounters: z.boolean(),
  speciesTypesMod: z.enum(["UNCHANGED", "RANDOM_FOLLOW_EVOLUTIONS", "COMPLETELY_RANDOM"]),
  splitWildZoneByEncounterTypes: z.boolean(),
  standardizeEXPCurves: z.boolean(),
  startWithGuaranteedMoves: z.boolean(),
  startersBSTMaximum: z.number().int(),
  startersBSTMinimum: z.number().int(),
  startersMod: z.enum(["UNCHANGED", "CUSTOM", "COMPLETELY_RANDOM", "RANDOM_WITH_TWO_EVOLUTIONS", "RANDOM_BASIC"]),
  startersNoDualTypes: z.boolean(),
  startersNoLegendaries: z.boolean(),
  startersSingleType: z.enum(["NORMAL", "FIGHTING", "FLYING", "GRASS", "WATER", "FIRE", "ROCK", "GROUND", "PSYCHIC", "BUG", "DRAGON", "ELECTRIC", "GHOST", "POISON", "ICE", "STEEL", "DARK", "FAIRY"]).nullable(),
  startersTypeMod: z.enum(["NONE", "FIRE_WATER_GRASS", "TRIANGLE", "UNIQUE", "SINGLE_TYPE"]),
  staticLevelModified: z.boolean(),
  staticLevelModifier: z.number().int(),
  staticPokemonMod: z.enum(["UNCHANGED", "RANDOM_MATCHING", "COMPLETELY_RANDOM", "SIMILAR_STRENGTH"]),
  swapStaticMegaEvos: z.boolean(),
  swapTrainerMegaEvos: z.boolean(),
  tmLevelUpMoveSanity: z.boolean(),
  tmsFollowEvolutions: z.boolean(),
  tmsForceGoodDamaging: z.boolean(),
  tmsGoodDamagingPercent: z.number().int(),
  tmsHmsCompatibilityMod: z.enum(["UNCHANGED", "RANDOM_PREFER_TYPE", "COMPLETELY_RANDOM", "FULL"]),
  tmsMod: z.enum(["UNCHANGED", "RANDOM"]),
  totemLevelModifier: z.number().int(),
  totemLevelsModified: z.boolean(),
  totemPokemonMod: z.enum(["UNCHANGED", "RANDOM", "SIMILAR_STRENGTH"]),
  trainersAvoidDuplicates: z.boolean(),
  trainersBlockEarlyWonderGuard: z.boolean(),
  trainersBlockLegendaries: z.boolean(),
  trainersEnforceDistribution: z.boolean(),
  trainersEnforceMainPlaythrough: z.boolean(),
  trainersEvolutionLevelModifier: z.number().int(),
  trainersEvolveTheirPokemon: z.boolean(),
  trainersLevelModified: z.boolean(),
  trainersLevelModifier: z.number().int(),
  trainersMatchTypingDistribution: z.boolean(),
  trainersMod: z.enum(["UNCHANGED", "RANDOM", "DISTRIBUTED", "MAINPLAYTHROUGH", "TYPE_THEMED", "TYPE_THEMED_ELITE4_GYMS", "KEEP_THEMED", "KEEP_THEME_OR_PRIMARY"]),
  trainersUseLocalPokemon: z.boolean(),
  trainersUsePokemonOfSimilarStrength: z.boolean(),
  tutorFollowEvolutions: z.boolean(),
  tutorLevelUpMoveSanity: z.boolean(),
  tutorsForceGoodDamaging: z.boolean(),
  tutorsGoodDamagingPercent: z.number().int(),
  typeEffectivenessMod: z.enum(["UNCHANGED", "RANDOM", "RANDOM_BALANCED", "KEEP_IDENTITIES", "INVERSE"]),
  typesFollowMegaEvolutions: z.boolean(),
  updateBaseStats: z.boolean(),
  updateBaseStatsToGeneration: z.number().int(),
  updateMoves: z.boolean(),
  updateMovesLegacy: z.boolean(),
  updateMovesToGeneration: z.number().int(),
  updateTypeEffectiveness: z.boolean(),
  updatedFromOldVersion: z.boolean(),
  useMinimumCatchRate: z.boolean(),
  useTimeBasedEncounters: z.boolean(),
  weighDuplicateAbilitiesTogether: z.boolean(),
  wildLevelModifier: z.number().int(),
  wildLevelsModified: z.boolean(),
  wildPokemonEvolutionMod: z.enum(["NONE", "BASIC_ONLY", "KEEP_STAGE"]),
  wildPokemonTypeMod: z.enum(["NONE", "RANDOM_THEMES", "KEEP_PRIMARY"]),
  wildPokemonZoneMod: z.enum(["NONE", "ENCOUNTER_SET", "MAP", "NAMED_LOCATION", "GAME"]),
}).strict()

export type RandomizerSettings = z.infer<typeof RandomizerSettings>
