import type { ComponentProps } from "react";
import { makeIconComponent } from "@/components/smartrotom/behavior/makeIconComponent";
import {
  Search,
  Plus,
  CirclePlus,
  File,
  FileText,
  Folder,
  FolderOpen,
  Hash,
  Tag,
  Pin,
  Star,
  Share2,
  MoreHorizontal,
  MoreVertical,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  X,
  Check,
  Clock,
  History,
  Link2,
  Columns2,
  Sun,
  Moon,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  List,
  ListOrdered,
  ListChecks,
  Quote,
  Code,
  SquareCode,
  Table,
  Heading1,
  Heading2,
  Type,
  Undo2,
  Redo2,
  Trash2,
  Settings,
  Bell,
  Zap,
  Sparkles,
  Copy,
  Download,
  Globe,
  Lock,
  Menu,
  ArrowUpDown,
  Inbox,
  Save,
  Dot,
  Layers,
  Palette,
  Network,
  Pencil,
  type LucideIcon,
} from "lucide-react";

/** Lucide-react placeholders standing in for the hand-drawn path map this replaced. */
const MAP = {
  search: Search,
  plus: Plus,
  "plus-circle": CirclePlus,
  file: File,
  "file-text": FileText,
  folder: Folder,
  "folder-open": FolderOpen,
  hash: Hash,
  tag: Tag,
  pin: Pin,
  star: Star,
  share: Share2,
  more: MoreHorizontal,
  "more-v": MoreVertical,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  x: X,
  check: Check,
  clock: Clock,
  history: History,
  link: Link2,
  split: Columns2,
  sun: Sun,
  moon: Moon,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strike: Strikethrough,
  list: List,
  "list-ordered": ListOrdered,
  "list-check": ListChecks,
  quote: Quote,
  code: Code,
  "code-block": SquareCode,
  table: Table,
  "h-1": Heading1,
  "h-2": Heading2,
  type: Type,
  undo: Undo2,
  redo: Redo2,
  trash: Trash2,
  settings: Settings,
  bell: Bell,
  zap: Zap,
  sparkles: Sparkles,
  copy: Copy,
  download: Download,
  globe: Globe,
  lock: Lock,
  menu: Menu,
  sort: ArrowUpDown,
  inbox: Inbox,
  save: Save,
  dot: Dot,
  layers: Layers,
  swatch: Palette,
  network: Network,
  pencil: Pencil,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof MAP;

export const Icon = makeIconComponent(MAP, { size: 18, strokeWidth: 1.75 });

export type IconProps = ComponentProps<typeof Icon>;
