export { Icon } from "./icon"
export { BoffButton } from "./button"
export { BoffCard } from "./card"
export { BoffBadge } from "./badge"
export { BoffInput } from "./input"
export { BoffSwitch } from "./switch"
export { BoffCheckbox } from "./checkbox"
export { BoffSlider } from "./slider"
export { BoffProgress, BoffRing } from "./progress"
export { BoffAvatar, BoffAvatarGroup } from "./avatar"
export { BoffSkeleton } from "./skeleton"
export { BoffTabs } from "./tabs"
export { BoffTooltip } from "./tooltip"
export { BoffModal } from "./dialog"
export { BoffPopover } from "./popover"
export { BoffAlert } from "./alert"
export { Kicker } from "./kicker"
export { Tag } from "./tag"
export { Callout } from "./callout"
export { ToastProvider, useToast } from "./toast-provider"
export { Field } from "./field"
export { SearchInput } from "./search-input"
export { Segmented } from "./segmented"
export { Breadcrumb } from "./breadcrumb"
export { Pagination } from "./pagination"
export { IconBox } from "./icon-box"
export { Stat } from "./stat"
export { CodeBlock } from "./code-block"
export { EmptyState } from "./empty-state"
export { RadioGroup } from "./radio-group"
export { ToolPanel } from "./tool-panel"
export { ToolStatBars } from "./tool-stat-bars"
export { ToolApp } from "./tool-app"
export { SegTabs } from "./seg-tabs"
export { ToolSelect } from "./tool-select"
export { ToolTable } from "./tool-table"
export { CopyButton } from "./copy-button"
export { Picker } from "./picker"
export { HpBar } from "./hp-bar"
export { ResultBadge } from "./result-badge"
export { StatTile } from "./stat-tile"
export { SplitBar } from "./split-bar"
export { TrendChart } from "./trend-chart"
export { HeatGrid } from "./heat-grid"
export { TagPills } from "./tag-pills"
export { DocTOC } from "./doc-toc"
export type { DocTOCItem } from "./doc-toc"
export { BoffSpinner } from "./spinner"
export { BoffActionBar } from "./action-bar"
export { GamePanel } from "./game-panel"
export { TYPES, tyVar, effMult, effLabel, hpColor, aniF, aniB } from "./bs-data"

// BSX (Battlesim v2) — the v2 BSX/BS render primitives were retired in the v3
// BattleSim migration (Phase E); only the data/types the sim engine still uses remain.
export { MOVESETS, MON_DATA, freshMon, calcRange, koLabel, speedOrder } from "./bsx-data"
export type { BSXMon } from "./bsx-data"

