import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'fs';
import { join } from 'path';

import { escape as escapeSql } from 'mysql2';

import { HOUSE_ACCOUNTS } from '../api/smartrotom/starbank/house-accounts';
import { AccountType } from '../api/smartrotom/starbank/enums/account-type.enum';
import { CATEGORIES } from './forum-categories';
import { GOB_ROLES, TASAS } from './gobierno';
import { REWARDS } from './mine-rewards';
import {
  CATEGORY_WEIGHTS,
  DEFAULT_POINTS,
  DEFAULT_TIER,
  SEASON_DAYS,
  SEASON_NAME,
  SEASON_NUMBER,
} from './pasaporte';

/**
 * Emits the static half of the bootstrap as plain SQL, for operators who would rather
 * run `mysql < file` than a Node process against production.
 *
 * It generates from the seed modules' own exported constants — never from a seeded
 * database. A `mysqldump` would be easier and is the wrong tool twice over: it bakes
 * AUTO_INCREMENT ids into the file (code that assumes a house-account id is exactly the
 * bug this repo has already paid for once), and it captures the admin's bcrypt hash into
 * a tracked file.
 *
 * COVERS ALL SIX STEPS, so a bootstrap needs no Node process on the server. The two that
 * do not translate cleanly are called out where they are built:
 *   - `00-admin`   bcrypt is not a MySQL builtin, so the password hash is an operator-supplied
 *                  SET at the top of the file, guarded so an unedited file inserts no admin.
 *   - `06-rooker`  the handle dedupe is a loop in TS and a window function here; identical
 *                  whenever sanitised names do not collide, which includes every fresh DB.
 *
 *   pnpm run seed:sql          rewrite drizzle/seed/
 *   pnpm run check:seed-sql    fail if the checked-in SQL is stale (CI)
 */

const OUT_DIR = join(__dirname, '..', '..', 'drizzle', 'seed');

/**
 * Every literal goes through mysql2's own escaper rather than hand-rolled quoting —
 * mysql2 is already a runtime dependency, so this adds nothing to install.
 */
const q = (value: string | number | boolean | null): string => escapeSql(value);

function header(title: string, source: string): string {
  return [
    `-- ${title}`,
    '--',
    `-- GENERATED by src/seed/generate-sql.ts from ${source} — do not edit by hand.`,
    '-- Regenerate with `pnpm run seed:sql`; `pnpm run check:seed-sql` fails on drift.',
    '--',
    '-- Idempotent: re-running changes nothing that is already correct.',
    '',
  ].join('\n');
}

/**
 * The house accounts. Resolution is by TYPE alone for the singletons — deliberately not
 * `ON DUPLICATE KEY UPDATE` on the (type, name) unique index, which would miss an account
 * somebody renamed and mint a second treasury beside it. SERVICE is one row per service,
 * so it alone matches on (type, name). Mirrors findExisting() in seed/house-accounts.ts.
 */
function houseAccounts(): string {
  const rows = HOUSE_ACCOUNTS.map((account) => {
    const guard =
      account.type === AccountType.SERVICE
        ? `type = ${q(account.type)} AND name = ${q(account.name)}`
        : `type = ${q(account.type)}`;
    return [
      `-- ${account.name} (${account.type}) — ${account.description}`,
      'INSERT INTO rotom_starbank_accounts (name, balance, type)',
      `SELECT ${q(account.name)}, 0, ${q(account.type)} FROM DUAL`,
      `WHERE NOT EXISTS (SELECT 1 FROM rotom_starbank_accounts WHERE ${guard});`,
    ].join('\n');
  });

  return (
    header('StarBank house accounts', 'starbank/house-accounts.ts') +
    '\n-- Balances are never touched, only existence: this file cannot move money.\n\n' +
    rows.join('\n\n') +
    '\n'
  );
}

/** Upsert by slug — the table's unique index, so ON DUPLICATE KEY UPDATE is exact here. */
function forumCategories(): string {
  const rows = CATEGORIES.map(
    (c) =>
      'INSERT INTO boffmedia_forum_categories\n' +
      '  (slug, name, description, icon, hue, locked, position)\n' +
      `VALUES (${q(c.slug)}, ${q(c.name)}, ${q(c.description)}, ${q(c.icon)}, ${q(c.hue)}, ${q(c.locked)}, ${q(c.position)})\n` +
      'ON DUPLICATE KEY UPDATE\n' +
      '  name = VALUES(name), description = VALUES(description), icon = VALUES(icon),\n' +
      '  hue = VALUES(hue), locked = VALUES(locked), position = VALUES(position);',
  );

  return (
    header('Forum categories', 'seed/forum-categories.ts') +
    '\n-- Re-running syncs label/icon/hue/position edits without duplicating rows.\n\n' +
    rows.join('\n\n') +
    '\n'
  );
}

/**
 * Roles + the tasas rate card. The TS seed also calls seedHouseAccounts() here for
 * convenience; in SQL those live in 01-house-accounts.sql so each file has one subject.
 * Run 01 first — nothing below depends on it, but the bootstrap order should not change
 * meaning depending on which file an operator happens to run.
 */
function gobierno(): string {
  const roles = GOB_ROLES.map(
    (name) =>
      `INSERT INTO boffmedia_roles (name) VALUES (${q(name)})\n` +
      'ON DUPLICATE KEY UPDATE name = name;',
  );

  // `active` is set on insert but never on update — a tasa switched off by hand stays off.
  const tasas = TASAS.map(
    (t) =>
      'INSERT INTO rotom_gobierno_tasas (code, concept, kind, rate, amount, active)\n' +
      `VALUES (${q(t.code)}, ${q(t.concept)}, ${q(t.kind)}, ${q(t.rate)}, ${q(t.amount)}, 1)\n` +
      'ON DUPLICATE KEY UPDATE\n' +
      '  concept = VALUES(concept), kind = VALUES(kind),\n' +
      '  rate = VALUES(rate), amount = VALUES(amount);',
  );

  return (
    header('Gobierno: roles + tasas rate card', 'seed/gobierno.ts') +
    '\n-- House accounts are in 01-house-accounts.sql (the TS seed bundles them here).\n' +
    '\n-- ── Roles ──────────────────────────────────────────────────────────────────\n\n' +
    roles.join('\n\n') +
    '\n\n-- ── Tasas ──────────────────────────────────────────────────────────────────\n\n' +
    tasas.join('\n\n') +
    '\n'
  );
}

/**
 * The mine drop table. `rotom_mine_rewards` has no unique index on item_id — only the
 * surrogate id — so ON DUPLICATE KEY UPDATE has nothing to catch on and the TS seed does
 * a read-then-branch instead. The SQL equivalent is UPDATE-then-INSERT-if-missing, keyed
 * on item_id.
 *
 * Rows are never deleted: rotom_mine_game_rewards.reward_id references this table ON
 * DELETE CASCADE, so clearing it to re-seed would take every player's game history and
 * ranking score with it.
 */
function mineRewards(): string {
  const rows = REWARDS.map((r) =>
    [
      `-- ${r.name} (${r.type}) — ${r.value}, ${r.width}x${r.height}`,
      'UPDATE rotom_mine_rewards SET',
      `  name = ${q(r.name)}, type = ${q(r.type)}, value = ${q(r.value)},`,
      `  width = ${q(r.width)}, height = ${q(r.height)}`,
      `WHERE item_id = ${q(r.itemId)};`,
      'INSERT INTO rotom_mine_rewards (name, type, item_id, value, width, height)',
      `SELECT ${q(r.name)}, ${q(r.type)}, ${q(r.itemId)}, ${q(r.value)}, ${q(r.width)}, ${q(r.height)} FROM DUAL`,
      `WHERE NOT EXISTS (SELECT 1 FROM rotom_mine_rewards WHERE item_id = ${q(r.itemId)});`,
    ].join('\n'),
  );

  return (
    header(`Mine drop table (${REWARDS.length} rewards)`, 'seed/mine-rewards.ts') +
    '\n-- Never DELETE from this table: game history FKs to it ON DELETE CASCADE.\n\n' +
    rows.join('\n\n') +
    '\n'
  );
}

/**
 * The active cycle plus the achievement weight backfill.
 *
 * The season window is relative to when the seed runs, so the dates are NOW()-relative
 * expressions rather than literals — a generated file with a frozen timestamp would drift
 * further from correct every day it sat in git.
 */
function pasaporte(): string {
  const weights = Object.entries(CATEGORY_WEIGHTS)
    // "anything else → the default" is already the column default; the TS skips that write.
    .filter(
      ([, w]) => !(w.points === DEFAULT_POINTS && w.tier === DEFAULT_TIER),
    )
    .map(
      ([category, w]) =>
        `UPDATE rotom_achievements SET points = ${q(w.points)}, tier = ${q(w.tier)}\n` +
        `WHERE category = ${q(category)}\n` +
        `  AND points = ${q(DEFAULT_POINTS)} AND tier = ${q(DEFAULT_TIER)};`,
    );

  return (
    header('Pasaporte: active cycle + achievement weights', 'seed/pasaporte.ts') +
    '\n-- ── The active cycle ───────────────────────────────────────────────────────\n' +
    '-- Guarded on "is any season active", not on the number: a cycle already running is\n' +
    '-- left alone rather than replaced.\n\n' +
    'INSERT INTO rotom_pasaporte_seasons (number, name, starts_at, ends_at, active)\n' +
    `SELECT ${q(SEASON_NUMBER)}, ${q(SEASON_NAME)},\n` +
    `       DATE_SUB(NOW(), INTERVAL ${SEASON_DAYS} DAY),\n` +
    `       DATE_ADD(NOW(), INTERVAL ${SEASON_DAYS} DAY), 1 FROM DUAL\n` +
    'WHERE NOT EXISTS (SELECT 1 FROM rotom_pasaporte_seasons WHERE active = 1);\n' +
    '\n-- ── Achievement weights ────────────────────────────────────────────────────\n' +
    `-- Only rows still at the default (${DEFAULT_POINTS}, '${DEFAULT_TIER}') are touched, so a value\n` +
    '-- tuned by hand is never overwritten.\n\n' +
    weights.join('\n\n') +
    '\n'
  );
}

/**
 * Roles, the administrator, its role grants and the app registry — the rows everything
 * else FKs to. RUN THIS FIRST.
 *
 * The password is the one thing SQL cannot produce: bcrypt is a hash function, not a
 * MySQL builtin, so the operator generates the hash and pastes it into the SET at the
 * top. The guard `LIKE '$2%'` means an unedited file inserts nothing rather than
 * creating an administrator nobody can log in as — and the verification SELECT at the
 * bottom says so out loud.
 *
 * One deliberate divergence from seed/default.ts: that script grants the admin every role
 * that exists *at the moment it runs*, which under seed:system is exactly these two,
 * because gobierno's GOB_* roles are created later. Naming them explicitly gets the same
 * result without depending on the order these files are run in.
 */
function admin(): string {
  const ADMIN_UUID = '00000000-0000-0000-0000-000000000001';
  const ROLES = ['BOFF_ADMIN', 'ROTOM_ADMIN'];
  const APPS = ['ChatApp', 'StarBank', 'Pokedex'];

  return (
    header('Roles, administrator and app registry', 'seed/default.ts') +
    `
-- ═══ EDIT THESE TWO LINES ═══════════════════════════════════════════════════
--
-- bcrypt cannot be computed in SQL. Generate the hash on your own machine — the
-- password never leaves it, only the hash travels:
--
--   node -e "console.log(require('bcrypt').hashSync(process.argv[1],12))" 'your-password'
--   htpasswd -bnBC 12 "" 'your-password' | tr -d ':\\n'     # if you prefer no Node
--
-- Minimum 12 characters: seed/default.ts refuses shorter ones and this file is the
-- same administrator. Leave the placeholder and NOTHING is inserted — the guard below
-- is what stops an unusable admin row being created silently.

SET @ADMIN_PASSWORD_HASH := '__PASTE_BCRYPT_HASH_HERE__';
SET @ADMIN_EMAIL         := 'admin@boffmedia.es';

-- ═══════════════════════════════════════════════════════════════════════════

-- ── Roles ──────────────────────────────────────────────────────────────────

${ROLES.map(
  (name) =>
    `INSERT INTO boffmedia_roles (name) VALUES (${q(name)})\nON DUPLICATE KEY UPDATE name = name;`,
).join('\n\n')}

-- ── SmartRotom identity ────────────────────────────────────────────────────
-- Must precede boffmedia_users: that table's uuid is an FK to this one.

INSERT INTO rotom_users (uuid, username) VALUES (${q(ADMIN_UUID)}, 'admin')
ON DUPLICATE KEY UPDATE username = username;

-- ── The administrator ──────────────────────────────────────────────────────
-- An existing row wins: re-running must never reset a password changed since.

INSERT INTO boffmedia_users (username, password, email, uuid)
SELECT 'admin', @ADMIN_PASSWORD_HASH, @ADMIN_EMAIL, ${q(ADMIN_UUID)} FROM DUAL
WHERE @ADMIN_PASSWORD_HASH LIKE '$2%'
  AND NOT EXISTS (SELECT 1 FROM boffmedia_users WHERE username = 'admin');

-- ── Role grants ────────────────────────────────────────────────────────────

INSERT INTO boffmedia_user_roles (user_id, role_id)
SELECT u.id, r.id
FROM boffmedia_users u, boffmedia_roles r
WHERE u.username = 'admin'
  AND r.name IN (${ROLES.map(q).join(', ')})
  AND NOT EXISTS (
    SELECT 1 FROM boffmedia_user_roles ur
    WHERE ur.user_id = u.id AND ur.role_id = r.id
  );

-- ── App registry ───────────────────────────────────────────────────────────

${APPS.map(
  (name) =>
    `INSERT INTO rotom_apps (name, active) VALUES (${q(name)}, 1)\nON DUPLICATE KEY UPDATE name = name;`,
).join('\n\n')}

-- ── Verify ─────────────────────────────────────────────────────────────────
-- admin_user must be 1. If it is 0 you left the placeholder in the SET above.

SELECT
  (SELECT COUNT(*) FROM boffmedia_users WHERE username = 'admin') AS admin_user,
  (SELECT COUNT(*) FROM boffmedia_user_roles ur
     JOIN boffmedia_users u ON u.id = ur.user_id
    WHERE u.username = 'admin')                                  AS admin_roles,
  (SELECT COUNT(*) FROM rotom_apps)                              AS apps;
`
  );
}

/**
 * Rooker handles — one profile per rotom_users row that lacks one. RUN THIS LAST: it
 * reads the users every other step has created.
 *
 * seed/rooker.ts derives the handle procedurally (lowercase, replace anything outside
 * [a-z0-9_], truncate to 32, pad to 3, then dedupe collisions with a numeric suffix).
 * The first three map onto REGEXP_REPLACE/LEFT/RPAD exactly. The dedupe does not: it is
 * a loop over a growing set of taken names, so this uses ROW_NUMBER() instead, offset
 * past any handle already sharing the prefix.
 *
 * WHAT THAT MEANS IN PRACTICE. Identical to the TS whenever the sanitised names do not
 * collide — which includes every fresh bootstrap, where rotom_users holds only the
 * admin. When names DO collide, both produce valid unique handles but may pick different
 * suffix numbers; nothing depends on which number a colliding player got. The final
 * NOT EXISTS makes a duplicate impossible rather than merely unlikely, so the worst case
 * is a player left without a profile — which the verification query at the bottom
 * reports, and a second run then fixes.
 */
function rooker(): string {
  // Kept as one expression so LEFT/RPAD wrap it identically to baseHandle().
  const sanitised = "LOWER(REGEXP_REPLACE(r.username, '[^a-zA-Z0-9_]', '_'))";
  const truncated = `LEFT(${sanitised}, 32)`;

  return (
    header('Rooker profiles (derived)', 'seed/rooker.ts') +
    `
-- Run LAST — it derives one profile per existing rotom_users row.

INSERT INTO rotom_rooker_profiles (uuid, handle, display_name)
SELECT t.uuid, t.handle, t.username
FROM (
  SELECT
    s.uuid,
    s.username,
    CASE WHEN s.seq = 1 THEN s.base
         ELSE CONCAT(LEFT(s.base, 32 - CHAR_LENGTH(CAST(s.seq AS CHAR))), s.seq)
    END AS handle
  FROM (
    SELECT
      b.uuid,
      b.username,
      b.base,
      -- Offset past handles already sharing this prefix so a re-run climbs past
      -- whatever the previous run took, instead of colliding with it forever.
      ROW_NUMBER() OVER (PARTITION BY b.base ORDER BY b.uuid)
        + (SELECT COUNT(*) FROM rotom_rooker_profiles p
            WHERE p.handle = b.base OR p.handle LIKE CONCAT(b.base, '%')) AS seq
    FROM (
      SELECT
        r.uuid,
        r.username,
        -- baseHandle(): lowercase, non-[a-z0-9_] -> '_', cut to 32, pad up to 3.
        RPAD(${truncated}, GREATEST(CHAR_LENGTH(${truncated}), 3), '_') AS base
      FROM rotom_users r
      WHERE NOT EXISTS (
        SELECT 1 FROM rotom_rooker_profiles p WHERE p.uuid = r.uuid
      )
    ) b
  ) s
) t
WHERE NOT EXISTS (
  SELECT 1 FROM rotom_rooker_profiles p2 WHERE p2.handle = t.handle
);

-- ── Verify ─────────────────────────────────────────────────────────────────
-- without_profile must be 0. A non-zero count means a handle collision was
-- skipped rather than suffixed — run this file again and it will resolve.

SELECT
  (SELECT COUNT(*) FROM rotom_users)                    AS users,
  (SELECT COUNT(*) FROM rotom_rooker_profiles)          AS profiles,
  (SELECT COUNT(*) FROM rotom_users r
    WHERE NOT EXISTS (SELECT 1 FROM rotom_rooker_profiles p
                       WHERE p.uuid = r.uuid))          AS without_profile;
`
  );
}

const FILES: { name: string; build: () => string }[] = [
  { name: '00-admin.sql', build: admin },
  { name: '01-house-accounts.sql', build: houseAccounts },
  { name: '02-forum-categories.sql', build: forumCategories },
  { name: '03-gobierno.sql', build: gobierno },
  { name: '04-mine-rewards.sql', build: mineRewards },
  { name: '05-pasaporte.sql', build: pasaporte },
  { name: '06-rooker.sql', build: rooker },
];

const COMBINED = 'seed-all.sql';

function build(): Map<string, string> {
  const out = new Map<string, string>();
  for (const file of FILES) out.set(file.name, file.build());

  out.set(
    COMBINED,
    [
      '-- Every static seed, in order, for a one-shot bootstrap:',
      '--   mysql --default-character-set=utf8mb4 -u … -p <db> < drizzle/seed/seed-all.sql',
      '--',
      '-- PASS THE CHARSET. This file carries "Ciclo de Otoño" and rates like "500₽/parcela";',
      '-- piped into a client that falls back to latin1 they are silently mangled on the way in,',
      '-- and you find out when the UI renders "OtoÃ±o".',
      '--',
      '-- GENERATED by src/seed/generate-sql.ts — do not edit by hand.',
      '--',
      '-- COMPLETE: no Node step is required on the server. But EDIT THE SET LINES in the',
      '-- 00-admin section first — bcrypt cannot be computed in SQL, so the password hash',
      '-- has to be pasted in. Leaving the placeholder inserts no administrator, by design.',
      '',
      ...FILES.map((f) => `-- ═══ ${f.name} ${'═'.repeat(Math.max(0, 60 - f.name.length))}\n\n${out.get(f.name)!}`),
    ].join('\n'),
  );

  return out;
}

function main(): void {
  const check = process.argv.includes('--check');
  const generated = build();

  if (check) {
    const stale: string[] = [];
    for (const [name, content] of generated) {
      const path = join(OUT_DIR, name);
      if (!existsSync(path) || readFileSync(path, 'utf8') !== content) {
        stale.push(name);
      }
    }
    if (stale.length > 0) {
      console.error(
        `✖ drizzle/seed/ is stale (${stale.join(', ')}).\n` +
          '  A seed constant changed without the SQL being regenerated.\n' +
          '  Run `pnpm run seed:sql` and commit the result.',
      );
      process.exit(1);
    }
    console.log(`✓ drizzle/seed/ matches src/seed (${generated.size} files)`);
    return;
  }

  mkdirSync(OUT_DIR, { recursive: true });
  for (const [name, content] of generated) {
    writeFileSync(join(OUT_DIR, name), content, 'utf8');
    console.log(`✔ drizzle/seed/${name}`);
  }
}

main();
