import type { ComponentProps } from "react"
import { makeIconComponent } from "@/components/smartrotom/behavior/makeIconComponent"
import {
  Home,
  Search,
  Bell,
  Mail,
  SquarePen,
  Feather,
  Reply,
  Repeat2,
  Heart,
  Share2,
  BarChart2,
  MoreHorizontal,
  BadgeCheck,
  Check,
  Zap,
  Trophy,
  Sword,
  Sparkles,
  Pin,
  MapPin,
  Calendar,
  Users,
  Flame,
  Image,
  BarChart3,
  Smile,
  Globe,
  Settings,
  ArrowLeft,
  X,
  Plus,
  Link2,
  Play,
  Shield,
  Star,
  Grid2x2,
  Hash,
  TrendingUp,
  Bookmark,
  ChevronRight,
  Clock,
  type LucideIcon,
} from "lucide-react"
import { Gif } from "@/lib/smartrotom/customIcons"

/**
 * Rooker's icon set — lucide-react placeholders standing in for the hand-drawn
 * glyphs this replaced, plus the hand-drawn `gif` (lucide ships no GIF glyph).
 * See the migration ledger for fidelity notes.
 */
const MAP = {
  home: Home,
  search: Search,
  bell: Bell,
  mail: Mail,
  compose: SquarePen,
  feather: Feather,
  reply: Reply,
  retrino: Repeat2,
  heart: Heart,
  share: Share2,
  views: BarChart2,
  more: MoreHorizontal,
  verified: BadgeCheck,
  check: Check,
  bolt: Zap,
  trophy: Trophy,
  sword: Sword,
  sparkle: Sparkles,
  pin: Pin,
  location: MapPin,
  calendar: Calendar,
  users: Users,
  flame: Flame,
  image: Image,
  poll: BarChart3,
  gif: Gif,
  smile: Smile,
  globe: Globe,
  settings: Settings,
  back: ArrowLeft,
  close: X,
  plus: Plus,
  link: Link2,
  play: Play,
  shield: Shield,
  star: Star,
  grid: Grid2x2,
  fire: Flame,
  hash: Hash,
  trending: TrendingUp,
  bookmark: Bookmark,
  chevron: ChevronRight,
  clock: Clock,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof MAP

/** `fill` is a boolean here — `true` draws the glyph solid and drops the stroke. */
export const Icon = makeIconComponent(MAP, {
  size: 20,
  strokeWidth: 1.9,
  fill: false,
  className: (cls) => cls ?? "",
})

export type IconProps = ComponentProps<typeof Icon>
