// GENERATED by scripts/sync-tool-assets.mjs — do not edit by hand.
//
// The asset prefixes this build actually ships, and the sub-trees inside them
// that it does NOT. Anything else is fetched through `boffasset://`.

export const BUNDLED_ASSET_PREFIXES: readonly string[] = [
  "/boffmedia/tools/seeds/",
  "/smartrotom/img/pmd/portrait/"
]

export const BUNDLED_ASSET_EXCEPTIONS: readonly string[] = []

/** True when `path` is served out of this app's own bundle. */
export function isBundledAsset(path: string): boolean {
  if (BUNDLED_ASSET_EXCEPTIONS.some((prefix) => path.startsWith(prefix))) return false
  return BUNDLED_ASSET_PREFIXES.some((prefix) => path.startsWith(prefix))
}
