/**
 * GENERATED by scripts/build-seed-bundle.mjs — do not edit by hand.
 *
 * Maps a curated pack id to the file currently on disk. The filename carries a
 * hash of the bundle's contents because `/boffmedia/tools/*` is served
 * immutable for a year: without it, a rebuilt bundle keeps its old URL and
 * every browser that already has it never sees the new bytes.
 */

export const BUNDLE_FILES: Readonly<Record<string, string>> = {
  "continents": "continents-1.1.14.e8cbf5b8.bin",
  "tectonic": "tectonic-3.0.2.7fe90779.bin",
  "terralith": "terralith-2.6.2.0a2b82ad.bin",
  "vanilla": "vanilla-1.21.1.e8c9588c.bin",
};
