import * as React from "react"
import type { IconType } from "react-icons"
import {
  HiOutlineAdjustmentsHorizontal,
  HiOutlineArrowDownTray,
  HiOutlineArrowLeft,
  HiOutlineArrowPath,
  HiOutlineArrowRight,
  HiOutlineArrowRightOnRectangle,
  HiOutlineArrowTopRightOnSquare,
  HiOutlineArrowTrendingUp,
  HiOutlineArrowUturnLeft,
  HiOutlineArrowUpTray,
  HiOutlineArrowsPointingIn,
  HiOutlineArrowsPointingOut,
  HiOutlineArrowsRightLeft,
  HiOutlineBars3,
  HiOutlineBell,
  HiOutlineBookOpen,
  HiOutlineBookmark,
  HiOutlineBolt,
  HiOutlineCalculator,
  HiOutlineCalendarDays,
  HiOutlineCamera,
  HiOutlineChartBar,
  HiOutlineChatBubbleLeft,
  HiOutlineCheck,
  HiOutlineChevronDown,
  HiOutlineChevronRight,
  HiOutlineCircleStack,
  HiOutlineCodeBracket,
  HiOutlineCog6Tooth,
  HiOutlineCube,
  HiOutlineDocumentDuplicate,
  HiOutlineEllipsisVertical,
  HiOutlineEnvelope,
  HiOutlineExclamationTriangle,
  HiOutlineEye,
  HiOutlineFire,
  HiOutlineFolder,
  HiOutlineForward,
  HiOutlineGift,
  HiOutlineFunnel,
  HiOutlineGlobeAlt,
  HiOutlineHeart,
  HiOutlineHome,
  HiOutlineInbox,
  HiOutlineInformationCircle,
  HiOutlineKey,
  HiOutlineLink,
  HiOutlineLockClosed,
  HiOutlineMap,
  HiOutlineMagnifyingGlass,
  HiOutlineMinus,
  HiOutlineMoon,
  HiOutlinePause,
  HiOutlinePencil,
  HiOutlinePlay,
  HiOutlinePlus,
  HiOutlinePuzzlePiece,
  HiOutlineQueueList,
  HiOutlineRectangleStack,
  HiOutlineServer,
  HiOutlineSpeakerWave,
  HiOutlineSpeakerXMark,
  HiOutlineSparkles,
  HiOutlineSquares2X2,
  HiOutlineSquare3Stack3D,
  HiOutlineStar,
  HiOutlineSun,
  HiOutlineSwatch,
  HiOutlineClock,
  HiOutlineTrash,
  HiOutlineTrophy,
  HiOutlineUser,
  HiOutlineUsers,
  HiOutlineViewfinderCircle,
  HiOutlineWrench,
  HiOutlineXMark,
} from "react-icons/hi2"
import {
  TbAxe,
  TbCompass,
  TbDeviceGamepad,
  TbDeviceGamepad2,
  TbDice,
  TbDroplet,
  TbDualScreen,
  TbHammer,
  TbPaw,
  TbRoulette,
  TbShield,
  TbSkull,
  TbSword,
  TbTree,
} from "react-icons/tb"
import { SiDiscord, SiGoogle, SiSteam, SiTwitch } from "react-icons/si"
import { cn } from "../cn"

const ICONS = {
  arrow: HiOutlineArrowRight,
  back: HiOutlineArrowLeft,
  home: HiOutlineHome,
  search: HiOutlineMagnifyingGlass,
  bell: HiOutlineBell,
  user: HiOutlineUser,
  users: HiOutlineUsers,
  sun: HiOutlineSun,
  moon: HiOutlineMoon,
  gamepad: TbDeviceGamepad,
  handheld: TbDeviceGamepad2,
  dualscreen: TbDualScreen,
  trophy: HiOutlineTrophy,
  calc: HiOutlineCalculator,
  sword: TbSword,
  tree: TbTree,
  chart: HiOutlineChartBar,
  trending: HiOutlineArrowTrendingUp,
  cards: HiOutlineRectangleStack,
  mail: HiOutlineEnvelope,
  calendar: HiOutlineCalendarDays,
  wrench: HiOutlineWrench,
  shield: TbShield,
  settings: HiOutlineCog6Tooth,
  bolt: HiOutlineBolt,
  flame: HiOutlineFire,
  target: HiOutlineViewfinderCircle,
  star: HiOutlineStar,
  check: HiOutlineCheck,
  x: HiOutlineXMark,
  plus: HiOutlinePlus,
  minus: HiOutlineMinus,
  edit: HiOutlinePencil,
  trash: HiOutlineTrash,
  eye: HiOutlineEye,
  link: HiOutlineLink,
  copy: HiOutlineDocumentDuplicate,
  chevronDown: HiOutlineChevronDown,
  chevronRight: HiOutlineChevronRight,
  collapse: HiOutlineArrowsPointingIn,
  list: HiOutlineQueueList,
  menu: HiOutlineBars3,
  grid: HiOutlineSquares2X2,
  filter: HiOutlineFunnel,
  clock: HiOutlineClock,
  info: HiOutlineInformationCircle,
  alert: HiOutlineExclamationTriangle,
  axe: TbAxe,
  puzzle: HiOutlinePuzzlePiece,
  play: HiOutlinePlay,
  download: HiOutlineArrowDownTray,
  external: HiOutlineArrowTopRightOnSquare,
  key: HiOutlineKey,
  gift: HiOutlineGift,
  hammer: TbHammer,
  zap: HiOutlineBolt,
  database: HiOutlineCircleStack,
  layers: HiOutlineSquare3Stack3D,
  sliders: HiOutlineAdjustmentsHorizontal,
  cog: HiOutlineCog6Tooth,
  refresh: HiOutlineArrowPath,
  book: HiOutlineBookOpen,
  globe: HiOutlineGlobeAlt,
  message: HiOutlineChatBubbleLeft,
  swatch: HiOutlineSwatch,
  sparkles: HiOutlineSparkles,
  inbox: HiOutlineInbox,
  code: HiOutlineCodeBracket,
  bookmark: HiOutlineBookmark,
  chevron: HiOutlineChevronDown,
  lock: HiOutlineLockClosed,
  heart: HiOutlineHeart,
  reply: HiOutlineArrowUturnLeft,
  paw: TbPaw,
  drop: TbDroplet,
  crosshair: HiOutlineViewfinderCircle,
  map: HiOutlineMap,
  skull: TbSkull,
  chain: HiOutlineLink,
  compass: TbCompass,
  dice: TbDice,
  discord: SiDiscord,
  google: SiGoogle,
  wheel: TbRoulette,
  steam: SiSteam,
  twitch: SiTwitch,
  camera: HiOutlineCamera,
  logout: HiOutlineArrowRightOnRectangle,
  fullscreen: HiOutlineArrowsPointingOut,
  exitFullscreen: HiOutlineArrowsPointingIn,
  pause: HiOutlinePause,
  swap: HiOutlineArrowsRightLeft,
  cube: HiOutlineCube,
  folder: HiOutlineFolder,
  upload: HiOutlineArrowUpTray,
  server: HiOutlineServer,
  more: HiOutlineEllipsisVertical,
  volume: HiOutlineSpeakerWave,
  mute: HiOutlineSpeakerXMark,
  skip: HiOutlineForward,
} satisfies Record<string, IconType>

/** Every valid icon name — use this to type icon fields so typos fail at compile time. */
export type IconName = keyof typeof ICONS

/** Runtime check for names that only exist as strings at compile time. */
export function isIconName(value: string): value is IconName {
  return Object.prototype.hasOwnProperty.call(ICONS, value)
}

export interface IconProps {
  name: IconName
  size?: number
  className?: string
  style?: React.CSSProperties
}

export function Icon({ name, size = 18, className, style }: IconProps) {
  const Glyph = ICONS[name] || ICONS.info
  return <Glyph size={size} className={cn("shrink-0", className)} style={style} aria-hidden="true" />
}

export const ICON_NAMES = Object.keys(ICONS) as IconName[]
