import type { MhWildsAnatomyCallout, MhWildsAnatomySlot } from "../types";

export type AnatomyPoint = { x: number; y: number };

/**
 * The report uses a fixed ten-slot board. These are the board's edge anchors,
 * expressed in the 100x100 coordinate system used by the SVG overlay.
 *
 * The extracted ArrowSize values are authored against the 512px anatomy
 * texture, while ArrowRot is the line angle relative to the slot's inward
 * direction. Keeping the transform here makes the fallback match the
 * coordinates generated by the asset normalizer.
 */
export const ANATOMY_SLOT_ANCHORS: Record<string, AnatomyPoint> = {
  leftTop: { x: 0, y: 17 },
  leftCenterUp: { x: 0, y: 35 },
  leftCenterUnder: { x: 0, y: 57 },
  leftBottom: { x: 0, y: 75 },
  centerTop: { x: 50, y: 17 },
  centerBottom: { x: 50, y: 78 },
  rightTop: { x: 100, y: 17 },
  rightCenterUp: { x: 100, y: 35 },
  rightCenterUnder: { x: 100, y: 57 },
  rightBottom: { x: 100, y: 75 },
};

const ANATOMY_CANVAS_SIZE = 512;
const ANATOMY_MIN_COORDINATE = 1;
const ANATOMY_MAX_COORDINATE = 99;

function finitePoint(
  point: AnatomyPoint | null | undefined,
): AnatomyPoint | null {
  if (!point || !Number.isFinite(point.x) || !Number.isFinite(point.y))
    return null;
  return point;
}

function clampCoordinate(value: number): number {
  return Math.min(
    ANATOMY_MAX_COORDINATE,
    Math.max(ANATOMY_MIN_COORDINATE, value),
  );
}

function fallbackCallout(
  slot: MhWildsAnatomySlot,
): MhWildsAnatomyCallout | null {
  const anchor = ANATOMY_SLOT_ANCHORS[slot.key];
  const arrow = slot.arrow;
  if (!anchor || !arrow?.visible) return null;
  if (
    arrow.size == null ||
    arrow.rotation == null ||
    !Number.isFinite(arrow.size) ||
    !Number.isFinite(arrow.rotation)
  )
    return null;

  const radians = ((arrow.rotation - 90) * Math.PI) / 180;
  const distance = (arrow.size / ANATOMY_CANVAS_SIZE) * 100;
  return {
    anchor,
    target: {
      x: clampCoordinate(anchor.x + Math.cos(radians) * distance),
      y: clampCoordinate(anchor.y + Math.sin(radians) * distance),
    },
  };
}

export function anatomyCalloutTarget(
  slot: MhWildsAnatomySlot,
): MhWildsAnatomyCallout | null {
  const generated = slot.callout;
  if (generated) {
    const anchor = finitePoint(generated.anchor);
    const target = finitePoint(generated.target);
    if (anchor && target) return { anchor, target };
  }
  return fallbackCallout(slot);
}
