/**
 * AUTO-GENERATED by `pnpm add-regulation`. Do not edit by hand.
 *
 * Upstream : smogon/pokemon-showdown@d849b2200 (2026-09-09)
 * Built for: @pkmn/sim 0.9.38
 *
 * Regenerate with:
 *   pnpm add-regulation "<upstream format name>"
 */
import { Abilities as ChampionsAbilities } from './abilities';
import { Abilities as ChampionsregmaAbilities } from './regma/abilities';
import { Conditions as ChampionsConditions } from './conditions';
import { FormatsData as ChampionsFormatsData } from './formats-data';
import { FormatsData as ChampionsregmaFormatsData } from './regma/formats-data';
import { FormatsData as ChampionsregmbFormatsData } from './regmb/formats-data';
import { Items as ChampionsItems } from './items';
import { Items as ChampionsregmaItems } from './regma/items';
import { Items as ChampionsregmbItems } from './regmb/items';
import { Learnsets as ChampionsLearnsets } from './learnsets';
import { Learnsets as ChampionsregmbLearnsets } from './regmb/learnsets';
import { Moves as ChampionsMoves } from './moves';
import { Moves as ChampionsregmaMoves } from './regma/moves';
import { Moves as ChampionsregmbMoves } from './regmb/moves';
import { Pokedex as ChampionsPokedex } from './pokedex';
import { Rulesets as ChampionsRulesets } from './rulesets';
import { Scripts as ChampionsScripts } from './scripts';
import { Scripts as ChampionsregmaScripts } from './regma/scripts';
import { Scripts as ChampionsregmbScripts } from './regmb/scripts';

export interface ChampionsModRegistration {
  /** Mod id as the sim knows it, e.g. 'championsregma'. */
  id: string;
  /** Data tables handed to Dex.mod(). */
  data: Record<string, unknown>;
}

/**
 * Ordered parents-first: a mod whose Scripts declare `inherit` needs its
 * parent already present in the sim's dex registry when it is registered.
 */
export const CHAMPIONS_MODS: readonly ChampionsModRegistration[] = [
  {
    id: 'champions',
    data: {
      Abilities: ChampionsAbilities,
      Conditions: ChampionsConditions,
      FormatsData: ChampionsFormatsData,
      Items: ChampionsItems,
      Learnsets: ChampionsLearnsets,
      Moves: ChampionsMoves,
      Rulesets: ChampionsRulesets,
      Scripts: ChampionsScripts,
      Species: ChampionsPokedex,
    },
  },
  {
    id: 'championsregmb',
    data: {
      FormatsData: ChampionsregmbFormatsData,
      Items: ChampionsregmbItems,
      Learnsets: ChampionsregmbLearnsets,
      Moves: ChampionsregmbMoves,
      Scripts: ChampionsregmbScripts,
    },
  },
  {
    id: 'championsregma',
    data: {
      Abilities: ChampionsregmaAbilities,
      FormatsData: ChampionsregmaFormatsData,
      Items: ChampionsregmaItems,
      Moves: ChampionsregmaMoves,
      Scripts: ChampionsregmaScripts,
    },
  },
];

/** Format entries, copied verbatim from upstream `config/formats.ts`. */
export const CHAMPIONS_FORMATS = [
  {
    name: "[Gen 9 Champions] BSS Reg M-A",
    mod: "championsregma",
    searchShow: false,
    bestOfDefault: true,
    ruleset: ["Flat Rules", "VGC Timer"],
  },
  {
    name: "[Gen 9 Champions] BSS Reg M-B",
    mod: "championsregmb",
    searchShow: false,
    bestOfDefault: true,
    ruleset: ["Flat Rules", "VGC Timer"],
  },
  {
    name: "[Gen 9 Champions] Draft",
    mod: "champions",
    searchShow: false,
    ruleset: ["Standard Draft"],
  },
  {
    name: "[Gen 9 Champions] OU",
    mod: "champions",
    ruleset: ["Standard"],
    banlist: ["AG", "Uber", "Moody", "Damp Rock", "King's Rock", "Light Clay", "Quick Claw", "Baton Pass", "Last Respects", "Shed Tail"],
  },
  {
    name: "[Gen 9 Champions] VGC 2026 Reg M-A",
    mod: "championsregma",
    gameType: "doubles",
    searchShow: false,
    bestOfDefault: true,
    ruleset: ["Flat Rules", "VGC Timer", "Open Team Sheets"],
  },
  {
    name: "[Gen 9 Champions] VGC 2026 Reg M-A (Bo3)",
    mod: "championsregma",
    gameType: "doubles",
    searchShow: false,
    ruleset: ["Flat Rules", "VGC Timer", "Force Open Team Sheets", "Best of = 3"],
  },
  {
    name: "[Gen 9 Champions] VGC 2026 Reg M-B",
    mod: "championsregmb",
    gameType: "doubles",
    searchShow: false,
    bestOfDefault: true,
    ruleset: ["Flat Rules", "VGC Timer", "Open Team Sheets"],
  },
  {
    name: "[Gen 9 Champions] VGC 2026 Reg M-B (Bo3)",
    mod: "championsregmb",
    gameType: "doubles",
    searchShow: false,
    ruleset: ["Flat Rules", "VGC Timer", "Force Open Team Sheets", "Best of = 3"],
  },
  {
    name: "[Gen 9 Champions] VGC 2026 Reg M-C",
    mod: "champions",
    gameType: "doubles",
    bestOfDefault: true,
    ruleset: ["Flat Rules", "VGC Timer", "Open Team Sheets"],
  },
  {
    name: "[Gen 9 Champions] VGC 2026 Reg M-C (Bo3)",
    mod: "champions",
    gameType: "doubles",
    ruleset: ["Flat Rules", "VGC Timer", "Force Open Team Sheets", "Best of = 3"],
  },
] as const;
