export enum AppStatus {
  INACTIVE = 0,
  ACTIVE = 1,
}

export enum ErrorCodes {
  APP_NOT_FOUND = 'APP_NOT_FOUND',
  APP_ALREADY_EXISTS = 'APP_ALREADY_EXISTS',
  APP_INACTIVE = 'APP_INACTIVE',
  APP_HAS_USERS = 'APP_HAS_USERS',
  APP_URL_ALREADY_EXISTS = 'APP_URL_ALREADY_EXISTS',
  USER_APP_NOT_FOUND = 'USER_APP_NOT_FOUND',
  USER_APP_ALREADY_EXISTS = 'USER_APP_ALREADY_EXISTS',
  INVALID_UUID = 'INVALID_UUID',
  INVALID_APP_ID = 'INVALID_APP_ID',
  INVALID_APP_ORDER = 'INVALID_APP_ORDER',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}

export const DefaultValues = {
  APP_ORDER: 999,
  PAGINATION_LIMIT: 50,
  PAGINATION_OFFSET: 0,
} as const;

export const ValidationRules = {
  APP_NAME_MAX_LENGTH: 32,
  APP_NAME_MIN_LENGTH: 1,
  UUID_LENGTH: 36,
  URL_MAX_LENGTH: 255,
} as const;