/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type { AbilityCount } from './models/AbilityCount';
export type { AbilityInfo } from './models/AbilityInfo';
export type { AccessRowEntity } from './models/AccessRowEntity';
export { Achievement } from './models/Achievement';
export type { AchievementStatusResponse } from './models/AchievementStatusResponse';
export { AchievementWithProgress } from './models/AchievementWithProgress';
export { ActivityItemEntity } from './models/ActivityItemEntity';
export type { ActorBodyDto } from './models/ActorBodyDto';
export type { ActorDto } from './models/ActorDto';
export type { AddInventoryItemDto } from './models/AddInventoryItemDto';
export type { AddLimitlessTournamentDto } from './models/AddLimitlessTournamentDto';
export type { AddMemberDto } from './models/AddMemberDto';
export type { AddNoteToUserDto } from './models/AddNoteToUserDto';
export { AddParticipantDto } from './models/AddParticipantDto';
export type { AddUserCardDto } from './models/AddUserCardDto';
export { AdminPackEntity } from './models/AdminPackEntity';
export type { AdminTeleportDto } from './models/AdminTeleportDto';
export type { ApiResponseEntity } from './models/ApiResponseEntity';
export { ArcadeInventoryItem } from './models/ArcadeInventoryItem';
export type { ArcadeInventoryResponse } from './models/ArcadeInventoryResponse';
export type { ArcadeStreak } from './models/ArcadeStreak';
export type { ArcadeStreakClaim } from './models/ArcadeStreakClaim';
export type { ArceuSpeakEntity } from './models/ArceuSpeakEntity';
export type { ArceusspeakDto } from './models/ArceusspeakDto';
export type { ArmorEntity } from './models/ArmorEntity';
export type { AuthenticationResultEntity } from './models/AuthenticationResultEntity';
export type { AuthLoginResponseEntity } from './models/AuthLoginResponseEntity';
export type { AuthRefreshResponseEntity } from './models/AuthRefreshResponseEntity';
export type { AuthRefreshSmartRotomUserEntity } from './models/AuthRefreshSmartRotomUserEntity';
export type { AuthRefreshUserEntity } from './models/AuthRefreshUserEntity';
export type { AuthUserEntity } from './models/AuthUserEntity';
export type { BaseDto } from './models/BaseDto';
export type { BaseStatsDto } from './models/BaseStatsDto';
export type { BatchFetchResultDto } from './models/BatchFetchResultDto';
export type { BatchUsersDto } from './models/BatchUsersDto';
export type { BatchUsersRequestDto } from './models/BatchUsersRequestDto';
export type { BattleAchievementDto } from './models/BattleAchievementDto';
export type { BattleAchievementResponse } from './models/BattleAchievementResponse';
export type { BiomeSpawnCollection } from './models/BiomeSpawnCollection';
export type { BiomeSpawnEntry } from './models/BiomeSpawnEntry';
export type { BlobUploadEntity } from './models/BlobUploadEntity';
export type { BoffMediaUserEntity } from './models/BoffMediaUserEntity';
export type { BulkDownloadResult } from './models/BulkDownloadResult';
export type { BulkUpsertPcMarksDto } from './models/BulkUpsertPcMarksDto';
export type { CacheOperationResultEntity } from './models/CacheOperationResultEntity';
export type { CacheRefreshResponse } from './models/CacheRefreshResponse';
export type { CacheStatusResponse } from './models/CacheStatusResponse';
export type { CallResponse } from './models/CallResponse';
export type { CallSession } from './models/CallSession';
export { CallUser } from './models/CallUser';
export type { CancelMultaDto } from './models/CancelMultaDto';
export type { CaptureBuscadoDto } from './models/CaptureBuscadoDto';
export type { CartelDestinationDto } from './models/CartelDestinationDto';
export type { CatalogSearchConsoleResult } from './models/CatalogSearchConsoleResult';
export type { CatalogSearchResult } from './models/CatalogSearchResult';
export type { CategoryEntity } from './models/CategoryEntity';
export type { ChampionsPasteDetailDto } from './models/ChampionsPasteDetailDto';
export { ChampionsRegulationDto } from './models/ChampionsRegulationDto';
export type { ChangePasswordDto } from './models/ChangePasswordDto';
export type { ChapterEntry } from './models/ChapterEntry';
export type { CharmEntity } from './models/CharmEntity';
export type { CharmRankEntity } from './models/CharmRankEntity';
export type { Chat } from './models/Chat';
export type { ChatMember } from './models/ChatMember';
export { ChatMessage } from './models/ChatMessage';
export type { CheckAchievementDto } from './models/CheckAchievementDto';
export { ClaimCajaDto } from './models/ClaimCajaDto';
export type { ClaimCajaResponse } from './models/ClaimCajaResponse';
export type { ClaimResponse } from './models/ClaimResponse';
export type { ClaimRewardDto } from './models/ClaimRewardDto';
export type { ClaimRewardsDto } from './models/ClaimRewardsDto';
export type { ClapResponse } from './models/ClapResponse';
export type { CloseSubastaDto } from './models/CloseSubastaDto';
export { Competitor } from './models/Competitor';
export type { ConfirmCajaDto } from './models/ConfirmCajaDto';
export type { ConfirmCajaResponse } from './models/ConfirmCajaResponse';
export type { ConfirmReportDto } from './models/ConfirmReportDto';
export type { ConsumeInventoryItemDto } from './models/ConsumeInventoryItemDto';
export type { ConvertChapterDto } from './models/ConvertChapterDto';
export type { CountResultDto } from './models/CountResultDto';
export { CreateAchievementDto } from './models/CreateAchievementDto';
export type { CreateAnuncioDto } from './models/CreateAnuncioDto';
export type { CreateApelacionDto } from './models/CreateApelacionDto';
export { CreateAppDto } from './models/CreateAppDto';
export type { CreateBidDto } from './models/CreateBidDto';
export { CreateBitacoraDto } from './models/CreateBitacoraDto';
export { CreateBuscadoDto } from './models/CreateBuscadoDto';
export type { CreateCartelDto } from './models/CreateCartelDto';
export type { CreateChatDto } from './models/CreateChatDto';
export type { CreateChatResponse } from './models/CreateChatResponse';
export type { CreateDenunciaDto } from './models/CreateDenunciaDto';
export type { CreateDocumentDto } from './models/CreateDocumentDto';
export type { CreateDocumentDtoWithUuid } from './models/CreateDocumentDtoWithUuid';
export type { CreateEspecieDto } from './models/CreateEspecieDto';
export { CreateEventDto } from './models/CreateEventDto';
export { CreateEventoDto } from './models/CreateEventoDto';
export { CreateExpedienteDto } from './models/CreateExpedienteDto';
export type { CreateExpedienteEventoDto } from './models/CreateExpedienteEventoDto';
export type { CreateFolderDto } from './models/CreateFolderDto';
export type { CreateGameDto } from './models/CreateGameDto';
export type { CreateInviteDto } from './models/CreateInviteDto';
export { CreateListingDto } from './models/CreateListingDto';
export { CreateMatchDto } from './models/CreateMatchDto';
export { CreateMessageDto } from './models/CreateMessageDto';
export type { CreateMessageResponse } from './models/CreateMessageResponse';
export type { CreateMultaDto } from './models/CreateMultaDto';
export type { CreateNewsCommentDto } from './models/CreateNewsCommentDto';
export type { CreateNewsDto } from './models/CreateNewsDto';
export type { CreateNoteResponse } from './models/CreateNoteResponse';
export { CreateNotificationDto } from './models/CreateNotificationDto';
export type { CreateNpcSkinDto } from './models/CreateNpcSkinDto';
export type { CreateObraDto } from './models/CreateObraDto';
export type { CreateOfferDto } from './models/CreateOfferDto';
export type { CreateOrderDto } from './models/CreateOrderDto';
export { CreatePackDto } from './models/CreatePackDto';
export type { CreateParcelaDto } from './models/CreateParcelaDto';
export type { CreateParcelaHistorialDto } from './models/CreateParcelaHistorialDto';
export { CreatePatrullaDto } from './models/CreatePatrullaDto';
export { CreatePhaseDto } from './models/CreatePhaseDto';
export { CreatePostDto } from './models/CreatePostDto';
export type { CreatePresetDto } from './models/CreatePresetDto';
export type { CreateReplayDto } from './models/CreateReplayDto';
export type { CreateReplayResponse } from './models/CreateReplayResponse';
export type { CreateReviewDto } from './models/CreateReviewDto';
export { CreateSessionDto } from './models/CreateSessionDto';
export { CreateShopTransactionDto } from './models/CreateShopTransactionDto';
export type { CreateSmartrotomUserDto } from './models/CreateSmartrotomUserDto';
export type { CreateSubastaDto } from './models/CreateSubastaDto';
export type { CreateSuggestionDto } from './models/CreateSuggestionDto';
export type { CreateSuggestionResultEntity } from './models/CreateSuggestionResultEntity';
export type { CreateTagDto } from './models/CreateTagDto';
export type { CreateTasaDto } from './models/CreateTasaDto';
export type { CreateTeamDto } from './models/CreateTeamDto';
export type { CreateThreadDto } from './models/CreateThreadDto';
export { CreateTournamentDto } from './models/CreateTournamentDto';
export type { CreateTradeDto } from './models/CreateTradeDto';
export type { CreateTransferDto } from './models/CreateTransferDto';
export type { CreateUserDto } from './models/CreateUserDto';
export type { CreateUserReplayDto } from './models/CreateUserReplayDto';
export type { CreateUserReplayResponse } from './models/CreateUserReplayResponse';
export { CreateVersionDto } from './models/CreateVersionDto';
export type { CreateZonaDto } from './models/CreateZonaDto';
export type { CronConfigDto } from './models/CronConfigDto';
export { CurseforgeSourceDto } from './models/CurseforgeSourceDto';
export type { DailyRewardBox } from './models/DailyRewardBox';
export { DailyRewardItem } from './models/DailyRewardItem';
export type { DailyRewardsConfig } from './models/DailyRewardsConfig';
export type { DecorationEntity } from './models/DecorationEntity';
export type { DeleteFileDto } from './models/DeleteFileDto';
export type { DeleteListingDto } from './models/DeleteListingDto';
export type { DeleteMessageDto } from './models/DeleteMessageDto';
export type { DetailedPokedexStatistics } from './models/DetailedPokedexStatistics';
export type { Dialogue } from './models/Dialogue';
export type { DiscordCallbackDto } from './models/DiscordCallbackDto';
export type { DivergenceResultDto } from './models/DivergenceResultDto';
export { DivergenceRowDto } from './models/DivergenceRowDto';
export type { Document } from './models/Document';
export { DownloadAllGamesDto } from './models/DownloadAllGamesDto';
export type { DownloadChaptersDto } from './models/DownloadChaptersDto';
export type { DownloadMangaNovelDto } from './models/DownloadMangaNovelDto';
export type { DownloadResult } from './models/DownloadResult';
export { DownloadSelectedGamesDto } from './models/DownloadSelectedGamesDto';
export type { DropRateEntry } from './models/DropRateEntry';
export type { DropRates } from './models/DropRates';
export type { DungeonBestRun } from './models/DungeonBestRun';
export type { DungeonPlayerStats } from './models/DungeonPlayerStats';
export type { DungeonRankingEntry } from './models/DungeonRankingEntry';
export type { DungeonRunParticipantDto } from './models/DungeonRunParticipantDto';
export type { EditorialBoardMember } from './models/EditorialBoardMember';
export type { EditPostDto } from './models/EditPostDto';
export { EmulatorSpecDto } from './models/EmulatorSpecDto';
export type { EndCallDto } from './models/EndCallDto';
export type { EndGameDto } from './models/EndGameDto';
export type { EnergyStatus } from './models/EnergyStatus';
export type { EpubMetadataDto } from './models/EpubMetadataDto';
export type { EuropeAggregateResult } from './models/EuropeAggregateResult';
export { Event } from './models/Event';
export type { EventoWeightsDto } from './models/EventoWeightsDto';
export type { EvolutionMethod } from './models/EvolutionMethod';
export type { EvolutionNode } from './models/EvolutionNode';
export type { EvolutionTree } from './models/EvolutionTree';
export type { FactionRequirements } from './models/FactionRequirements';
export { FetchSmogonDto } from './models/FetchSmogonDto';
export type { FicusAiHealthEntity } from './models/FicusAiHealthEntity';
export type { FicusAiUserStatsEntity } from './models/FicusAiUserStatsEntity';
export type { FicusMessageContentDto } from './models/FicusMessageContentDto';
export { FileDownloadEntry } from './models/FileDownloadEntry';
export { FindOrCreateResult } from './models/FindOrCreateResult';
export type { FollowDto } from './models/FollowDto';
export type { ForgotPasswordDto } from './models/ForgotPasswordDto';
export { ForumAuthor } from './models/ForumAuthor';
export type { ForumCategory } from './models/ForumCategory';
export { ForumMember } from './models/ForumMember';
export type { ForumPost } from './models/ForumPost';
export type { ForumPostList } from './models/ForumPostList';
export type { ForumStats } from './models/ForumStats';
export type { ForumThread } from './models/ForumThread';
export type { ForumThreadList } from './models/ForumThreadList';
export type { ForumVoteResult } from './models/ForumVoteResult';
export { FullMove } from './models/FullMove';
export type { FullUserEntity } from './models/FullUserEntity';
export type { Game } from './models/Game';
export type { GameEndResponse } from './models/GameEndResponse';
export type { GameFileEntry } from './models/GameFileEntry';
export type { GameRewardDto } from './models/GameRewardDto';
export type { GameStartResponse } from './models/GameStartResponse';
export { GameVersionEntity } from './models/GameVersionEntity';
export type { Gen9DataDto } from './models/Gen9DataDto';
export type { Gen9MoveDto } from './models/Gen9MoveDto';
export { GenerateBracketDto } from './models/GenerateBracketDto';
export type { GetAchievementByIdDto } from './models/GetAchievementByIdDto';
export type { GetAchievementsDto } from './models/GetAchievementsDto';
export type { GetNewsDto } from './models/GetNewsDto';
export type { GetPlayerAppsDto } from './models/GetPlayerAppsDto';
export type { GetReplayDto } from './models/GetReplayDto';
export type { GetUserDocumentsDto } from './models/GetUserDocumentsDto';
export type { GetUserQuestsDto } from './models/GetUserQuestsDto';
export type { GiveLootboxDto } from './models/GiveLootboxDto';
export type { GobiernoAnuncioEntity } from './models/GobiernoAnuncioEntity';
export type { GobiernoAnuncioListEntity } from './models/GobiernoAnuncioListEntity';
export type { GobiernoApelacionEntity } from './models/GobiernoApelacionEntity';
export type { GobiernoApelacionListEntity } from './models/GobiernoApelacionListEntity';
export type { GobiernoAuditoriaEntity } from './models/GobiernoAuditoriaEntity';
export type { GobiernoAuditoriaListEntity } from './models/GobiernoAuditoriaListEntity';
export { GobiernoBitacoraEntity } from './models/GobiernoBitacoraEntity';
export { GobiernoBuscadoEntity } from './models/GobiernoBuscadoEntity';
export type { GobiernoBuscadoListEntity } from './models/GobiernoBuscadoListEntity';
export type { GobiernoCartelEntity } from './models/GobiernoCartelEntity';
export { GobiernoCensoEntity } from './models/GobiernoCensoEntity';
export type { GobiernoCensoListEntity } from './models/GobiernoCensoListEntity';
export type { GobiernoCountersEntity } from './models/GobiernoCountersEntity';
export type { GobiernoDenunciaEntity } from './models/GobiernoDenunciaEntity';
export type { GobiernoDenunciaListEntity } from './models/GobiernoDenunciaListEntity';
export type { GobiernoEventoCapturaEntity } from './models/GobiernoEventoCapturaEntity';
export type { GobiernoEventoCapturasResponseEntity } from './models/GobiernoEventoCapturasResponseEntity';
export { GobiernoEventoEntity } from './models/GobiernoEventoEntity';
export type { GobiernoEventoEspecieEntity } from './models/GobiernoEventoEspecieEntity';
export type { GobiernoEventoEspecieListEntity } from './models/GobiernoEventoEspecieListEntity';
export type { GobiernoEventoObraEntity } from './models/GobiernoEventoObraEntity';
export type { GobiernoEventoObraListEntity } from './models/GobiernoEventoObraListEntity';
export type { GobiernoExpedienteEntity } from './models/GobiernoExpedienteEntity';
export type { GobiernoExpedienteEventoEntity } from './models/GobiernoExpedienteEventoEntity';
export type { GobiernoExpedienteEventoListEntity } from './models/GobiernoExpedienteEventoListEntity';
export type { GobiernoExpedienteListEntity } from './models/GobiernoExpedienteListEntity';
export type { GobiernoMegafoniaEntity } from './models/GobiernoMegafoniaEntity';
export type { GobiernoMultaEntity } from './models/GobiernoMultaEntity';
export type { GobiernoMultaListEntity } from './models/GobiernoMultaListEntity';
export type { GobiernoNpcSkinEntity } from './models/GobiernoNpcSkinEntity';
export type { GobiernoOficialEntity } from './models/GobiernoOficialEntity';
export type { GobiernoOficialRankEntity } from './models/GobiernoOficialRankEntity';
export type { GobiernoParcelaEntity } from './models/GobiernoParcelaEntity';
export type { GobiernoParcelaHistorialEntity } from './models/GobiernoParcelaHistorialEntity';
export type { GobiernoParcelaHistorialListEntity } from './models/GobiernoParcelaHistorialListEntity';
export type { GobiernoParcelaListEntity } from './models/GobiernoParcelaListEntity';
export type { GobiernoPatrullaEntity } from './models/GobiernoPatrullaEntity';
export type { GobiernoPujaEntity } from './models/GobiernoPujaEntity';
export type { GobiernoSubastaEntity } from './models/GobiernoSubastaEntity';
export type { GobiernoSubastaListEntity } from './models/GobiernoSubastaListEntity';
export type { GobiernoTasaEntity } from './models/GobiernoTasaEntity';
export type { GobiernoTesoreriaEntity } from './models/GobiernoTesoreriaEntity';
export type { GobiernoZonaEntity } from './models/GobiernoZonaEntity';
export type { GoogleAuthDto } from './models/GoogleAuthDto';
export type { GoogleCallbackDto } from './models/GoogleCallbackDto';
export type { GrantAccessDto } from './models/GrantAccessDto';
export { GrantRoleDto } from './models/GrantRoleDto';
export type { HeldItem } from './models/HeldItem';
export type { ImageExistsResponse } from './models/ImageExistsResponse';
export type { ImageUploadResponse } from './models/ImageUploadResponse';
export type { ImportJobStatusDto } from './models/ImportJobStatusDto';
export type { InitializationResult } from './models/InitializationResult';
export type { InitiateCallDto } from './models/InitiateCallDto';
export type { IntegratedUserCreationResultEntity } from './models/IntegratedUserCreationResultEntity';
export type { IntegrationsEntity } from './models/IntegrationsEntity';
export type { InventoryItemGroup } from './models/InventoryItemGroup';
export type { InviteCodeEntity } from './models/InviteCodeEntity';
export type { ItemSprite } from './models/ItemSprite';
export type { JoinChallengeEntity } from './models/JoinChallengeEntity';
export type { JoinEventDto } from './models/JoinEventDto';
export type { JoinTeamDto } from './models/JoinTeamDto';
export type { KartCircuitBest } from './models/KartCircuitBest';
export type { KartPlayerStats } from './models/KartPlayerStats';
export type { KartRankingEntry } from './models/KartRankingEntry';
export type { LauncherDownloadEntity } from './models/LauncherDownloadEntity';
export { LauncherPackEntity } from './models/LauncherPackEntity';
export type { LauncherReleaseEntity } from './models/LauncherReleaseEntity';
export type { LauncherSessionEntity } from './models/LauncherSessionEntity';
export type { LauncherVersionEntity } from './models/LauncherVersionEntity';
export type { LeaderboardEntry } from './models/LeaderboardEntry';
export type { LimitlessPlayerDto } from './models/LimitlessPlayerDto';
export type { LimitlessPlayerTeamDto } from './models/LimitlessPlayerTeamDto';
export type { LimitlessTournamentDto } from './models/LimitlessTournamentDto';
export type { LinkDiscordDto } from './models/LinkDiscordDto';
export type { LinkGoogleDto } from './models/LinkGoogleDto';
export type { LinkSteamDto } from './models/LinkSteamDto';
export type { LinkTwitchDto } from './models/LinkTwitchDto';
export type { ListingItemInputDto } from './models/ListingItemInputDto';
export type { ListingMonInputDto } from './models/ListingMonInputDto';
export type { LoaderVersionEntity } from './models/LoaderVersionEntity';
export type { LocalChaptersResult } from './models/LocalChaptersResult';
export { Locale } from './models/Locale';
export type { LocalGameEntry } from './models/LocalGameEntry';
export type { LocalGamesResult } from './models/LocalGamesResult';
export type { LoginMcDto } from './models/LoginMcDto';
export type { LootboxBoxConfig } from './models/LootboxBoxConfig';
export type { LootboxBoxesCollection } from './models/LootboxBoxesCollection';
export type { LootboxConfigEntity } from './models/LootboxConfigEntity';
export { LootboxItemConfig } from './models/LootboxItemConfig';
export type { MangaChapter } from './models/MangaChapter';
export type { MangaDetail } from './models/MangaDetail';
export type { MangaResult } from './models/MangaResult';
export type { MangaSearchResult } from './models/MangaSearchResult';
export type { MarkChatReadDto } from './models/MarkChatReadDto';
export type { MarkChatReadResponse } from './models/MarkChatReadResponse';
export type { MarkMessageReadDto } from './models/MarkMessageReadDto';
export type { MarkReadBodyDto } from './models/MarkReadBodyDto';
export { MatchDetail } from './models/MatchDetail';
export { MatchDto } from './models/MatchDto';
export type { MatchMessageDto } from './models/MatchMessageDto';
export { MatchMessageView } from './models/MatchMessageView';
export { MatchNoteDto } from './models/MatchNoteDto';
export { MatchProposalView } from './models/MatchProposalView';
export type { MatchSideRecord } from './models/MatchSideRecord';
export { MatchSlotDto } from './models/MatchSlotDto';
export { MatchView } from './models/MatchView';
export type { MessagePartDto } from './models/MessagePartDto';
export { MessagePartType } from './models/MessagePartType';
export type { MessageReaction } from './models/MessageReaction';
export type { MessageRequestDto } from './models/MessageRequestDto';
export type { MessageResponse } from './models/MessageResponse';
export { MessageSender } from './models/MessageSender';
export type { MinecraftAccountDto } from './models/MinecraftAccountDto';
export type { MinecraftCustomStats } from './models/MinecraftCustomStats';
export type { MinecraftDetailsDto } from './models/MinecraftDetailsDto';
export type { MinecraftLinkDto } from './models/MinecraftLinkDto';
export type { MinecraftRegistrationDto } from './models/MinecraftRegistrationDto';
export type { MineReward } from './models/MineReward';
export { ModDependencyEntity } from './models/ModDependencyEntity';
export { ModFileEntity } from './models/ModFileEntity';
export { ModProjectEntity } from './models/ModProjectEntity';
export { ModrinthSourceDto } from './models/ModrinthSourceDto';
export { ModSearchHitEntity } from './models/ModSearchHitEntity';
export type { ModSearchPageEntity } from './models/ModSearchPageEntity';
export type { MonsterEntity } from './models/MonsterEntity';
export type { MoveCount } from './models/MoveCount';
export type { MoveEffect } from './models/MoveEffect';
export type { MovePokemonDto } from './models/MovePokemonDto';
export type { MoveTargetingInfo } from './models/MoveTargetingInfo';
export type { News } from './models/News';
export type { NewsComment } from './models/NewsComment';
export type { NewsIssue } from './models/NewsIssue';
export type { NewsletterSubscribeDto } from './models/NewsletterSubscribeDto';
export type { NewsResponse } from './models/NewsResponse';
export type { NewsStatusDto } from './models/NewsStatusDto';
export type { NoteFolder } from './models/NoteFolder';
export type { NotePreview } from './models/NotePreview';
export type { NoteTag } from './models/NoteTag';
export type { NoteVersion } from './models/NoteVersion';
export type { NotificationConfigDto } from './models/NotificationConfigDto';
export { NotificationEntity } from './models/NotificationEntity';
export type { NotificationResponseDto } from './models/NotificationResponseDto';
export type { NotificationsInboxDto } from './models/NotificationsInboxDto';
export { NotificationTargetDto } from './models/NotificationTargetDto';
export type { NPC } from './models/NPC';
export type { NPCData } from './models/NPCData';
export type { NPCUpdateResponse } from './models/NPCUpdateResponse';
export type { ObjetoMC } from './models/ObjetoMC';
export type { OpenLootBoxDto } from './models/OpenLootBoxDto';
export type { OpenLootBoxResponseDto } from './models/OpenLootBoxResponseDto';
export type { OrderActorDto } from './models/OrderActorDto';
export type { OrderAppDto } from './models/OrderAppDto';
export type { OrderItemDto } from './models/OrderItemDto';
export type { OrderLineInputDto } from './models/OrderLineInputDto';
export type { PackIdEntity } from './models/PackIdEntity';
export type { PackServerDto } from './models/PackServerDto';
export type { PackServerEntity } from './models/PackServerEntity';
export type { PackVersionEntity } from './models/PackVersionEntity';
export { Participant } from './models/Participant';
export type { PasaporteLadderRungEntity } from './models/PasaporteLadderRungEntity';
export { PasaporteLogroEntity } from './models/PasaporteLogroEntity';
export type { PasaporteProfileEntity } from './models/PasaporteProfileEntity';
export type { PasaporteSeasonEntity } from './models/PasaporteSeasonEntity';
export type { PasaporteSeasonInfoEntity } from './models/PasaporteSeasonInfoEntity';
export { PasaporteStandingEntity } from './models/PasaporteStandingEntity';
export type { PatchEpubMetadataDto } from './models/PatchEpubMetadataDto';
export type { PayMultaDto } from './models/PayMultaDto';
export type { PcMark } from './models/PcMark';
export type { Performance } from './models/Performance';
export { PersonalMetaComparisonDto } from './models/PersonalMetaComparisonDto';
export type { PersonalMetaComparisonRowDto } from './models/PersonalMetaComparisonRowDto';
export type { PersonRefEntity } from './models/PersonRefEntity';
export { PhaseAdvanceRule } from './models/PhaseAdvanceRule';
export { PhaseView } from './models/PhaseView';
export type { PlaceBidDto } from './models/PlaceBidDto';
export type { PlayerAppDto } from './models/PlayerAppDto';
export type { PlayerHistory } from './models/PlayerHistory';
export type { PlayerRankInfo } from './models/PlayerRankInfo';
export type { PlayerStatistics } from './models/PlayerStatistics';
export type { PlayerStats } from './models/PlayerStats';
export type { PlayGameDto } from './models/PlayGameDto';
export type { Point } from './models/Point';
export type { PokedexRegistry } from './models/PokedexRegistry';
export type { PokedexStatistics } from './models/PokedexStatistics';
export type { Pokemon } from './models/Pokemon';
export type { PokemonAbilities } from './models/PokemonAbilities';
export type { PokemonAbilityEntry } from './models/PokemonAbilityEntry';
export type { PokemonAggression } from './models/PokemonAggression';
export type { PokemonBattleStats } from './models/PokemonBattleStats';
export type { PokemonDimensions } from './models/PokemonDimensions';
export type { PokemonEvolution } from './models/PokemonEvolution';
export type { PokemonEvYields } from './models/PokemonEvYields';
export type { PokemonForm } from './models/PokemonForm';
export type { PokemonGenderProperties } from './models/PokemonGenderProperties';
export type { PokemonGigantamax } from './models/PokemonGigantamax';
export type { PokemonGiveRequestDto } from './models/PokemonGiveRequestDto';
export { PokemonImage } from './models/PokemonImage';
export type { PokemonLearnset } from './models/PokemonLearnset';
export type { PokemonMC } from './models/PokemonMC';
export type { PokemonModelLocator } from './models/PokemonModelLocator';
export type { PokemonMoveEntry } from './models/PokemonMoveEntry';
export type { PokemonMovement } from './models/PokemonMovement';
export type { PokemonPalette } from './models/PokemonPalette';
export type { PokemonSearchResult } from './models/PokemonSearchResult';
export type { PokemonSpawn } from './models/PokemonSpawn';
export type { PokemonUsageDetailDto } from './models/PokemonUsageDetailDto';
export type { PokemonUsageEntryDto } from './models/PokemonUsageEntryDto';
export type { PokemonW } from './models/PokemonW';
export type { PresetSlotDto } from './models/PresetSlotDto';
export type { PresetVersionDto } from './models/PresetVersionDto';
export type { ProposeReportDto } from './models/ProposeReportDto';
export type { PublicProfileEntity } from './models/PublicProfileEntity';
export { Quest } from './models/Quest';
export type { QuestCategory } from './models/QuestCategory';
export type { QuestObjective } from './models/QuestObjective';
export type { QuestRequirements } from './models/QuestRequirements';
export type { QuestReward } from './models/QuestReward';
export type { QuestSystemData } from './models/QuestSystemData';
export type { RaceParticipantDto } from './models/RaceParticipantDto';
export type { RankingEntry } from './models/RankingEntry';
export type { RarityRange } from './models/RarityRange';
export { ReactDto } from './models/ReactDto';
export type { ReactMessageDto } from './models/ReactMessageDto';
export type { RedeemInviteDto } from './models/RedeemInviteDto';
export type { RefreshTokenDto } from './models/RefreshTokenDto';
export type { Region } from './models/Region';
export type { RegisterCapturaDto } from './models/RegisterCapturaDto';
export type { RegisterMinecraftDto } from './models/RegisterMinecraftDto';
export type { RegisterParticipantDto } from './models/RegisterParticipantDto';
export { RegisterPokemonDto } from './models/RegisterPokemonDto';
export type { RemoveMemberDto } from './models/RemoveMemberDto';
export type { Replay } from './models/Replay';
export type { ReportMatchDto } from './models/ReportMatchDto';
export type { ResendVerificationDto } from './models/ResendVerificationDto';
export type { ReserveCajaResponse } from './models/ReserveCajaResponse';
export type { ResetPasswordDto } from './models/ResetPasswordDto';
export { ResolveApelacionDto } from './models/ResolveApelacionDto';
export { ResolveDenunciaDto } from './models/ResolveDenunciaDto';
export type { ResolvedFileEntity } from './models/ResolvedFileEntity';
export type { ResolveFileDto } from './models/ResolveFileDto';
export { ResourceType } from './models/ResourceType';
export type { RespondOfferDto } from './models/RespondOfferDto';
export type { RespondTradeDto } from './models/RespondTradeDto';
export { ReviewSuggestionDto } from './models/ReviewSuggestionDto';
export type { RevokeRoleDto } from './models/RevokeRoleDto';
export type { RewardsByType } from './models/RewardsByType';
export type { RookerDeleteResultEntity } from './models/RookerDeleteResultEntity';
export type { RookerFeedEntity } from './models/RookerFeedEntity';
export type { RookerFollowResultEntity } from './models/RookerFollowResultEntity';
export type { RookerNotificationEntity } from './models/RookerNotificationEntity';
export type { RookerNotificationListEntity } from './models/RookerNotificationListEntity';
export type { RookerPostAuthorEntity } from './models/RookerPostAuthorEntity';
export type { RookerPostBattleEntity } from './models/RookerPostBattleEntity';
export type { RookerPostCaptureEntity } from './models/RookerPostCaptureEntity';
export type { RookerPostCountsEntity } from './models/RookerPostCountsEntity';
export { RookerPostEntity } from './models/RookerPostEntity';
export { RookerPostViewerStateEntity } from './models/RookerPostViewerStateEntity';
export type { RookerProfileCountsEntity } from './models/RookerProfileCountsEntity';
export type { RookerProfileEntity } from './models/RookerProfileEntity';
export type { RookerReactionCountsEntity } from './models/RookerReactionCountsEntity';
export type { RookerSearchEntity } from './models/RookerSearchEntity';
export type { RookerSuggestionEntity } from './models/RookerSuggestionEntity';
export type { RookerSuggestionListEntity } from './models/RookerSuggestionListEntity';
export type { RookerThreadEntity } from './models/RookerThreadEntity';
export type { RookerTrainerStatsEntity } from './models/RookerTrainerStatsEntity';
export type { RookerTrendEntity } from './models/RookerTrendEntity';
export type { RookerTrendListEntity } from './models/RookerTrendListEntity';
export type { RosterMember } from './models/RosterMember';
export type { RosterMemberDto } from './models/RosterMemberDto';
export { RotomApp } from './models/RotomApp';
export type { RotomMessage } from './models/RotomMessage';
export type { RotomUser } from './models/RotomUser';
export type { SaveDocumentResponse } from './models/SaveDocumentResponse';
export type { SaveDungeonRunDto } from './models/SaveDungeonRunDto';
export type { SaveDungeonRunResponse } from './models/SaveDungeonRunResponse';
export type { SaveRaceDto } from './models/SaveRaceDto';
export type { SaveRaceResponse } from './models/SaveRaceResponse';
export type { ScheduleMatchesDto } from './models/ScheduleMatchesDto';
export type { ScoreboardRequirements } from './models/ScoreboardRequirements';
export type { SearchConsoleResult } from './models/SearchConsoleResult';
export type { SearchLocalGamesResult } from './models/SearchLocalGamesResult';
export type { SendMegafoniaDto } from './models/SendMegafoniaDto';
export type { SendMessageDto } from './models/SendMessageDto';
export type { SendNotificationDto } from './models/SendNotificationDto';
export type { SeriesCardsGroup } from './models/SeriesCardsGroup';
export { SeriesDto } from './models/SeriesDto';
export { SeriesGameDto } from './models/SeriesGameDto';
export { SessionDto } from './models/SessionDto';
export type { SessionSmartRotomUserEntity } from './models/SessionSmartRotomUserEntity';
export type { SessionUserEntity } from './models/SessionUserEntity';
export type { SetBalanceDto } from './models/SetBalanceDto';
export type { SetBrowserTunnelDto } from './models/SetBrowserTunnelDto';
export type { SetChatMutedDto } from './models/SetChatMutedDto';
export type { SetChatPinnedDto } from './models/SetChatPinnedDto';
export type { SetLockedDto } from './models/SetLockedDto';
export type { SetPinnedDto } from './models/SetPinnedDto';
export { SetStatusDto } from './models/SetStatusDto';
export type { SharexUploadDto } from './models/SharexUploadDto';
export type { SiteStatsEntity } from './models/SiteStatsEntity';
export type { SkillEntity } from './models/SkillEntity';
export type { SmartRotomUserEntity } from './models/SmartRotomUserEntity';
export type { SmogonSnapshotDto } from './models/SmogonSnapshotDto';
export type { SolveThreadDto } from './models/SolveThreadDto';
export type { SpawnCondition } from './models/SpawnCondition';
export type { SpawnInfo } from './models/SpawnInfo';
export { SpeciesTeamEntryDto } from './models/SpeciesTeamEntryDto';
export type { SpeedTierEntryDto } from './models/SpeedTierEntryDto';
export type { SpeedTierValuesDto } from './models/SpeedTierValuesDto';
export type { SpinnerItemDto } from './models/SpinnerItemDto';
export type { SpreadEntryDto } from './models/SpreadEntryDto';
export type { SpreadUsageDto } from './models/SpreadUsageDto';
export { StarBankAccount } from './models/StarBankAccount';
export type { StarbankAccountEntity } from './models/StarbankAccountEntity';
export { StarBankTransaction } from './models/StarBankTransaction';
export type { StatSpreadDto } from './models/StatSpreadDto';
export type { SubmitScoreDto } from './models/SubmitScoreDto';
export type { SuccessResponse } from './models/SuccessResponse';
export { SuggestionEntity } from './models/SuggestionEntity';
export { SystemHealthResponse } from './models/SystemHealthResponse';
export type { TakeTripDto } from './models/TakeTripDto';
export type { TaxiConfig } from './models/TaxiConfig';
export type { TaxiStop } from './models/TaxiStop';
export type { TcgCard } from './models/TcgCard';
export type { TcgCardAttack } from './models/TcgCardAttack';
export type { TcgCardBooster } from './models/TcgCardBooster';
export type { TcgCardLegal } from './models/TcgCardLegal';
export type { TcgCardVariants } from './models/TcgCardVariants';
export type { TcgCardWeakness } from './models/TcgCardWeakness';
export type { TcgSeries } from './models/TcgSeries';
export type { TcgSet } from './models/TcgSet';
export type { TcgUserCard } from './models/TcgUserCard';
export type { TcgUserCardHistory } from './models/TcgUserCardHistory';
export { Team } from './models/Team';
export type { TeamLeaderboardEntry } from './models/TeamLeaderboardEntry';
export { TeamMember } from './models/TeamMember';
export type { TeamPresetDto } from './models/TeamPresetDto';
export type { TeamsheetDto } from './models/TeamsheetDto';
export type { TeamsheetMonDto } from './models/TeamsheetMonDto';
export type { TeamSnapshotDto } from './models/TeamSnapshotDto';
export type { TeleportPlayerDto } from './models/TeleportPlayerDto';
export type { TesoreriaBreakdownItemEntity } from './models/TesoreriaBreakdownItemEntity';
export type { TesoreriaSeriePuntoEntity } from './models/TesoreriaSeriePuntoEntity';
export { TournamentDetail } from './models/TournamentDetail';
export type { TournamentImportStartDto } from './models/TournamentImportStartDto';
export { TournamentSummary } from './models/TournamentSummary';
export type { TrackerSyncDataDto } from './models/TrackerSyncDataDto';
export type { TrainerDefeatMoneyDto } from './models/TrainerDefeatMoneyDto';
export type { TransferFromMainDto } from './models/TransferFromMainDto';
export type { TripResult } from './models/TripResult';
export type { TwitchCallbackDto } from './models/TwitchCallbackDto';
export type { UnclaimedItem } from './models/UnclaimedItem';
export type { UnreadCountEntity } from './models/UnreadCountEntity';
export { UpdateAchievementDto } from './models/UpdateAchievementDto';
export type { UpdateAnuncioDto } from './models/UpdateAnuncioDto';
export { UpdateApelacionDto } from './models/UpdateApelacionDto';
export { UpdateAppDto } from './models/UpdateAppDto';
export type { UpdateBattleTeamDto } from './models/UpdateBattleTeamDto';
export { UpdateBuscadoDto } from './models/UpdateBuscadoDto';
export type { UpdateCartelDto } from './models/UpdateCartelDto';
export { UpdateDenunciaDto } from './models/UpdateDenunciaDto';
export type { UpdateDex } from './models/UpdateDex';
export type { UpdateDexDto } from './models/UpdateDexDto';
export type { UpdateDocumentDto } from './models/UpdateDocumentDto';
export type { UpdateEspecieDto } from './models/UpdateEspecieDto';
export { UpdateEventDto } from './models/UpdateEventDto';
export { UpdateEventoDto } from './models/UpdateEventoDto';
export { UpdateExpedienteDto } from './models/UpdateExpedienteDto';
export type { UpdateFolderDto } from './models/UpdateFolderDto';
export type { UpdateGameDto } from './models/UpdateGameDto';
export { UpdateListingDto } from './models/UpdateListingDto';
export type { UpdateMangaConfigDto } from './models/UpdateMangaConfigDto';
export type { UpdateMessageDto } from './models/UpdateMessageDto';
export type { UpdateMultaDto } from './models/UpdateMultaDto';
export type { UpdateNewsDto } from './models/UpdateNewsDto';
export type { UpdateNPCsDto } from './models/UpdateNPCsDto';
export type { UpdateNpcSkinDto } from './models/UpdateNpcSkinDto';
export type { UpdateObraDto } from './models/UpdateObraDto';
export { UpdatePackDto } from './models/UpdatePackDto';
export type { UpdateParcelaDto } from './models/UpdateParcelaDto';
export { UpdateParticipantDto } from './models/UpdateParticipantDto';
export { UpdatePatrullaDto } from './models/UpdatePatrullaDto';
export { UpdatePhaseDto } from './models/UpdatePhaseDto';
export type { UpdateProfileDto } from './models/UpdateProfileDto';
export type { UpdateProgressDto } from './models/UpdateProgressDto';
export type { UpdaterFeedEntity } from './models/UpdaterFeedEntity';
export type { UpdaterPlatformEntity } from './models/UpdaterPlatformEntity';
export { UpdateSeriesStatusDto } from './models/UpdateSeriesStatusDto';
export type { UpdateSmartrotomUserDto } from './models/UpdateSmartrotomUserDto';
export { UpdateSubastaDto } from './models/UpdateSubastaDto';
export type { UpdateTagDto } from './models/UpdateTagDto';
export type { UpdateTasaDto } from './models/UpdateTasaDto';
export type { UpdateTeamDto } from './models/UpdateTeamDto';
export { UpdateTournamentDto } from './models/UpdateTournamentDto';
export type { UpdateUserCardQuantityDto } from './models/UpdateUserCardQuantityDto';
export type { UpdateUserDto } from './models/UpdateUserDto';
export type { UpdateWingullNpcsDto } from './models/UpdateWingullNpcsDto';
export type { UpdateZonaDto } from './models/UpdateZonaDto';
export type { UploadFileDto } from './models/UploadFileDto';
export type { UploadImageDto } from './models/UploadImageDto';
export type { UploadNpcImageDto } from './models/UploadNpcImageDto';
export type { UpsertPcMarkDto } from './models/UpsertPcMarkDto';
export { UpsertRegulationDto } from './models/UpsertRegulationDto';
export type { UpsertSeriesDto } from './models/UpsertSeriesDto';
export type { UrlBodyDto } from './models/UrlBodyDto';
export { UrlSourceDto } from './models/UrlSourceDto';
export type { UsageEntryDto } from './models/UsageEntryDto';
export type { UsageStatDto } from './models/UsageStatDto';
export type { UserAchievement } from './models/UserAchievement';
export { UserActivityItemEntity } from './models/UserActivityItemEntity';
export type { UserInitializationDataDto } from './models/UserInitializationDataDto';
export type { UserLoginDto } from './models/UserLoginDto';
export type { UserQuestData } from './models/UserQuestData';
export type { UserRolesResponseEntity } from './models/UserRolesResponseEntity';
export type { UsersPaginatedResponseEntity } from './models/UsersPaginatedResponseEntity';
export type { UserStatistics } from './models/UserStatistics';
export type { UserStatisticsEntity } from './models/UserStatisticsEntity';
export type { UserTrophiesEntity } from './models/UserTrophiesEntity';
export { UserTrophyEntity } from './models/UserTrophyEntity';
export type { UserValidationResponseEntity } from './models/UserValidationResponseEntity';
export type { UserValidationResult } from './models/UserValidationResult';
export type { UserWithAccounts } from './models/UserWithAccounts';
export type { UserWithIntegrationsEntity } from './models/UserWithIntegrationsEntity';
export type { UuidDto } from './models/UuidDto';
export type { ValidateCacheDto } from './models/ValidateCacheDto';
export type { ValuateDto } from './models/ValuateDto';
export type { VerifyEmailDto } from './models/VerifyEmailDto';
export type { VerifyJoinDto } from './models/VerifyJoinDto';
export { VgcIngestionJobDto } from './models/VgcIngestionJobDto';
export type { VgcMetaSlotDto } from './models/VgcMetaSlotDto';
export type { VgcPokemonDto } from './models/VgcPokemonDto';
export type { VoteObraDto } from './models/VoteObraDto';
export type { WarmupCacheDto } from './models/WarmupCacheDto';
export type { WatchlistDto } from './models/WatchlistDto';
export type { WeaponEntity } from './models/WeaponEntity';
export type { WeaponTreeEntity } from './models/WeaponTreeEntity';
export type { WeaponTreeNodeEntity } from './models/WeaponTreeNodeEntity';
export type { Weather } from './models/Weather';
export type { WigglypopBidEntity } from './models/WigglypopBidEntity';
export type { WigglypopItemCatalogEntity } from './models/WigglypopItemCatalogEntity';
export type { WigglypopListingEntity } from './models/WigglypopListingEntity';
export type { WigglypopListingItemEntity } from './models/WigglypopListingItemEntity';
export type { WigglypopListingListEntity } from './models/WigglypopListingListEntity';
export type { WigglypopListingMonEntity } from './models/WigglypopListingMonEntity';
export type { WigglypopOfferEntity } from './models/WigglypopOfferEntity';
export type { WigglypopOrderEntity } from './models/WigglypopOrderEntity';
export type { WigglypopOrderLineEntity } from './models/WigglypopOrderLineEntity';
export type { WigglypopPersonRef } from './models/WigglypopPersonRef';
export type { WigglypopReviewEntity } from './models/WigglypopReviewEntity';
export type { WigglypopSellerEntity } from './models/WigglypopSellerEntity';
export type { WigglypopSuccessEntity } from './models/WigglypopSuccessEntity';
export type { WigglypopTradeOfferEntity } from './models/WigglypopTradeOfferEntity';
export { WigglypopValuationEntity } from './models/WigglypopValuationEntity';
export type { WigglypopWatchlistEntity } from './models/WigglypopWatchlistEntity';
export type { WigglypopWatchResultEntity } from './models/WigglypopWatchResultEntity';
export type { ZMove } from './models/ZMove';
