/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type { AbilityCount } from './models/AbilityCount';
export type { AbilityInfo } from './models/AbilityInfo';
export { Achievement } from './models/Achievement';
export type { AchievementStatusResponse } from './models/AchievementStatusResponse';
export { AchievementWithProgress } from './models/AchievementWithProgress';
export { ActivityItemEntity } from './models/ActivityItemEntity';
export type { AddInventoryItemDto } from './models/AddInventoryItemDto';
export type { AddLimitlessTournamentDto } from './models/AddLimitlessTournamentDto';
export type { AddMemberDto } from './models/AddMemberDto';
export type { AddNoteToUserDto } from './models/AddNoteToUserDto';
export type { AddUserCardDto } from './models/AddUserCardDto';
export type { ApiResponseEntity } from './models/ApiResponseEntity';
export { ArcadeInventoryItem } from './models/ArcadeInventoryItem';
export type { ArcadeInventoryResponse } from './models/ArcadeInventoryResponse';
export type { ArcadeStreak } from './models/ArcadeStreak';
export type { ArcadeStreakClaim } from './models/ArcadeStreakClaim';
export type { ArceuSpeakEntity } from './models/ArceuSpeakEntity';
export type { ArceusspeakDto } from './models/ArceusspeakDto';
export type { ArmorEntity } from './models/ArmorEntity';
export type { AuthenticationResultEntity } from './models/AuthenticationResultEntity';
export type { AuthLoginResponseEntity } from './models/AuthLoginResponseEntity';
export type { AuthRefreshResponseEntity } from './models/AuthRefreshResponseEntity';
export type { AuthRefreshSmartRotomUserEntity } from './models/AuthRefreshSmartRotomUserEntity';
export type { AuthRefreshUserEntity } from './models/AuthRefreshUserEntity';
export type { AuthUserEntity } from './models/AuthUserEntity';
export type { BaseStatsDto } from './models/BaseStatsDto';
export type { BatchFetchResultDto } from './models/BatchFetchResultDto';
export type { BatchUsersDto } from './models/BatchUsersDto';
export type { BatchUsersRequestDto } from './models/BatchUsersRequestDto';
export type { BattleAchievementDto } from './models/BattleAchievementDto';
export type { BattleAchievementResponse } from './models/BattleAchievementResponse';
export type { BiomeSpawnCollection } from './models/BiomeSpawnCollection';
export type { BiomeSpawnEntry } from './models/BiomeSpawnEntry';
export type { BoffMediaUserEntity } from './models/BoffMediaUserEntity';
export type { BulkDownloadResult } from './models/BulkDownloadResult';
export type { CacheOperationResultEntity } from './models/CacheOperationResultEntity';
export type { CacheRefreshResponse } from './models/CacheRefreshResponse';
export type { CacheStatusResponse } from './models/CacheStatusResponse';
export type { CallResponse } from './models/CallResponse';
export type { CallSession } from './models/CallSession';
export { CallUser } from './models/CallUser';
export type { CatalogSearchConsoleResult } from './models/CatalogSearchConsoleResult';
export type { CatalogSearchResult } from './models/CatalogSearchResult';
export type { ChampionsPasteDetailDto } from './models/ChampionsPasteDetailDto';
export { ChampionsRegulationDto } from './models/ChampionsRegulationDto';
export type { ChangePasswordDto } from './models/ChangePasswordDto';
export type { ChapterEntry } from './models/ChapterEntry';
export type { CharmEntity } from './models/CharmEntity';
export type { CharmRankEntity } from './models/CharmRankEntity';
export type { Chat } from './models/Chat';
export type { ChatMember } from './models/ChatMember';
export type { ChatMessage } from './models/ChatMessage';
export type { CheckAchievementDto } from './models/CheckAchievementDto';
export type { ClaimItemsDto } from './models/ClaimItemsDto';
export type { ClaimItemsResponseDto } from './models/ClaimItemsResponseDto';
export type { ClaimResponse } from './models/ClaimResponse';
export type { ClaimRewardDto } from './models/ClaimRewardDto';
export type { ClaimRewardsDto } from './models/ClaimRewardsDto';
export type { ConsumeInventoryItemDto } from './models/ConsumeInventoryItemDto';
export type { ConvertChapterDto } from './models/ConvertChapterDto';
export type { CountResultDto } from './models/CountResultDto';
export { CreateAchievementDto } from './models/CreateAchievementDto';
export { CreateAppDto } from './models/CreateAppDto';
export type { CreateChatDto } from './models/CreateChatDto';
export type { CreateChatResponse } from './models/CreateChatResponse';
export type { CreateDocumentDto } from './models/CreateDocumentDto';
export type { CreateDocumentDtoWithUuid } from './models/CreateDocumentDtoWithUuid';
export { CreateEventDto } from './models/CreateEventDto';
export type { CreateGameDto } from './models/CreateGameDto';
export { CreateMatchDto } from './models/CreateMatchDto';
export { CreateMessageDto } from './models/CreateMessageDto';
export type { CreateMessageResponse } from './models/CreateMessageResponse';
export type { CreateNewsDto } from './models/CreateNewsDto';
export type { CreateNoteResponse } from './models/CreateNoteResponse';
export { CreateNotificationDto } from './models/CreateNotificationDto';
export type { CreatePostDto } from './models/CreatePostDto';
export type { CreatePresetDto } from './models/CreatePresetDto';
export type { CreateReplayDto } from './models/CreateReplayDto';
export type { CreateReplayResponse } from './models/CreateReplayResponse';
export { CreateSessionDto } from './models/CreateSessionDto';
export type { CreateShopTransactionDto } from './models/CreateShopTransactionDto';
export type { CreateSmartrotomUserDto } from './models/CreateSmartrotomUserDto';
export type { CreateSuggestionDto } from './models/CreateSuggestionDto';
export type { CreateSuggestionResultEntity } from './models/CreateSuggestionResultEntity';
export type { CreateTeamDto } from './models/CreateTeamDto';
export type { CreateThreadDto } from './models/CreateThreadDto';
export type { CreateTransferDto } from './models/CreateTransferDto';
export type { CreateUserDto } from './models/CreateUserDto';
export type { CreateUserReplayDto } from './models/CreateUserReplayDto';
export type { CreateUserReplayResponse } from './models/CreateUserReplayResponse';
export type { CronConfigDto } from './models/CronConfigDto';
export type { DailyRewardBox } from './models/DailyRewardBox';
export { DailyRewardItem } from './models/DailyRewardItem';
export type { DailyRewardsConfig } from './models/DailyRewardsConfig';
export type { DecorationEntity } from './models/DecorationEntity';
export type { DeleteFileDto } from './models/DeleteFileDto';
export type { DeleteMessageDto } from './models/DeleteMessageDto';
export type { DetailedPokedexStatistics } from './models/DetailedPokedexStatistics';
export type { Dialogue } from './models/Dialogue';
export type { DivergenceResultDto } from './models/DivergenceResultDto';
export { DivergenceRowDto } from './models/DivergenceRowDto';
export type { Document } from './models/Document';
export { DownloadAllGamesDto } from './models/DownloadAllGamesDto';
export type { DownloadChaptersDto } from './models/DownloadChaptersDto';
export type { DownloadMangaNovelDto } from './models/DownloadMangaNovelDto';
export type { DownloadResult } from './models/DownloadResult';
export { DownloadSelectedGamesDto } from './models/DownloadSelectedGamesDto';
export type { DropRateEntry } from './models/DropRateEntry';
export type { DropRates } from './models/DropRates';
export type { EditPostDto } from './models/EditPostDto';
export type { EndCallDto } from './models/EndCallDto';
export type { EndGameDto } from './models/EndGameDto';
export type { EnergyStatus } from './models/EnergyStatus';
export type { EpubMetadataDto } from './models/EpubMetadataDto';
export type { EuropeAggregateResult } from './models/EuropeAggregateResult';
export { Event } from './models/Event';
export type { EvolutionMethod } from './models/EvolutionMethod';
export type { EvolutionNode } from './models/EvolutionNode';
export type { EvolutionTree } from './models/EvolutionTree';
export type { FactionRequirements } from './models/FactionRequirements';
export { FetchSmogonDto } from './models/FetchSmogonDto';
export type { FicusAiHealthEntity } from './models/FicusAiHealthEntity';
export type { FicusAiUserStatsEntity } from './models/FicusAiUserStatsEntity';
export type { FicusMessageContentDto } from './models/FicusMessageContentDto';
export { FileDownloadEntry } from './models/FileDownloadEntry';
export { FindOrCreateResult } from './models/FindOrCreateResult';
export type { ForgotPasswordDto } from './models/ForgotPasswordDto';
export { ForumAuthor } from './models/ForumAuthor';
export type { ForumCategory } from './models/ForumCategory';
export { ForumMember } from './models/ForumMember';
export type { ForumPost } from './models/ForumPost';
export type { ForumPostList } from './models/ForumPostList';
export type { ForumStats } from './models/ForumStats';
export type { ForumThread } from './models/ForumThread';
export type { ForumThreadList } from './models/ForumThreadList';
export type { ForumVoteResult } from './models/ForumVoteResult';
export { FullMove } from './models/FullMove';
export type { FullUserEntity } from './models/FullUserEntity';
export type { Game } from './models/Game';
export type { GameEndResponse } from './models/GameEndResponse';
export type { GameFileEntry } from './models/GameFileEntry';
export type { GameRewardDto } from './models/GameRewardDto';
export type { GameStartResponse } from './models/GameStartResponse';
export type { Gen9DataDto } from './models/Gen9DataDto';
export type { Gen9MoveDto } from './models/Gen9MoveDto';
export type { GetAchievementByIdDto } from './models/GetAchievementByIdDto';
export type { GetAchievementsDto } from './models/GetAchievementsDto';
export type { GetNewsDto } from './models/GetNewsDto';
export type { GetPlayerAppsDto } from './models/GetPlayerAppsDto';
export type { GetReplayDto } from './models/GetReplayDto';
export type { GetUserDocumentsDto } from './models/GetUserDocumentsDto';
export type { GetUserQuestsDto } from './models/GetUserQuestsDto';
export type { GiveLootboxDto } from './models/GiveLootboxDto';
export type { GoogleAuthDto } from './models/GoogleAuthDto';
export type { GoogleCallbackDto } from './models/GoogleCallbackDto';
export type { HeldItem } from './models/HeldItem';
export type { ImageExistsResponse } from './models/ImageExistsResponse';
export type { ImageUploadResponse } from './models/ImageUploadResponse';
export type { ImportJobStatusDto } from './models/ImportJobStatusDto';
export type { InitializationResult } from './models/InitializationResult';
export type { InitiateCallDto } from './models/InitiateCallDto';
export type { IntegratedUserCreationResultEntity } from './models/IntegratedUserCreationResultEntity';
export type { IntegrationsEntity } from './models/IntegrationsEntity';
export type { InventoryItemGroup } from './models/InventoryItemGroup';
export type { ItemSprite } from './models/ItemSprite';
export type { JoinEventDto } from './models/JoinEventDto';
export type { JoinTeamDto } from './models/JoinTeamDto';
export type { LeaderboardEntry } from './models/LeaderboardEntry';
export type { LimitlessPlayerDto } from './models/LimitlessPlayerDto';
export type { LimitlessPlayerTeamDto } from './models/LimitlessPlayerTeamDto';
export type { LimitlessTournamentDto } from './models/LimitlessTournamentDto';
export type { LocalChaptersResult } from './models/LocalChaptersResult';
export { Locale } from './models/Locale';
export type { LocalGameEntry } from './models/LocalGameEntry';
export type { LocalGamesResult } from './models/LocalGamesResult';
export type { LoginMcDto } from './models/LoginMcDto';
export type { LootboxBoxConfig } from './models/LootboxBoxConfig';
export type { LootboxBoxesCollection } from './models/LootboxBoxesCollection';
export type { LootboxConfigEntity } from './models/LootboxConfigEntity';
export { LootboxItemConfig } from './models/LootboxItemConfig';
export type { MangaChapter } from './models/MangaChapter';
export type { MangaDetail } from './models/MangaDetail';
export type { MangaResult } from './models/MangaResult';
export type { MangaSearchResult } from './models/MangaSearchResult';
export type { MarkMessageReadDto } from './models/MarkMessageReadDto';
export type { MarkReadBodyDto } from './models/MarkReadBodyDto';
export { MatchDto } from './models/MatchDto';
export { MatchNoteDto } from './models/MatchNoteDto';
export { MatchSlotDto } from './models/MatchSlotDto';
export type { MessagePartDto } from './models/MessagePartDto';
export { MessagePartType } from './models/MessagePartType';
export type { MessageRequestDto } from './models/MessageRequestDto';
export type { MessageResponse } from './models/MessageResponse';
export { MessageSender } from './models/MessageSender';
export type { MinecraftAccountDto } from './models/MinecraftAccountDto';
export type { MinecraftCustomStats } from './models/MinecraftCustomStats';
export type { MinecraftDetailsDto } from './models/MinecraftDetailsDto';
export type { MinecraftLinkDto } from './models/MinecraftLinkDto';
export type { MinecraftRegistrationDto } from './models/MinecraftRegistrationDto';
export type { MineReward } from './models/MineReward';
export type { MonsterEntity } from './models/MonsterEntity';
export type { MoveCount } from './models/MoveCount';
export type { MoveEffect } from './models/MoveEffect';
export type { MoveTargetingInfo } from './models/MoveTargetingInfo';
export type { News } from './models/News';
export type { NewsResponse } from './models/NewsResponse';
export type { NewsStatusDto } from './models/NewsStatusDto';
export type { NotePreview } from './models/NotePreview';
export type { NotificationConfigDto } from './models/NotificationConfigDto';
export { NotificationEntity } from './models/NotificationEntity';
export type { NotificationResponseDto } from './models/NotificationResponseDto';
export type { NotificationsInboxDto } from './models/NotificationsInboxDto';
export { NotificationTargetDto } from './models/NotificationTargetDto';
export type { NPC } from './models/NPC';
export type { NPCData } from './models/NPCData';
export type { NPCUpdateResponse } from './models/NPCUpdateResponse';
export type { Object } from './models/Object';
export type { OpenLootBoxDto } from './models/OpenLootBoxDto';
export type { OpenLootBoxResponseDto } from './models/OpenLootBoxResponseDto';
export type { OrderAppDto } from './models/OrderAppDto';
export type { OrderItemDto } from './models/OrderItemDto';
export { Participant } from './models/Participant';
export type { PatchEpubMetadataDto } from './models/PatchEpubMetadataDto';
export type { Performance } from './models/Performance';
export { PersonalMetaComparisonDto } from './models/PersonalMetaComparisonDto';
export type { PersonalMetaComparisonRowDto } from './models/PersonalMetaComparisonRowDto';
export type { PlayerAppDto } from './models/PlayerAppDto';
export type { PlayerHistory } from './models/PlayerHistory';
export type { PlayerRankInfo } from './models/PlayerRankInfo';
export type { PlayerStatistics } from './models/PlayerStatistics';
export type { PlayerStats } from './models/PlayerStats';
export type { PlayGameDto } from './models/PlayGameDto';
export type { Point } from './models/Point';
export type { PokedexRegistry } from './models/PokedexRegistry';
export type { PokedexStatistics } from './models/PokedexStatistics';
export type { Pokemon } from './models/Pokemon';
export type { PokemonAbilities } from './models/PokemonAbilities';
export type { PokemonAbilityEntry } from './models/PokemonAbilityEntry';
export type { PokemonAggression } from './models/PokemonAggression';
export type { PokemonBattleStats } from './models/PokemonBattleStats';
export type { PokemonDimensions } from './models/PokemonDimensions';
export type { PokemonEvolution } from './models/PokemonEvolution';
export type { PokemonEvYields } from './models/PokemonEvYields';
export type { PokemonForm } from './models/PokemonForm';
export type { PokemonGenderProperties } from './models/PokemonGenderProperties';
export type { PokemonGigantamax } from './models/PokemonGigantamax';
export type { PokemonGiveRequestDto } from './models/PokemonGiveRequestDto';
export { PokemonImage } from './models/PokemonImage';
export type { PokemonLearnset } from './models/PokemonLearnset';
export type { PokemonModelLocator } from './models/PokemonModelLocator';
export type { PokemonMoveEntry } from './models/PokemonMoveEntry';
export type { PokemonMovement } from './models/PokemonMovement';
export type { PokemonPalette } from './models/PokemonPalette';
export type { PokemonSearchResult } from './models/PokemonSearchResult';
export type { PokemonSpawn } from './models/PokemonSpawn';
export type { PokemonUsageDetailDto } from './models/PokemonUsageDetailDto';
export type { PokemonUsageEntryDto } from './models/PokemonUsageEntryDto';
export type { PokemonW } from './models/PokemonW';
export type { PresetSlotDto } from './models/PresetSlotDto';
export type { PresetVersionDto } from './models/PresetVersionDto';
export type { PublicProfileEntity } from './models/PublicProfileEntity';
export { Quest } from './models/Quest';
export type { QuestCategory } from './models/QuestCategory';
export type { QuestObjective } from './models/QuestObjective';
export type { QuestRequirements } from './models/QuestRequirements';
export type { QuestReward } from './models/QuestReward';
export type { QuestSystemData } from './models/QuestSystemData';
export type { RankingEntry } from './models/RankingEntry';
export type { RarityRange } from './models/RarityRange';
export type { RefreshTokenDto } from './models/RefreshTokenDto';
export type { Region } from './models/Region';
export type { RegisterMinecraftDto } from './models/RegisterMinecraftDto';
export { RegisterPokemonDto } from './models/RegisterPokemonDto';
export type { RemoveMemberDto } from './models/RemoveMemberDto';
export type { Replay } from './models/Replay';
export type { ResendVerificationDto } from './models/ResendVerificationDto';
export type { ResetPasswordDto } from './models/ResetPasswordDto';
export { ResourceType } from './models/ResourceType';
export type { ResultadoCarreraDto } from './models/ResultadoCarreraDto';
export { ReviewSuggestionDto } from './models/ReviewSuggestionDto';
export type { RewardsByType } from './models/RewardsByType';
export type { RotomMessage } from './models/RotomMessage';
export type { SaveDocumentResponse } from './models/SaveDocumentResponse';
export type { ScoreboardRequirements } from './models/ScoreboardRequirements';
export type { SearchConsoleResult } from './models/SearchConsoleResult';
export type { SearchLocalGamesResult } from './models/SearchLocalGamesResult';
export type { SendMessageDto } from './models/SendMessageDto';
export type { SendNotificationDto } from './models/SendNotificationDto';
export type { SeriesCardsGroup } from './models/SeriesCardsGroup';
export { SeriesDto } from './models/SeriesDto';
export { SeriesGameDto } from './models/SeriesGameDto';
export { SessionDto } from './models/SessionDto';
export type { SessionSmartRotomUserEntity } from './models/SessionSmartRotomUserEntity';
export type { SessionUserEntity } from './models/SessionUserEntity';
export type { SetBrowserTunnelDto } from './models/SetBrowserTunnelDto';
export type { SetLockedDto } from './models/SetLockedDto';
export type { SetPinnedDto } from './models/SetPinnedDto';
export type { SharexUploadDto } from './models/SharexUploadDto';
export type { SiteStatsEntity } from './models/SiteStatsEntity';
export type { SkillEntity } from './models/SkillEntity';
export { SmartRotomApp } from './models/SmartRotomApp';
export type { SmartRotomUser } from './models/SmartRotomUser';
export type { SmartRotomUserEntity } from './models/SmartRotomUserEntity';
export type { SmogonSnapshotDto } from './models/SmogonSnapshotDto';
export type { SolveThreadDto } from './models/SolveThreadDto';
export type { SpawnCondition } from './models/SpawnCondition';
export type { SpawnInfo } from './models/SpawnInfo';
export { SpeciesTeamEntryDto } from './models/SpeciesTeamEntryDto';
export type { SpeedTierEntryDto } from './models/SpeedTierEntryDto';
export type { SpeedTierValuesDto } from './models/SpeedTierValuesDto';
export type { SpinnerItemDto } from './models/SpinnerItemDto';
export type { SpreadEntryDto } from './models/SpreadEntryDto';
export type { SpreadUsageDto } from './models/SpreadUsageDto';
export { StarBankAccount } from './models/StarBankAccount';
export type { StarbankAccountEntity } from './models/StarbankAccountEntity';
export { StarBankTransaction } from './models/StarBankTransaction';
export type { StatSpreadDto } from './models/StatSpreadDto';
export type { SuccessResponse } from './models/SuccessResponse';
export { SuggestionEntity } from './models/SuggestionEntity';
export { SystemHealthResponse } from './models/SystemHealthResponse';
export type { TaxiStop } from './models/TaxiStop';
export type { TcgCard } from './models/TcgCard';
export type { TcgCardAttack } from './models/TcgCardAttack';
export type { TcgCardBooster } from './models/TcgCardBooster';
export type { TcgCardLegal } from './models/TcgCardLegal';
export type { TcgCardVariants } from './models/TcgCardVariants';
export type { TcgCardWeakness } from './models/TcgCardWeakness';
export type { TcgSeries } from './models/TcgSeries';
export type { TcgSet } from './models/TcgSet';
export { Team } from './models/Team';
export type { TeamLeaderboardEntry } from './models/TeamLeaderboardEntry';
export { TeamMember } from './models/TeamMember';
export type { TeamPresetDto } from './models/TeamPresetDto';
export type { TeamSnapshotDto } from './models/TeamSnapshotDto';
export type { TeleportPlayerDto } from './models/TeleportPlayerDto';
export type { TournamentImportStartDto } from './models/TournamentImportStartDto';
export type { TrackerSyncDataDto } from './models/TrackerSyncDataDto';
export type { TrainerDefeatMoneyDto } from './models/TrainerDefeatMoneyDto';
export type { TransferFromMainDto } from './models/TransferFromMainDto';
export type { UnclaimedItem } from './models/UnclaimedItem';
export type { UnreadCountEntity } from './models/UnreadCountEntity';
export { UpdateAchievementDto } from './models/UpdateAchievementDto';
export { UpdateAppDto } from './models/UpdateAppDto';
export type { UpdateBattleTeamDto } from './models/UpdateBattleTeamDto';
export type { UpdateDex } from './models/UpdateDex';
export type { UpdateDexDto } from './models/UpdateDexDto';
export type { UpdateDocumentDto } from './models/UpdateDocumentDto';
export { UpdateEventDto } from './models/UpdateEventDto';
export type { UpdateGameDto } from './models/UpdateGameDto';
export type { UpdateMangaConfigDto } from './models/UpdateMangaConfigDto';
export type { UpdateMessageDto } from './models/UpdateMessageDto';
export type { UpdateNewsDto } from './models/UpdateNewsDto';
export type { UpdateNPCsDto } from './models/UpdateNPCsDto';
export type { UpdateProgressDto } from './models/UpdateProgressDto';
export { UpdateSeriesStatusDto } from './models/UpdateSeriesStatusDto';
export type { UpdateSmartrotomUserDto } from './models/UpdateSmartrotomUserDto';
export type { UpdateTeamDto } from './models/UpdateTeamDto';
export type { UpdateUserCardQuantityDto } from './models/UpdateUserCardQuantityDto';
export type { UpdateUserDto } from './models/UpdateUserDto';
export type { UploadFileDto } from './models/UploadFileDto';
export type { UploadImageDto } from './models/UploadImageDto';
export type { UploadNpcImageDto } from './models/UploadNpcImageDto';
export { UpsertRegulationDto } from './models/UpsertRegulationDto';
export type { UpsertSeriesDto } from './models/UpsertSeriesDto';
export type { UrlBodyDto } from './models/UrlBodyDto';
export type { UsageEntryDto } from './models/UsageEntryDto';
export type { UsageStatDto } from './models/UsageStatDto';
export type { UserAchievement } from './models/UserAchievement';
export { UserActivityItemEntity } from './models/UserActivityItemEntity';
export type { UserCard } from './models/UserCard';
export type { UserCardHistory } from './models/UserCardHistory';
export type { UserInitializationDataDto } from './models/UserInitializationDataDto';
export type { UserLoginDto } from './models/UserLoginDto';
export type { UserQuestData } from './models/UserQuestData';
export type { UserRolesResponseEntity } from './models/UserRolesResponseEntity';
export type { UsersPaginatedResponseEntity } from './models/UsersPaginatedResponseEntity';
export type { UserStatistics } from './models/UserStatistics';
export type { UserStatisticsEntity } from './models/UserStatisticsEntity';
export type { UserTrophiesEntity } from './models/UserTrophiesEntity';
export { UserTrophyEntity } from './models/UserTrophyEntity';
export type { UserValidationResponseEntity } from './models/UserValidationResponseEntity';
export type { UserValidationResult } from './models/UserValidationResult';
export type { UserWithAccounts } from './models/UserWithAccounts';
export type { UserWithIntegrationsEntity } from './models/UserWithIntegrationsEntity';
export type { UuidDto } from './models/UuidDto';
export type { ValidateCacheDto } from './models/ValidateCacheDto';
export type { VerifyEmailDto } from './models/VerifyEmailDto';
export { VgcIngestionJobDto } from './models/VgcIngestionJobDto';
export type { VgcMetaSlotDto } from './models/VgcMetaSlotDto';
export type { VgcPokemonDto } from './models/VgcPokemonDto';
export type { WarmupCacheDto } from './models/WarmupCacheDto';
export type { WeaponEntity } from './models/WeaponEntity';
export type { WeaponTreeEntity } from './models/WeaponTreeEntity';
export type { WeaponTreeNodeEntity } from './models/WeaponTreeNodeEntity';
export type { Weather } from './models/Weather';
export type { ZMove } from './models/ZMove';
