export enum WeaponKind {
  GREAT_SWORD = 'great-sword',
  LONG_SWORD = 'long-sword',
  SWORD_AND_SHIELD = 'sword-and-shield',
  DUAL_BLADES = 'dual-blades',
  HAMMER = 'hammer',
  HUNTING_HORN = 'hunting-horn',
  LANCE = 'lance',
  GUNLANCE = 'gunlance',
  SWITCH_AXE = 'switch-axe',
  CHARGE_BLADE = 'charge-blade',
  INSECT_GLAIVE = 'insect-glaive',
  LIGHT_BOWGUN = 'light-bowgun',
  HEAVY_BOWGUN = 'heavy-bowgun',
  BOW = 'bow',
}
