export const APPS_REPOSITORY_TOKEN = Symbol('IAppsRepository');
export const USER_APPS_REPOSITORY_TOKEN = Symbol('IUserAppsRepository');
export const ACHIEVEMENTS_REPOSITORY_TOKEN = Symbol('ACHIEVEMENTS_REPOSITORY');
export const REPLAYS_REPOSITORY_TOKEN = Symbol('REPLAYS_REPOSITORY');
export const ARCADE_STREAK_REPOSITORY_TOKEN = Symbol('ARCADE_STREAK_REPOSITORY');
export const ARCADE_INVENTORY_REPOSITORY_TOKEN = Symbol('ARCADE_INVENTORY_REPOSITORY');
export const ARCADE_USER_REPOSITORY_TOKEN = Symbol('ARCADE_USER_REPOSITORY');
export const ARCADE_LOOTBOX_REPOSITORY_TOKEN = Symbol('ARCADE_LOOTBOX_REPOSITORY');