module.exports = {
    testEnvironment: 'node',
    rootDir: './',
    setupFiles: ['<rootDir>/jest.setup.ts'],
    transform: {
      '^.+\\.tsx?$': ['ts-jest', { tsconfig: './tsconfig.spec.json' }],
    },
    modulePaths: ['<rootDir>'],
    moduleNameMapper: {
      '^@/(.*)$': '<rootDir>/src/$1',
      '^@api/(.*)$': '<rootDir>/src/api/$1',
      '^@repositories/(.*)$': '<rootDir>/src/api/_repositories/$1',
      '^@boffmedia/shared(.*)$': '<rootDir>/../../packages/shared/src$1',
    },
    modulePathIgnorePatterns: ['src/typings'],
    testPathIgnorePatterns: [
      '/node_modules./',
      '<rootDir>/(coverage|dist|lib|tmp)./',
      '<rootDir>/src/api/smartrotom/arcade/arcade.controller.integration.spec.ts',
      '<rootDir>/src/api/smartrotom/arcade/arcade.facade.service.spec.ts',
    ],
    coverageDirectory: 'coverage',
    coverageProvider: 'v8',
    maxWorkers: Number(process.env.JEST_MAX_WORKERS ?? 2),
    workerIdleMemoryLimit: '512MB',
    coverageReporters: ['text-summary', 'cobertura', 'lcov'],
    collectCoverage: false,
    collectCoverageFrom: [
      'src/**/*.ts',
      '!src/**/*.spec.ts',
      '!src/**/*.e2e-spec.ts',
      '!src/main.ts',
      '!src/**/*.entity.ts',
      '!src/**/*.dto.ts',
      '!src/**/*.enum.ts',
      '!src/**/*.module.ts',
      '!src/**/*.interface.ts',
      '!src/**/vgc/mod/**',
    ],
    coverageThreshold: {
      global: {
        branches: 40,
        functions: 40,
        lines: 40,
        statements: 40,
      },
    },
  };